#include QMK_KEYBOARD_H
#include "jumar.h"

#define LAYOUT LAYOUT_ortho_5x15

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_0_QWERTY] = LAYOUT_wrapper(
                    ROW5_LEFT_BASE, XXXXXXX, TG(5), XXXXXXX, ROW5_RIGHT_BASE,
                    ROW4_LEFT_BASE, XXXXXXX, TG(4), XXXXXXX, ROW4_RIGHT_BASE,
                    ROW3_LEFT_BASE, XXXXXXX, TG(3), XXXXXXX, ROW3_RIGHT_BASE,
                    ROW2_LEFT_BASE, XXXXXXX, TG(2), XXXXXXX, ROW2_RIGHT_BASE,
                  FOUR_TRNS, ROW1_LEFT_BASE, TG(1), ROW1_RIGHT_BASE, FOUR_TRNS
    ),
	[_1_SYMBOLS_NUMPAD] = LAYOUT_wrapper(
                    ROW5_LEFT_SYMB_NUMPAD, XXXXXXX, XXXXXXX, XXXXXXX, ROW5_RIGHT_SYMB_NUMPAD,
                    ROW4_LEFT_SYMB_NUMPAD, XXXXXXX, XXXXXXX, XXXXXXX, ROW4_RIGHT_SYMB_NUMPAD,
                    ROW3_LEFT_SYMB_NUMPAD, XXXXXXX, XXXXXXX, XXXXXXX, ROW3_RIGHT_SYMB_NUMPAD,
                    ROW2_LEFT_SYMB_NUMPAD, XXXXXXX, XXXXXXX, XXXXXXX, ROW2_RIGHT_SYMB_NUMPAD,
                  FOUR_TRNS, ROW1_LEFT_SYMB_NUMPAD, _______, ROW1_RIGHT_SYMB_NUMPAD, FOUR_TRNS
    ),
	[_2_MOUSE_MEDIA] = LAYOUT_wrapper(
                    ROW5_LEFT_MOUSE_MEDIA, XXXXXXX, XXXXXXX, XXXXXXX, ROW5_RIGHT_MOUSE_MEDIA,
                    ROW4_LEFT_MOUSE_MEDIA, XXXXXXX, XXXXXXX, XXXXXXX, ROW4_RIGHT_MOUSE_MEDIA,
                    ROW3_LEFT_MOUSE_MEDIA, XXXXXXX, XXXXXXX, XXXXXXX, ROW3_RIGHT_MOUSE_MEDIA,
                    ROW2_LEFT_MOUSE_MEDIA, XXXXXXX, _______, XXXXXXX, ROW2_RIGHT_MOUSE_MEDIA,
                  FOUR_TRNS, ROW1_LEFT_MOUSE_MEDIA, XXXXXXX, ROW1_RIGHT_MOUSE_MEDIA, FOUR_TRNS
    ),
	[_3_NAV] = LAYOUT_wrapper(
                    ROW5_LEFT_NAV_CPY_PASTA, XXXXXXX, XXXXXXX, XXXXXXX, ROW5_RIGHT_NAV_CPY_PASTA,
                    ROW4_LEFT_NAV_CPY_PASTA, XXXXXXX, XXXXXXX, XXXXXXX, ROW4_RIGHT_NAV_CPY_PASTA,
                    ROW3_LEFT_NAV_CPY_PASTA, XXXXXXX, _______, XXXXXXX, ROW3_RIGHT_NAV_CPY_PASTA,
                    ROW2_LEFT_NAV_CPY_PASTA, XXXXXXX, XXXXXXX, XXXXXXX, ROW2_RIGHT_NAV_CPY_PASTA,
                  FOUR_TRNS, ROW1_LEFT_NAV_CPY_PASTA, XXXXXXX, ROW1_RIGHT_NAV_CPY_PASTA, FOUR_TRNS
    ),
	[_4_GAM] = LAYOUT_wrapper(
                    ROW5_LEFT_GAMING, XXXXXXX, XXXXXXX, XXXXXXX, ROW5_RIGHT_GAMING,
                    ROW4_LEFT_GAMING, XXXXXXX, _______, XXXXXXX, ROW4_RIGHT_GAMING,
                    ROW3_LEFT_GAMING, XXXXXXX, XXXXXXX, XXXXXXX, ROW3_RIGHT_GAMING,
                    ROW2_LEFT_GAMING, XXXXXXX, XXXXXXX, XXXXXXX, ROW2_RIGHT_GAMING,
                  FOUR_TRNS, ROW1_LEFT_GAMING, XXXXXXX, ROW1_RIGHT_GAMING, FOUR_TRNS
    ),
   [_5_RGB] = LAYOUT_wrapper(
                    ROW5_LEFT_RGB, XXXXXXX, _______, XXXXXXX, ROW5_RIGHT_RGB,
                    ROW4_LEFT_RGB, XXXXXXX, XXXXXXX, XXXXXXX, ROW4_RIGHT_RGB,
                    ROW3_LEFT_RGB, XXXXXXX, XXXXXXX, XXXXXXX, ROW3_RIGHT_RGB,
                    ROW2_LEFT_RGB, XXXXXXX, XXXXXXX, XXXXXXX, ROW2_RIGHT_RGB,
                  FOUR_TRNS, ROW1_LEFT_RGB, XXXXXXX, ROW1_RIGHT_RGB, FOUR_TRNS
    ),
};

void matrix_init_user(void) {
    matrix_init_user_RGB_LYR();
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  process_record_user_RGB(keycode, record);
  return true;
}
