OLED_ENABLE = yes
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
VIA_ENABLE = yes
NKRO_ENABLE = yes
KEY_LOCK_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
ENCODER_MAP_ENABLE = yes
