#pragma once

#define UNICODE

#ifdef RGBLIGHT_ENABLE
  #ifdef RGBLIGHT_ANIMATIONS
    #undef RGBLIGHT_ANIMATIONS
  #endif
  #define RGBLIGHT_SLEEP
  #define RGBLIGHT_EFFECT_BREATHING
  #define RGBLIGHT_EFFECT_SNAKE
  #define RGBLIGHT_EFFECT_KNIGHT
#endif  // RGBLIGHT_ENABLE

#if defined(LOCKING_SUPPORT_ENABLE)
  #undef LOCKING_SUPPORT_ENABLE
#endif

#if defined(LOCKING_RESYNC_ENABLE)
  #undef LOCKING_RESYNC_ENABLE
#endif
