#pragma once

#define UNICODE

#ifdef RGBLIGHT_ENABLE
#    define RGBLIGHT_SLEEP
#    ifdef RGBLIGHT_ANIMATIONS
#        undef RGBLIGHT_ANIMATIONS
#    endif
#    define RGBLIGHT_SLEEP
#    define RGBLIGHT_EFFECT_BREATHING
#    define RGBLIGHT_EFFECT_RAINBOW_MOOD
#    define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    define RGBLIGHT_EFFECT_STATIC_GRADIENT
#    define TWINKLE
#endif  // RGBLIGHT_ENABLE

#if defined(LOCKING_SUPPORT_ENABLE)
#    undef LOCKING_SUPPORT_ENABLE
#endif

#if defined(LOCKING_RESYNC_ENABLE)
#    undef LOCKING_RESYNC_ENABLE
#endif
