#pragma once

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN A5
#define SPI_MISO_PIN A6
#define SPI_MOSI_PIN A7

#define POINTING_DEVICE_CS_PIN A4
#define POINTING_DEVICE_MOTION_PIN A3
#define POINTING_DEVICE_TASK_THROTTLE_MS 1

#define ENCODER_RESOLUTION 2

#ifdef RGB_MATRIX_ENABLE

#define WS2812_BITBANG_NOP_FUDGE 0
#define WS2812_PWM_DRIVER PWMD3
#define WS2812_PWM_CHANNEL 1
#define WS2812_DMA_STREAM STM32_DMA1_STREAM1
#define WS2812_DMA_CHANNEL 1
#define WS2812_DMAMUX_ID STM32_DMAMUX1_TIM3_UP

#endif


