RGBLIGHT_ENABLE = yes
BACKLIGHT_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
# COMBO_ENABLE = yes
BOOTMAGIC_ENABLE = full
MOUSEKEY_ENABLE = yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = no
AUTO_SHIFT_ENABLE = no

EXTRAFLAGS += -flto
