#pragma once

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN A5
#define SPI_MISO_PIN A6
#define SPI_MOSI_PIN A7

#define POINTING_DEVICE_CS_PIN A4
#define POINTING_DEVICE_MOTION_PIN A3
#define POINTING_DEVICE_TASK_THROTTLE_MS 1

#define ENCODER_RESOLUTION 2

