#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include "../../config.h"

// place overrides here
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 3
#define RGBLIGHT_EFFECT_KNIGHT_LENGTH 2
#define RGBLIGHT_EFFECT_KNIGHT_OFFSET 2

#define RGBLED_BREATHING_INTERVAL_COUNT 1
#define RGBLED_RAINBOW_MOOD_INTERVAL_COUNT 1
#define RGBLED_RAINBOW_SWIRL_INTERVAL_COUNT 1
#define RGBLED_SNAKE_INTERVAL_COUNT 1
#define RGBLED_KNIGHT_INTERVAL_COUNT 1
#define RGB_INTERVALS_SET

#endif
