BACKLIGHT_ENABLE  = no
BOOTMAGIC_ENABLE  = no
COMMAND_ENABLE    = yes
CONSOLE_ENABLE    = yes
EXTRAKEY_ENABLE   = yes
MOUSEKEY_ENABLE   = yes
NKRO_ENABLE       = yes
SLEEP_LED_ENABLE  = no
TAP_DANCE_ENABLE  = yes
UNICODE_ENABLE    = yes
VISUALIZER_ENABLE = no

EXTRAFLAGS += -flto
