#pragma once

#define MASTER_RIGHT

#define USB_MAX_POWER_CONSUMPTION 500

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_LIMIT_VAL 70
    #define RGBLIGHT_SLEEP
    #define WS2812_DI_PIN D3
    #define RGBLED_NUM 72
    #define RGBLED_SPLIT { 36,36 }
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    #define RGBLIGHT_EFFECT_BREATHING
    #define RGBLIGHT_EFFECT_CHRISTMAS
#endif

#define QUICK_TAP_TERM 0
#ifdef TAPPING_TERM
    #undef TAPPING_TERM
    #define TAPPING_TERM 200
#endif
#define ENCODER_DIRECTION_FLIP

#define POINTING_DEVICE_ROTATION_270
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define CIRQUE_PINNACLE_DIAMETER_MM 35
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE


#define SPLIT_LAYER_STATE_ENABLE
#define CUSTOM_SPLIT_TRANSPORT_SYNC
#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_A, RPC_ID_USER_OLED_KEYLOG_STR, RPC_ID_USER_LAST_KEYCODE
#define RPC_M2S_BUFFER_SIZE 64
#define RPC_S2M_BUFFER_SIZE 64
#define OLED_KEYLOGGER_SIZE 5
#define OLED_LAST_KEYCODE_SIZE 2

#define NO_ACTION_ONESHOT
#define NO_MUSIC_MODE
#define NO_USB_STARTUP_CHECK