MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
CUSTOM_OLED_DRIVER ?= yes
DEFERRED_EXEC_ENABLE = yes
CUSTOM_SPLIT_TRANSPORT_SYNC = yes
RGBLIGHT_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 