#define GDISP_DRIVER_VMT			    GDISPVMT_EMULATOR_LED_ERGODOX
#define GDISP_HARDWARE_DRAWPIXEL		TRUE
#define GDISP_HARDWARE_PIXELREAD		TRUE
#define GDISP_HARDWARE_CONTROL			TRUE
#define GDISP_LLD_PIXELFORMAT			GDISP_PIXELFORMAT_MONO
#define GDISP_SCREEN_WIDTH		        7
#define GDISP_SCREEN_HEIGHT		        7
#define ROTATE_180_IS_FLIP

#include "emulator/emulator_driver_impl.h"
