OLED_ENABLE = yes
OLED_DRIVER = SSD1306      # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = no     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
OS_DETECTION_ENABLE = yes
SPLIT_KEYBOARD = yes
SPLIT_DETECTED_OS_ENABLE = yes
TAP_DANCE_ENABLE = yes