BOOTLOADER = atmel-dfu

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no

AUTO_SHIFT_ENABLE = yes
DYNAMIC_MACRO_ENABLE = no
ENCODER_ENABLE = yes
MIDI_ENABLE = no
SEQUENCER_ENABLE = no

LTO_ENABLE = yes