#define MATRIX_ROW_PINS { D4, C6, D7, NO_PIN, B4 }
#define MATRIX_COL_PINS { F4, F5, F6, F7, B1, NO_PIN, B2 }

#define MATRIX_ROW_PINS_RIGHT { D4, C6, E6, NO_PIN, B4 }
#define MATRIX_COL_PINS_RIGHT { F4, F5, F6, F7, B3, NO_PIN, B2 }
