#define EXTENDED_MATRIX_ROW_PINS (MCU_GPIO, D0, 4), (MCU_GPIO, C0, 6), (MCU_GPIO, D0, 7), (NO_DEVICE, NO_INPUT, 0), (MCU_GPIO, B0, 4)
#define EXTENDED_MATRIX_COL_PINS \
        (MCU_GPIO, F0, 4), (MCU_GPIO, F0,5 ), (MCU_GPIO, F0,6 ), \
        (MCU_GPIO, F0, 7), (MCU_GPIO, B0, 1), (NO_DEVICE, NO_INPUT, 0), (MCU_GPIO, B0, 2)

#define EXTENDED_MATRIX_ROW_PINS_RIGHT (MCU_GPIO, D0, 4), (MCU_GPIO, C0, 6), (MCU_GPIO, E0, 6), (NO_DEVICE, NO_INPUT, 0), (MCU_GPIO, B0, 4)
#define EXTENDED_MATRIX_COL_PINS_RIGHT \
        (MCU_GPIO, F0, 4), (MCU_GPIO, F0,5 ), (MCU_GPIO, F0,6 ), \
        (MCU_GPIO, F0, 7), (MCU_GPIO, B0, 3), (NO_DEVICE, NO_INPUT, 0), (MCU_GPIO, B0, 2)
