BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
LEADER_ENABLE = yes

# Firmware Size Optimizations
EXTRAFLAGS += -flto
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
BLUETOOTH_ENABLE = no
OLED_DRIVER_ENABLE = no
AUDIO_ENABLE = no
# TAP_DANCE_ENABLE   = no