#pragma once

#define TAPPING_TOGGLE 2
#define TAPPING_TERM 150

#define MOUSEKEY_WHEEL_DELAY 20
#define MOUSEKEY_WHEEL_INTERVAL 80
#define MOUSEKEY_WHEEL_MAX_SPEED 4
#define MOUSEKEY_WHEEL_TIME_TO_MAX 30