SRC += draevin.c

LTO_ENABLE = yes

TAP_DANCE_ENABLE = yes
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = yes
