// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// framebuffer
#if defined(ENABLE_RGB_MATRIX_TYPING_HEATMAP)
#    define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#endif
#if defined(ENABLE_RGB_MATRIX_DIGITAL_RAIN)
#    define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#endif

// reactive
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SPLASH)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_MULTISPLASH)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_SPLASH)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS)
#    define RGB_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_RGB_MATRIX_SOLID_MULTISPLASH)
#    define RGB_MATRIX_KEYPRESSES
#endif
