BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = no         # Console for debug
RGBLIGHT_ENABLE = no
WPM_ENABLE = yes
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Disable keyboard backlight functionality
AUDIO_ENABLE = no           # Audio output
VIA_ENABLE = no
LTO_ENABLE = yes            # Save space
