# Configuration for probot-stale - https://github.com/probot/stale

# General configuration

# Pull request specific configuration
pulls:
  staleLabel: awaiting changes
  # Number of days of inactivity before an Issue or Pull Request becomes stale
  daysUntilStale: 45
  # Number of days of inactivity before a stale Issue or Pull Request is closed.
  # Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
  daysUntilClose: 30
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    Thank you for your contribution!

    This pull request has been automatically marked as stale because it has not had
    activity in the last 45 days. It will be closed in 30 days if no further activity occurs.
    Please feel free to give a status update now, or re-open when it's ready.
    
    For maintainers: Please label with `awaiting review`, `breaking_change`, `in progress`, or `on hold` to prevent 
    the issue from being re-flagged.
  # Comment to post when closing a stale Issue or Pull Request.
  closeComment: >
    Thank you for your contribution!

    This pull request has been automatically closed because it has not had activity in the last 30 days.
    Please feel free to give a status update now, ping for review, or re-open when it's ready.
  # Limit the number of actions per hour, from 1-30. Default is 30
  limitPerRun: 30
  exemptLabels:
    - awaiting review
    - breaking_change
    - in progress
    - on hold

# Issue specific configuration
issues:
  staleLabel: stale
  limitPerRun: 10
  daysUntilStale: 90
  daysUntilClose: 30
  markComment: >
    This issue has been automatically marked as stale because it has not had activity in the
    last 90 days. It will be closed in the next 30 days unless it is tagged properly or other activity
    occurs.
    
    For maintainers: Please label with `bug`, `in progress`, `on hold`, `discussion` or `to do` to prevent 
    the issue from being re-flagged.
  closeComment: >
    This issue has been automatically closed because it has not had activity in the last 30 days.
    If this issue is still valid, re-open the issue and let us know.
  exemptLabels:
    - bug
    - in progress
    - on hold
    - discussion
    - to do
