#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#undef  BACKLIGHT_LEVELS
#define BACKLIGHT_LEVELS 8

/* ws2812 RGB LED */
#ifndef RGBLIGHT_ENABLE
#undef RGB_DI_PIN
#endif
#if defined(KEYBOARD_preonic_rev2)
  #define RGB_DI_PIN B3
  #undef RGBLED_NUM
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
  #define RGBLED_NUM 11     // Number of LEDs
  #undef RGBLIGHT_HUE_STEP
  #define RGBLIGHT_HUE_STEP 8
  #undef RGBLIGHT_SAT_STEP
  #define RGBLIGHT_SAT_STEP 8
  #undef RGBLIGHT_VAL_STEP
  #define RGBLIGHT_VAL_STEP 8
#endif

// for the split boards //
#define EE_HANDS

#endif
