COMMAND_ENABLE     			= no       # Commands for debug and configuration
AUDIO_ENABLE       			= no
NKRO_ENABLE        			= no
BACKLIGHT_ENABLE   			= no
SWAP_HANDS_ENABLE  			= no
INDICATOR_LIGHTS            = no
RGBLIGHT_STARTUP_ANIMATION  = no
CUSTOM_UNICODE_ENABLE       = no
CUSTOM_SPLIT_TRANSPORT_SYNC = no
RGBLIGHT_ENABLE 			= yes       #by default this is no, but for the colors to work it needs to be `yes`
RGB_MATRIX_ENABLE 			= no #by default this is yes, but for the colors to work it needs to be `no`
