#pragma once


#undef PRODUCT
#define PRODUCT         SilverBullet44

#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING


#define K_TL0 KC_LSFT
#define K_TL1 LT(1,KC_BSPC)
#define K_TL2 LT(2,KC_TAB)
#define K_TL3 MO(3)

#define KX__SFT KC_RSFT
#define KX__CTL KC_RCTL
#define KX__ALT KC_RALT
#define KX__GUI KC_RGUI

#define K_IM_EN KC_HAEN
#define K_IM_JP KC_HANJ



#define LED_HIGH  96
#define LED_MID   16
#define LED_LOW    2


