/* chrisae9 Config */
#pragma once

/* Light Config */
#undef RGBLIGHT_HUE_STEP
#define RGBLIGHT_HUE_STEP 1
#undef RGBLIGHT_SAT_STEP
#define RGBLIGHT_SAT_STEP 8
#undef RGBLIGHT_VAL_STEP
#define RGBLIGHT_VAL_STEP 16

/* In order */
#define RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE


/* Mouse Config */
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 15
#define MOUSEKEY_TIME_TO_MAX 10
#define MOUSEKEY_MAX_SPEED 2.5
