SRC +=	keyboard.c \
	command.c \
	layer.c \
	timer.c \
	print.c \
	util.c

# Option modules
ifdef MOUSEKEY_ENABLE
    SRC += mousekey.c
endif

ifdef PS2_MOUSE_ENABLE
    SRC += ps2.c \
	   ps2_mouse.c
endif

include $(COMMON_DIR)/Makefile.rules
