make -j emery65:chrisgve
make -j mechlovin/adelais/standard_led/arm/rev4/apm32f103:chrisgve
make -j mechlovin/adelais/standard_led/arm/rev4/stm32f303:chrisgve_hhkb
make -j mechlovin/adelais/standard_led/arm/rev4/apm32f103:chrisgve_hhkb
make -j kbdfans/odin/soldered:chrisgve
make -j preonic/rev3:chrisgve_2x2u
make -j preonic/rev3:chrisgve
make -j zlant_xl:chrisgve
make -j mode/m65s:chrisgve
make -j cannonkeys/adelie:chrisgve
make -j cannonkeys/instant60:chrisgve
make -j cannonkeys/savage65:chrisgve_tsangan
make -j dz60:chrisgve_tsangan
make -j dztech/dz60rgb_wkl/v2_1:chrisgve
make -j kbdfans/kbd67/rev2:chrisgve_v3
make -j winx:chrisgve
make -j hineybush/h60:chrisgve
make -j hifinger75:chrisgve
make -j bemeier/bmek/rev3:chrisgve
make -j kbdfans/D60_B:chrisgve

