#define COLOR HSV_GREEN // define solid color
#define BACKLIGHT_TIMEOUT 5 // (minutes)

#define USB_POLLING_INTERVAL_MS 1
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR

#undef USB2422_MANUFACTURER
#undef USB2422_PRODUCT
#define USB2422_MANUFACTURER "FML128.ch"
#define USB2422_PRODUCT "FMK128 Hub"
