SRC += matrix.c
CUSTOM_MATRIX = lite

MIDI_ENABLE = yes

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_CUSTOM_KB = yes

OLED_ENABLE = yes
## for both SH1106/SH1107
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
MUSIC_ENABLE = no

ENCODER_ENABLE = yes

#CONSOLE_ENABLE = yes
