USER_NAME := chrisgve
SRC += chrisgve.c

LTO_ENABLE = yes
# APPLE_FN_ENABLE = yes
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

SLEEP_LED_ENABLE = no
SHIFT_ENABLE = yes

ENCODER_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
