// Copyright 2023 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP22
#define I2C1_SCL_PIN GP23

#define AUDIO_PIN GP28
#define AUDIO_PWM_DRIVER PWMD6
#define AUDIO_INIT_DELAY
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A
#define STARTUP_SONG SONG(STARTUP_SOUND)

#define ANALOG_JOYSTICK_Y_AXIS_PIN GP26
#define ANALOG_JOYSTICK_X_AXIS_PIN GP27
// #define MASTER_RIGHT
#ifndef MASTER_RIGHT
#    define SPLIT_POINTING_ENABLE
#    define POINTING_DEVICE_ROTATION_90
#    define POINTING_DEVICE_RIGHT
#else
#    define POINTING_DEVICE_ROTATION_90
#endif
#define ANALOG_JOYSTICK_SPEED_REGULATOR 15

#define OLED_BRIGHTNESS 128

#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD
