// Copyright 2023 Zach DeCook
// SPDX-License-Identifier: GPL-3.0-only
#pragma once

#define RP2040_FLASH_GENERIC_03H
#define MATRIX_ROWS 14
#define MATRIX_COLS 10

// WS2812_BYTE_ORDER defined by revision
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_MATRIX_LED_COUNT 140
#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_BREATHING
// #define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS

#define AUDIO_PIN GP23
// From the data sheet, pin 23 is PWM3 B
#define AUDIO_PWM_DRIVER PWMD3
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_B
#define AUDIO_INIT_DELAY
#define AUDIO_ENABLE_TONE_MULTIPLEXING
#define AUDIO_TONE_MULTIPLEXING_RATE_DEFAULT 50

// From the data sheet, pins 16/17 can use I2C0 DA/CL
#define I2C_DRIVER I2CD0
// (The name of these defines is confusing...)
#define I2C1_SDA_PIN GP16
#define I2C1_SCL_PIN GP17
#define OLED_BRIGHTNESS 55
#define OLED_IC OLED_IC_SH1106
// OLED_DISPLAY_ defined by revision

#define ENCODER_DEFAULT_POS 0x3
