// Copyright 2023 Zach DeCook
// SPDX-License-Identifier: GPL-3.0-only

#define RP2040_FLASH_GENERIC_03H

#define MIDI_ADVANCED

#define RGB_MATRIX_LED_COUNT 140
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE

// #define AUDIO_PIN GP23
// #define AUDIO_PWM_DRIVER PWMD0
// #define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A

// #define I2C_DRIVER I2CD0
