#ifndef CONFIG_BERFARAH_H
#define CONFIG_BERFARAH_H

#include QMK_KEYBOARD_CONFIG_H

#undef TAPPING_TERM
#define TAPPING_TERM 150

#define RGBLIGHT_EFFECT_BREATHE_CENTER 1.4
#define RGBLIGHT_EFFECT_BREATHE_MAX 150

#undef IGNORE_MOD_TAP_INTERRUPT
#endif
