#pragma once

//dpi settings
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 700
#define CHARYBDIS_MINIMUM_SNIPING_DPI 300
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
#define CHARYBDIS_DRAGSCROLL_BUFFER_SIZE 2

//combos
#define COMBO_VARIABLE_LEN
#define COMBO_TERM 60
