#pragma once

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 12
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_TIME_TO_MAX 60

#define TAPPING_TERM 180
#define IGNORE_MOD_TAP_INTERRUPT

#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_ALPHA

#define ENCODERS_PAD_A { B3 }
#define ENCODERS_PAD_B { B2 }
#define ENCODERS_PAD_A_RIGHT { B3 }
#define ENCODERS_PAD_B_RIGHT { B2 }
#define ENCODER_RESOLUTION 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define RGBLIGHT_LAYERS_RETAIN_VAL
#define RGB_DISABLE_WHEN_USB_SUSPENDED