#pragma once

#define MASTER_LEFT
#define NO_ACTION_ONESHOT

#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_SINGLE_REPORT

#define TAPPING_TERM 170

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

