// Copyright 2025 @shetty-tejas
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define MASTER_LEFT

#define NO_ACTION_ONESHOT

#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_SINGLE_REPORT

#define TAPPING_TERM 200
#define QUICK_TAP_TERM TAPPING_TERM

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

