# build options
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = yes

BACKLIGHT_ENABLE = no
BACKLIGHT_CUSTOM_DRIVER = no

RGBLIGHT_ENABLE = no
RGBLIGHT_CUSTOM_DRIVER = no

KEY_LOCK_ENABLE = yes
