#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [0] = LAYOUT(
		KC_COMM, KC_SLSH, KC_RABK, KC_N, KC_LALT, KC_X, KC_V, KC_7, KC_8, 
		KC_I, KC_P, KC_DEL, KC_Y, KC_TAB, KC_W, KC_R, KC_1, KC_2, 
		KC_0, KC_EQL, KC_BSLS, KC_8, KC_1, KC_4, KC_6, 
		KC_9, KC_MINS, KC_LABK, KC_7, KC_2, KC_3, KC_5, 
		KC_DOT, KC_3, KC_6, KC_F1, KC_9, KC_ESC, KC_F2, 
		KC_LSFT, 
		KC_M, KC_DOT, KC_SPC, KC_LGUI, KC_C, KC_B, KC_0, KC_ENT, 
		KC_LSFT, KC_L, KC_QUOT, KC_J, KC_MENU, KC_A, KC_D, KC_G, 
		KC_K, KC_SCLN, KC_SPC, KC_H, KC_Z, KC_S, KC_F, KC_4, KC_5, 
		KC_O, KC_INS, KC_ENT, KC_U, KC_Q, KC_E, KC_T, 
		KC_LCTL, 
		KC_LCTL)
}
