EXTRAKEY_ENABLE  = yes
NKRO_ENABLE      = yes

BACKLIGHT_ENABLE = yes
MOUSEKEY_ENABLE  = no
AUDIO_ENABLE     = no
RGBLIGHT_ENABLE  = yes
LEADER_ENABLE    = no
MIDI_ENABLE      = no
BLUETOOTH_ENABLE = no
