#define GDISP_DRIVER_VMT		    	GDISPVMT_EMULATOR_LCD_ERGODOX
#define GDISP_HARDWARE_DRAWPIXEL		TRUE
#define GDISP_HARDWARE_PIXELREAD		TRUE
#define GDISP_HARDWARE_CONTROL			TRUE
#define GDISP_LLD_PIXELFORMAT			GDISP_PIXELFORMAT_MONO
#define GDISP_SCREEN_WIDTH		        128
#define GDISP_SCREEN_HEIGHT		        32
#define ROTATE_180_IS_FLIP

#include "emulator/emulator_driver_impl.h"
