// Copyright 2021 Scott Bennett (@SBennett13)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define NO_MUSIC_MODE
#define FORCE_NKRO

// I don't use a bunch of layers
#define LAYER_STATE_8BIT

// Disable the RGB Light (underglow) stuff
#undef RBGLIGHT_ANIMATIONS
#undef RBGLIGHT_EFFECT_BREATHING
#undef RBGLIGHT_EFFECT_RAINBOW_MOOD
#undef RBGLIGHT_EFFECT_RAINBOW_SWIRL
#undef RBGLIGHT_EFFECT_SNAKE
#undef RBGLIGHT_EFFECT_KNIGHT
#undef RBGLIGHT_EFFECT_CHRISTMAS
#undef RBGLIGHT_EFFECT_STATIC_GRADIENT
#undef RBGLIGHT_EFFECT_RGB_TEST
#undef RBGLIGHT_EFFECT_ALTERNATING
#undef RBGLIGHT_EFFECT_TWINKLE

// No Cherry MX Lock switch
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

// No oneshot (Active until another key hit)
#define NO_ACTION_ONESHOT

// Remove some RGB
#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
