#pragma once

#define UNICODE_SELECTED_MODES UC_MAC, UC_LNX

#define ONESHOT_TAP_TOGGLE 5
#define ONESHOT_TIMEOUT 5000

#undef TAP_CODE_DELAY
#define TAP_CODE_DELAY 5 //DEFAULT: 100

//#define UNICODE_SCRIPT_MODE_ENABLE
