/* SPDX-License-Identifier: GPL-2.0-or-later */
#include QMK_KEYBOARD_H

#define FN_MO13 MO(1)
#define FN_MO23 MO(2)


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		LALT_T(KC_TAB), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO,
		KC_LCTL, KC_A, KC_S, KC_D, LSFT_T(KC_F), KC_G, KC_NO,
		KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,
		OSM(MOD_HYPR), FN_MO13, LGUI_T(KC_ENT),
		KC_ESC, KC_P, KC_O, KC_I, KC_U, KC_Y, KC_NO,
		KC_QUOT, KC_SCLN, KC_L, KC_K, RSFT_T(KC_J), KC_H, KC_NO,
		KC_RSFT, KC_SLSH, KC_DOT, KC_COMM, KC_M, KC_N,
		KC_BSPC, FN_MO23, KC_SPC
	),
	[1] = LAYOUT(
		KC_TRNS, LSFT(KC_1), LSFT(KC_2), LSFT(KC_3), LSFT(KC_4), LSFT(KC_5), KC_TRNS,
		KC_TRNS, KC_1, KC_2, KC_3, LSFT_T(KC_4), KC_5, KC_TRNS,
		KC_TRNS, KC_6, KC_7, KC_8, KC_9, KC_0,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, LSFT(KC_0), LSFT(KC_9), LSFT(KC_8), LSFT(KC_7), LSFT(KC_6), KC_TRNS,
		KC_BSLS, KC_RBRC, KC_LBRC, KC_GRV, RSFT_T(KC_EQL), KC_MINS, KC_TRNS,
		KC_TRNS, LSFT(KC_RBRC), LSFT(KC_LBRC), LSFT(KC_GRV), LSFT(KC_EQL), LSFT(KC_MINS),
		LALT(KC_BSPC), KC_TRNS, OSM(MOD_RGUI)
	),
	[2] = LAYOUT(
		KC_TRNS, KC_NO, KC_NO, KC_NO, KC_F2, KC_NO, KC_TRNS,
		KC_TRNS, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_NO, KC_TRNS,
		KC_TRNS, KC_NO, LGUI(LSFT(KC_4)), KC_NO, KC_NO, KC_NO,
		OSM(MOD_LALT|MOD_LGUI), KC_TRNS, OSM(MOD_LGUI),
		KC_TRNS, LGUI(LSFT(KC_T)), KC_MPLY, KC_MNXT, KC_MPRV, LCTL(LSFT(LALT(LGUI(KC_Y)))), KC_TRNS,
		LSFT(KC_BSLS), LGUI(KC_GRV), KC_RGHT, KC_UP, KC_DOWN, KC_LEFT, KC_TRNS,
		KC_TRNS, LGUI(KC_P0), LGUI(KC_PMNS), LGUI(LSFT(KC_RBRC)), LGUI(LSFT(KC_LBRC)), LGUI(KC_PPLS),
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[3] = LAYOUT(
		QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		RGB_TOG, RGB_HUI, RGB_SAI, RGB_VAI, KC_NO, KC_NO, KC_NO,
		KC_NO, RGB_HUD, RGB_SAD, RGB_VAD, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_NO, LALT(KC_RGHT), LALT(KC_UP), LALT(KC_DOWN), LALT(KC_LEFT), KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_TRNS, KC_TRNS, KC_TRNS
	),
	[4] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		TO(0), KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_D, KC_WH_U, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_MS_R, KC_MS_U, KC_MS_D, KC_MS_L, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_MS_R, KC_MS_D, KC_MS_L, KC_TRNS,
		TO(0), KC_BTN2, KC_BTN1
	),
	[5] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS
	)
};


layer_state_t layer_state_set_user(layer_state_t state) {
    return update_tri_layer_state(state, 1, 2, 3);
}

bool get_hold_on_other_key_press(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(2, KC_SPC):
            return true;
        case LSFT_T(KC_F):
        case RSFT_T(KC_J):
            return false;
        default:
            return false;
    }
}
