RAD
The Rad Macro Pad is a USB-C,  Macro Pad with 11 keys powered by QMK
* Keyboard Maintainer: Anubhav Dhiman 
* Hardware Supported: ATmega32U4)
Hardware Availability: Interest Check
Make example for this keyboard (after setting up your build environment):
make rad:default
Flashing example for this keyboard (after setting up the bootloadHID flashing environment)
make rad:default:flash
I have two example keymaps available, both the default and the encoderlayers keymap which demonstrates using different encoder functions based on the layer chosen.
See the build environment setup and the make instructions for more information. Brand new to QMK? Start with our Complete Newbs Guide.





