OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
AUTO_SHIFT_ENABLE = yes
EXTRAFLAGS += -flto
WPM_ENABLE = no
MOUSEKEY_ENABLE = No      # Mouse keys
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = no
BOOTMAGIC_ENABLE = full
