#pragma once

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 12
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_TIME_TO_MAX 60

#define TAPPING_TERM 180
#define IGNORE_MOD_TAP_INTERRUPT

#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_ALPHA

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define RGBLIGHT_LAYERS_RETAIN_VAL
#define RGB_DISABLE_WHEN_USB_SUSPENDED

#define COMBO_COUNT 11