SRC += muse.c

# Build Options
NKRO_ENABLE 		 = yes
EXTRAKEY_ENABLE  = yes
LEADER_ENABLE    = yes
TAP_DANCE_ENABLE = yes
AUDIO_ENABLE 		 = yes
COMMAND_ENABLE 	 = no
CONSOLE_ENABLE   = no
MOUSEKEY_ENABLE  = no
