message(STATUS "Custom Matrix: ${CUSTOM_MATRIX}")
set(CUSTOM_MATRIX "no" CACHE STRING "Custom matrix-scanning")
set_property(CACHE CUSTOM_MATRIX PROPERTY STRINGS yes lite no)
if(NOT ${CUSTOM_MATRIX} STREQUAL yes)
    target_sources(qmk PUBLIC quantum/matrix_common.c)
    if(NOT ${CUSTOM_MATRIX} STREQUAL lite)
        target_sources(qmk PUBLIC quantum/matrix.c)
    endif()
endif()