#include "../../config.h"


#undef RGBLED_BREATHING_INTERVAL_COUNT
#undef RGBLED_RAINBOW_MOOD_INTERVAL_COUNT
#undef RGBLED_RAINBOW_SWIRL_INTERVAL_COUNT
#undef RGBLED_SNAKE_INTERVAL_COUNT
#undef RGBLED_KNIGHT_INTERVAL_COUNT

#define RGBLED_BREATHING_INTERVAL_COUNT 1
#define RGBLED_RAINBOW_MOOD_INTERVAL_COUNT 1
#define RGBLED_RAINBOW_SWIRL_INTERVAL_COUNT 1
#define RGBLED_SNAKE_INTERVAL_COUNT 1
#define RGBLED_KNIGHT_INTERVAL_COUNT 1

#define RGB_INTERVALS_SET
