#define MOUSEKEY_DELAY             0
#define MOUSEKEY_INTERVAL          4
#define MOUSEKEY_MAX_SPEED         5
#define MOUSEKEY_TIME_TO_MAX       77
#define MOUSEKEY_WHEEL_MAX_SPEED   8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40
