VIA_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes
BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
EXTRAKEY_ENABLE = no

TD_LSFT_CAPSLOCK_ENABLE = yes
IDLE_TIMEOUT_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
INVERT_NUMLOCK_INDICATOR = yes
