OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more 
NKRO_ENABLE = yes
WPM_ENABLE = yes
EXTRAFLAGS += -flto
CONSOLE_ENABLE = no     # Console for debug(+400)
AUDIO_ENABLE   = no     # Audio output on port C6
LINK_TIME_OPTIMIZATION_ENABLE = yes
SPACE_CADET_ENABLE = no
EXTRAKEY_ENABLE = no
MOUSEKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
SWAP_HANDS_ENABLE = yes