#pragma once

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM 220

#define COMBO_TERM 30

#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL

#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1000
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200
#define CHARYBDIS_MINIMUM_SNIPING_DPI 400
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
