COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes

ENCODER_ENABLE = no

BOOTMAGIC_ENABLE = no
RGB_MATRIX_ENABLE = no
RGB_MATRIX_SUPPORTED = no
RGB_LIGHT_SUPPORTED = no
OLED_DRIVER_ENABLE = no
WPM_ENABLE = no

SRC += features/caps_word.c
