VIA_ENABLE = yes            # VIA support
LTO_ENABLE = yes            #

TAP_DANCE_ENABLE = yes

TD_LSFT_CAPSLOCK_ENABLE = yes
STARTUP_NUMLOCK_ON = yes

ENCODER_DEFAULTACTIONS_ENABLE = yes
INVERT_NUMLOCK_INDICATOR = yes
ALTTAB_SCROLL_ENABLE = yes
