#pragma once

#define PRIYADI_PROMETHIUM

#define RGBSPS_ENABLE
#define RGBSPS_DEMO_ENABLE

#define UNICODE_TYPE_DELAY 0

#define LAYOUT_DVORAK
#define LAYOUT_COLEMAK
#define LAYOUT_NORMAN
#define LAYOUT_WORKMAN

#define DOUBLESPACE_LAYER_ENABLE
// #define TOLELOT_ENABLE
