MOUSEKEY_ENABLE        = yes                # Enable Mouse keys
RGBLIGHT_ENABLE        = no                 # Disable WS2812 RGB underlight.
VIA_ENABLE             = no                 # Disable VIA
TAP_DANCE_ENABLE       = yes                # Enable Tap Dance
OLED_ENABLE            = yes                # Disable OLED
LTO_ENABLE             = yes			    # Enable Link Time Optimization
POINTING_DEVICE_ENABLE = no				    # Enable pointing device
UNICODE_ENABLE         = yes                # Enable unicode character calls
WPM_ENABLE             = yes				# Enable WPM tracking
