#define TAPPING_TERM 150
#define TAPPING_TOGGLE 2

#define MOUSEKEY_DELAY             200
#define MOUSEKEY_INTERVAL          60
#define MOUSEKEY_MAX_SPEED         50
#define MOUSEKEY_TIME_TO_MAX       80
#define MOUSEKEY_WHEEL_MAX_SPEED   8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 15
