OLED_ENABLE = yes
OLED_DRIVER = SSD1306

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = yes
UNICODE_ENABLE = yes
SPLIT_KEYBOARD = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes

NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
##qmk flash -kb splitkb/kyria/rev3 -km focalor -e CONVERT_TO=elite_pi