#pragma once

#define SQX_HS

#undef DRIVER_1_LED_TOTAL
#define DRIVER_1_LED_TOTAL 33
#undef DRIVER_2_LED_TOTAL
#define DRIVER_2_LED_TOTAL 31

#undef DRIVER_LED_TOTAL
#define DRIVER_LED_TOTAL (DRIVER_1_LED_TOTAL + DRIVER_2_LED_TOTAL)
