#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
		KC_PGUP, KC_PGDOWN, KC_PAUSE, KC_RIGHT,
		KC_HOME, KC_END, KC_UP, KC_DOWN,
		KC_INS, KC_DEL, KC_PSCR, KC_LEFT),
};
