
#define EE_HANDS

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define TAPPING_TERM 175
#define COMBO_TERM 300
#define PERMISSIVE_HOLD

#define UNICODE_SELECTED_MODES UC_MAC

#undef CHARYBDIS_AUTO_SNIPER_LAYER
#define CHARYBDIS_AUTO_SNIPER_LAYER 5
