#ifndef CONFIG_USER_H
#define CONFIG_USER_H
#include "../../config.h"

#undef TAPPING_TERM
#define TAPPING_TERM 150
#undef PERMISSIVE_HOLD
//#define IGNORE_MOD_TAP_INTERRUPT

#ifdef RGBLIGHT_ENABLE
#undef RGBLIGHT_SAT_STEP 
#define RGBLIGHT_SAT_STEP 12
#define RGBLIGHT_EFFECT_KNIGHT_LENGTH 7
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 7
#define RGBLIGHT_EFFECT_BREATHE_CENTER 1
#endif // RGBLIGHT_ENABLE


#endif
