#include "rgb.h"

#ifdef RGBLIGHT_EFFECT_BREATHING
const uint8_t RGBLED_BREATHING_INTERVALS[] PROGMEM = {20, 30, 5, 10};
#endif

#ifdef RGBLIGHT_EFFECT_RAINBOW_MOOD
const uint8_t RGBLED_RAINBOW_MOOD_INTERVALS[] PROGMEM = {20, 50, 100};
#endif

#ifdef RGBLIGHT_EFFECT_RAINBOW_SWIRL
const uint8_t RGBLED_RAINBOW_SWIRL_INTERVALS[] PROGMEM = {20, 50, 100};
#endif

#ifdef RGBLIGHT_EFFECT_SNAKE
const uint8_t RGBLED_SNAKE_INTERVALS[] PROGMEM = {20, 50, 100};
#endif

#ifdef RGBLIGHT_EFFECT_KNIGHT
const uint8_t RGBLED_KNIGHT_INTERVALS[] PROGMEM = {20, 50, 100};
#endif

const hsv_t GODSPEED_BLUE   = { .h = 280, .s = 68,  .v = RGBLIGHT_LIMIT_VAL };
const hsv_t GODSPEED_YELLOW = { .h = 38,  .s = 153, .v = RGBLIGHT_LIMIT_VAL };
