AUTO_SHIFT_ENABLE = no  # Enable autoshift
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = no
GRAVE_ESC_ENABLE = no
CONSOLE_ENABLE = no
SPACE_CADET_ENABLE    = no
GRAVE_ESC_ENABLE      = no
LTO_ENABLE = yes

SRC += cwebster2.c
SRC += keycodes.c
