// Copyright 2024 sanfeps (@sanfeps)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define EE_HANDS

// Bootmagic key for the right half: top-outer key (the `?` key on base layer).
// Left half uses default BOOTMAGIC_ROW/COLUMN [0,0] = ESC.
#define BOOTMAGIC_ROW_RIGHT 5
#define BOOTMAGIC_COLUMN_RIGHT 0

#ifdef RGB_MATRIX_ENABLE
#   define RGB_MATRIX_KEYPRESSES
#   define RGB_MATRIX_SLEEP
#   define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#   define RGB_MATRIX_HUE_STEP 8
#   define RGB_MATRIX_SAT_STEP 8
#   define RGB_MATRIX_VAL_STEP 8
#   define RGB_MATRIX_SPD_STEP 10

#   define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_TYPING_HEATMAP
#   define RGB_MATRIX_DEFAULT_HUE  128
#   define RGB_MATRIX_DEFAULT_SAT  255
#   define RGB_MATRIX_DEFAULT_VAL  200
#   define RGB_MATRIX_DEFAULT_SPD  127

#   define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#   define ENABLE_RGB_MATRIX_BREATHING
#   define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#   define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#   define ENABLE_RGB_MATRIX_PIXEL_FLOW

// Requires RGB_MATRIX_FRAMEBUFFER_EFFECTS
#   define ENABLE_RGB_MATRIX_TYPING_HEATMAP

// Requires RGB_MATRIX_KEYPRESSES
#   define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#   define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#   define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#   define ENABLE_RGB_MATRIX_SPLASH
#endif
