SPLIT_KEYBOARD = yes
#AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
OLED_ENABLE = yes
RGBLIGHT_ENABLE = yes # Enables QMK's RGB code
RAW_ENABLE = yes
OS_DETECTION_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes