DYNAMIC_MACRO_ENABLE = yes
LEADER_ENABLE = yes

# Firmware size Optimizations
EXTRAFLAGS += -flto
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE   = no
UNICODEMAP_ENABLE  = no
SPLIT_KEYBOARD    = no
