#include QMK_KEYBOARD_H


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
   LAYOUT_ortho_5x4(
		KC_NLCK, KC_PSLS, KC_PAST, LT(1, KC_PMNS), 
		KC_P7, KC_P8, KC_P9, KC_PMNS, 
		KC_P4, KC_P5, KC_P6, KC_PPLS, 
		KC_P1, KC_P2, KC_P3, KC_ENT, 
		KC_P0, KC_PDOT, KC_PDOT, KC_ENT),

	LAYOUT_ortho_5x4(
		RESET, KC_TRNS, KC_TRNS, KC_TRNS, 
		RGB_VAI, RGB_VAD, KC_TRNS, KC_TRNS, 
		RGB_HUI, RGB_HUD, KC_TRNS, KC_TRNS, 
		RGB_TOG, RGB_MOD, KC_TRNS, KC_TRNS, 
		BL_STEP, KC_TRNS, KC_TRNS, KC_TRNS)
};
