#ifndef CONFIG_HEARTROBOTNINJA_H
#define CONFIG_HEARTROBOTNINJA_H

#include "../../config.h"

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 1000

#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 1000

#undef TAPPING_TERM
#define TAPPING_TERM 200

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#endif