#pragma once
// Common settings
#define TAPPING_TERM 250
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define LEADER_TIMEOUT 500
#define LEADER_PER_KEY_TIMING

#if defined(KEYBOARD_crkbd)
#	define EE_HANDS
#	define OLED_TIMEOUT 5000
#	define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"
#endif

#if defined(RGB_MATRIX_ENABLE) && defined(KEYBOARD_bm40hsrgb)
#	define DISABLE_RGB_MATRIX_BAND_SAT
#	define DISABLE_RGB_MATRIX_BAND_VAL
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#	define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#	define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#	define DISABLE_RGB_MATRIX_CYCLE_ALL
#	define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#	define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
#	define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#	define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#	define DISABLE_RGB_MATRIX_DUAL_BEACON
#	define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#	define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#	define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#	define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#	define DISABLE_RGB_MATRIX_RAINDROPS
#	define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#	define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#	define RGB_DISABLE_WHEN_USB_SUSPENDED true
#else
#	undef DISABLE_RGB_MATRIX_SPLASH
#	undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#	undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#	define RGB_DISABLE_WHEN_USB_SUSPENDED true
#endif
