// Copyright 2018 Carlos Filoteo
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
#define WS2812_DI_PIN D3    // The pin the LED strip is connected to
#define RGBLIGHT_LED_COUNT 7     // Number of LEDs in your strip
