MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = ssd1306
LTO_ENABLE      = yes

CONSOLE_ENABLE = yes
CAPS_WORD_ENABLE = yes


CONVERT_TO		= rp2040_ce
BOARD 			= GENERIC_PROMICRO_RP2040