#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layers { _QWERTY = 0, _SYMBOLS, _FANDMEDIA, _LEAGUE };

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    /* ,-----------------------------------------.                              ,-----------------------------------------.
     * | TAB  |  Q   |  W   |  E   |  R   |  T   |                              |  Y   |  U   |  I   |  O   |  P   | \ |  |
     * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
     * |MT(MOD|  A   |  S   |  D   |  F   |  G   |                              |  H   |  J   |  K   |  L   | ; :  | ' "  |
     * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
     * | LSFT |  Z   |  X   |  C   |  V   |  B   | LCTL | LGUI |  |      | LSFT |  N   |  M   | , >  | . <  | / ?  | RSFT |
     * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
     *                      | DEL  | LGUI |MT(MOD|MT(MOD|MT(MOD|  |LT(2,K|LT(1,K|MT(MOD| RGUI | RSFT |
     *                      |      |      |      |      |      |  |      |      |      |      |      |
     *                      `----------------------------------'  `----------------------------------'
     *                                                                               generated by [keymapviz] */
    [_QWERTY] = LAYOUT(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, MT(MOD_LSFT, KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LCTL, KC_LGUI, KC_TRNS, KC_LSFT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_DEL, KC_LGUI, MT(MOD_LALT, KC_TAB), MT(MOD_LSFT, KC_BSPC), MT(MOD_LCTL, KC_ESC), LT(2, KC_ENT), LT(1, KC_SPC), MT(MOD_RALT, KC_TAB), KC_RGUI, KC_RSFT),

    /* ,-----------------------------------------.                              ,-----------------------------------------.
     * |      |  1   |  2   |  3   |  4   |  5   |                              |  6   |  7   |  8   |  9   |  0   |      |
     * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
     * |      |  !   |  @   |  #   |  $   |  %   |                              |  ^   |  &   |  *   | - _  | = +  |      |
     * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
     * |      |  <   |  [   |  {   |  (   | ' "  |      |      |  |      |      | ` ~  |  )   |  }   |  ]   |  >   |      |
     * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
     *                      |      |      |      |      |      |  |      |      |      |      |      |
     *                      |      |      |      |      |      |  |      |      |      |      |      |
     *                      `----------------------------------'  `----------------------------------'
     *                                                                               generated by [keymapviz] */

    [_SYMBOLS] = LAYOUT(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_TRNS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_MINS, KC_EQL, KC_TRNS, KC_TRNS, KC_LT, KC_LBRC, KC_LCBR, KC_LPRN, KC_QUOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_GRV, KC_RPRN, KC_RCBR, KC_RBRC, KC_GT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    /* ,-----------------------------------------.                              ,-----------------------------------------.
     * |      |  F5  |  F6  |  F7  |  F8  | WAKE |                              | MPLY | BTN1 | BTN2 | BTN3 | PSCR | MUTE |
     * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
     * |      |  F1  |  F2  |  F3  |  F4  | VOLU |                              | LEFT | DOWN |  UP  | RGHT | COPY |      |
     * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
     * |      |  F9  | F10  | F11  | F12  | VOLD |      |      |  |      |TG(3) | MS_L | MS_D | MS_U | MS_R | PSTE |      |
     * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
     *                      |      |      |      |      |      |  |      |      |      |      |      |
     *                      |      |      |      |      |      |  |      |      |      |      |      |
     *                      `----------------------------------'  `----------------------------------'
     *                                                                               generated by [keymapviz] */

    [_FANDMEDIA] = LAYOUT(KC_TRNS, KC_F5, KC_F6, KC_F7, KC_F8, KC_WAKE, KC_MPLY, KC_BTN1, KC_BTN2, KC_BTN3, KC_PSCR, KC_MUTE, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_VOLU, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_COPY, KC_TRNS, KC_TRNS, KC_F9, KC_F10, KC_F11, KC_F12, KC_VOLD, KC_TRNS, KC_TRNS, KC_TRNS, TG(3), KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_PSTE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

    /* ,-----------------------------------------.                              ,-----------------------------------------.
     * |      |      |      |      |      |      |                              | ESC  |  1   |  2   |  3   |  4   |      |
     * |------+------+------+------+------+------|                              |------+------+------+------+------+------|
     * |      |      |      |      |      |      |                              | TAB  |  Q   |  W   |  E   |  R   |      |
     * |------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------|
     * |      |      |      |      |      |      |      |      |  |TG(3) |      |  P   |  A   |  S   |  D   |  F   |      |
     * `------+------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------+------'
     *                      |      |      |      |      |      |  | LCTL | SPC  | LSFT | LALT |      |
     *                      |      |      |      |      |      |  |      |      |      |      |      |
     *                      `----------------------------------'  `----------------------------------'
     *                                                                               generated by [keymapviz] */

    [_LEAGUE] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TG(3), KC_TRNS, KC_P, KC_A, KC_S, KC_D, KC_F, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_SPC, KC_LSFT, KC_LALT, KC_NO)};
