AUTO_SHIFT_ENABLE = yes
AUTO_SHIFT_MODIFIERS = yes
UNICODE_ENABLE = yes

ifeq 
BACKLIGHT_ENABLE = yes
CONSOLE_ENABLE = no
endif
ifeq 
BACKLIGHT_ENABLE = no
CONSOLE_ENABLE = yes
EXTRALDFLAGS = -Wl,--build-id=none
UNICODE_ENABLE = yes
endif
