/*---RGB settings-------------------------------------------- */
#undef  RGBLIGHT_HUE_STEP
#undef  RGBLIGHT_SAT_STEP
#undef  RGBLIGHT_VAL_STEP
#undef  RGBLIGHT_EFFECT_CHRISTMAS_INTERVAL

#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 17
#define RGBLIGHT_VAL_STEP 17
#define RGBLIGHT_EFFECT_CHRISTMAS_INTERVAL 200