// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i qmklogo.png -f rgb565`

#pragma once

#include <qp.h>

extern const uint32_t gfx_qmklogo_length;
extern const uint8_t  gfx_qmklogo[10700];
