WS2812_DRIVER = vendor
#RGBLIGHT_ENABLE = yes

QUANTUM_PAINTER_ENABLE = yes
#QUANTUM_PAINTER_DRIVERS += st7735_spi
QUANTUM_PAINTER_DRIVERS += gc9107_spi
#QUANTUM_PAINTER_DRIVERS += gc9a01_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

#SPI_DRIVER_REQUIRED = yes

#SRC += rp2040_tft.c
SRC += graphics/Apple-Orchard-128x160.qgf.c graphics/qmklogo.qgf.c

#CONSOLE_ENABLE = yes