AUDIO_ENABLE:=no
BACKLIGHT_ENABLE:=no
BLUETOOTH_ENABLE:=no
BOOTMAGIC_ENABLE:=no
COMMAND_ENABLE:=no
CONSOLE_ENABLE:=no
EXTRAKEY_ENABLE:=yes
MIDI_ENABLE:=no
MOUSEKEY_ENABLE:=yes
NKRO_ENABLE:=no
RGBLIGHT_ENABLE:=no
SLEEP_LED_ENABLE:=no
TAP_DANCE_ENABLE:=yes
UNICODEMAP_ENABLE:=no
UNICODE_ENABLE:=no


