#pragma once

// Default configuration using 100kHz on I2CD1
#define SW_I2C_USE_I2C1 TRUE
//#define I2C_CLOCK_FREQUENCY 100000
//#define SW_I2C_USE_OSAL_DELAY TRUE
//#define I2C1_SCL_PAL_MODE PAL_MODE_ALTERNATE_OPENDRAIN
//#define I2C1_SDA_PAL_MODE PAL_MODE_ALTERNATE_OPENDRAIN