TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = yes
BOOTMAGIC_ENABLE = no
AUTO_SHIFT_ENABLE = no
AUDIO_ENABLE = no
CONSOLE_ENABLE = yes
ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
