#pragma once

#define VIAL_KEYBOARD_UID {0x5B, 0x05, 0x1C, 0x81, 0x84, 0x3F, 0xFF, 0x4F}

#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define RGB_MATRIX_LED_PROCESS_LIMIT (RGB_MATRIX_LED_COUNT + 12)

#define RGB_MODE_PLAIN

#define RGB_MODE_RAINBOW

#define RGB_MODE_SWIRL
