#pragma once

#define BOARD_OTG_VBUSIG
#define BOARD_OTG2_USES_ULPI

#define USB_DRIVER USBD2
#define USB_ENDPOINTS_ARE_REORDERABLE

#ifndef EARLY_INIT_PERFORM_BOOTLOADER_JUMP
#    define EARLY_INIT_PERFORM_BOOTLOADER_JUMP TRUE
#endif
