#include "h87a.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	KEYMAP(
		KC_ESC, KC_F1, KC_F3, KC_F5, KC_F7, KC_F10, KC_F12, KC_SLCK, 
		KC_F2, KC_F4, KC_F6, KC_F8, KC_F9, KC_F11, KC_PSCR, KC_PAUS, 
		KC_GRV, KC_2, KC_4, KC_6, KC_8, KC_0, KC_EQL, KC_BSPC, KC_HOME, 
		KC_1, KC_3, KC_5, KC_7, KC_9, KC_MINS, KC_BSPC, KC_INS, KC_PGUP, 
		KC_TAB, KC_W, KC_R, KC_Y, KC_I, KC_P, KC_RBRC, KC_END, 
		KC_Q, KC_E, KC_T, KC_U, KC_O, KC_LBRC, KC_BSLS, KC_DEL, KC_PGDN, 
		KC_CAPS, KC_S, KC_F, KC_H, KC_K, KC_SCLN, KC_QUOT, 
		KC_A, KC_D, KC_G, KC_J, KC_L, KC_QUOT, KC_ENT, 
		KC_LSFT, KC_Z, KC_C, KC_B, KC_M, KC_DOT, KC_LSFT, KC_UP, 
		KC_A, KC_X, KC_V, KC_N, KC_COMM, KC_SLSH, KC_QUOT, 
		KC_LCTL, KC_LALT, KC_LALT, MO(1), KC_DOWN, 
		KC_LGUI, KC_SPC, KC_LGUI, KC_LCTL, KC_LEFT, KC_RGHT),

	KEYMAP(
		KC_TRNS, KC_TRNS, KC_TRNS, RGB_TOG, RGB_HUI, RGB_SAD, RGB_VAD, BL_DEC, 
		KC_TRNS, KC_TRNS, RGB_MOD, RGB_HUD, RGB_SAI, RGB_VAI, BL_TOGG, BL_INC, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLU, 
		KC_TRNS, KC_TRNS, RESET, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MNXT, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, KC_VOLD, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),


};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
	return true;
}

