USER_NAME := rhruiz
RGBLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = lite
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
RAW_ENABLE = yes
LINK_TIME_OPTIMIZATION_ENABLE = yes

# BOOTLOADER = qmk-dfu
