// Copyright 2026 Timo Strube (@tstrube)
// SPDX-License-Identifier: GPL-3.0-or-later

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_ESC ,KC_GRV ,KC_1   ,KC_2   ,KC_3   ,KC_4   ,KC_5   ,KC_6   ,KC_MPLY,KC_MPLY,KC_7   ,KC_8   ,KC_9   ,KC_0   ,KC_MINS,KC_EQL ,KC_BSPC,KC_DEL ,
        KC_CUT ,KC_TAB ,KC_Q   ,KC_W   ,KC_E   ,KC_R   ,KC_T   ,KC_HOME,KC_MNXT,KC_MNXT,KC_PGUP,KC_Y   ,KC_U   ,KC_I   ,KC_O   ,KC_P   ,KC_LBRC,KC_RBRC,
        KC_COPY,KC_CAPS,KC_A   ,KC_S   ,KC_D   ,KC_F   ,KC_G   ,KC_END ,KC_MPRV,KC_MPRV,KC_PGDN,KC_H   ,KC_J   ,KC_K   ,KC_L   ,KC_SCLN,KC_QUOT,KC_ENT ,
        KC_PSTE,KC_LSFT,KC_Z   ,KC_X   ,KC_C   ,KC_V   ,KC_B   ,KC_MUTE,KC_VOLU,KC_VOLU,KC_MUTE,KC_N   ,KC_M   ,KC_COMM,KC_DOT ,KC_SLSH,KC_UP  ,KC_RSFT,
        KC_UNDO,KC_LCTL,MO(1)  ,KC_MENU,KC_LGUI,KC_LALT,KC_SPC         ,KC_VOLD,KC_VOLD        ,KC_SPC ,KC_PSCR,MO(1)  ,KC_BSLS,KC_LEFT,KC_DOWN,KC_RGHT
    ),
    [1] = LAYOUT(
        RM_TOGG,XXXXXXX,KC_F1  ,KC_F2  ,KC_F3  ,KC_F4  ,KC_F5  ,KC_F6  ,QK_BOOT,QK_BOOT,KC_F7  ,KC_F8  ,KC_F9  ,KC_F10 ,KC_F11 ,KC_F12 ,XXXXXXX,RM_TOGG,
        XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,
        RM_NEXT,RM_SPDU,RM_HUEU,RM_SATU,RM_VALU,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX,RM_VALU,RM_SATU,RM_HUEU,RM_SPDU,RM_NEXT,
        RM_PREV,RM_SPDD,RM_HUED,RM_SATD,RM_VALD,XXXXXXX,XXXXXXX,MD_JOYL,XXXXXXX,XXXXXXX,MD_JOYR,XXXXXXX,XXXXXXX,RM_VALD,RM_SATD,RM_HUED,RM_SPDD,RM_PREV,
        KC_AGIN,XXXXXXX,_______,XXXXXXX,XXXXXXX,XXXXXXX,XXXXXXX        ,XXXXXXX,XXXXXXX        ,XXXXXXX,XXXXXXX,_______,XXXXXXX,XXXXXXX,KC_PENT,XXXXXXX
    )
};
