name: Other issues
description: Anything else that doesn't fall into the above categories.
labels: ["help wanted", "question"]
body:
  - type: markdown
    attributes:
      value: |
        Provide a general summary of the changes you want in the title above.
  - type: markdown
    attributes:
      value: |
        Please check [https://docs.qmk.fm/#/support](https://docs.qmk.fm/#/support) for additional resources first. If that doesn't answer your question, choose the bug report template instead, as that may be more appropriate.
  - type: textarea
    attributes:
      label: Issue Description
      description: Describe your issue in as much detail as possible.