# RP2040-specific options
ALLOW_WARNINGS = yes
PICO_INTRINSICS_ENABLED = no # ATM Unsupported by ChibiOS.
# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
AUDIO_SUPPORTED = no
RGBLIGHT_ENABLE = no
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = yes
RGB_MATRIX_ENABLE = yes

SPLIT_KEYBOARD = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

SERIAL_DRIVER = vendor

LTO_ENABLE = yes
VIA_ENABLE = yes
UNICODE_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes

OS_DETECTION_ENABLE = yes
PROCESSOR = RP2040