F_CPU = 16000000
ARCH = AVR8
F_USB = $(F_CPU)
BOOTLOADER = caterina

CONSOLE_ENABLE = no
DEBUG_ENABLE = no
SPLIT_KEYBOARD = yes
DIPS_ENABLE = no
PHYSICAL_LEDS_ENABLE = yes
CAPS_LOCK_LED_ENABLE = yes
NUM_LOCK_LED_ENABLE = yes
SCROLL_LOCK_LED_ENABLE = yes
BACKLIGHT_ENABLE = yes
RGBLIGHT_ENABLE = yes
