// Copyright 2024 SDK (@sdk66)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#ifdef WIRELESS_ENABLE
#    define LPWR_TIMEOUT RGB_MATRIX_TIMEOUT
#endif

#define USB_POWER_EN_PIN B1 //USB ENABLE pin
#define LED_POWER_EN_PIN A5 //LED ENABLE pin
#define HS_BAT_CABLE_PIN A7 //USB insertion detection pin

#define BAT_FULL_PIN A15
#define BAT_FULL_STATE 1

/* Battery */
#define BATTERY_CAPACITY_LOW 15 
#define BATTERY_CAPACITY_STOP 0 

#define HS_RGB_INDICATOR_COUNT 108
#define HS_RGB_BAT_COUNT 1
#define RGB_MATRIX_BAT_INDEX_MAP {1, 2, 3, 4, 5,  6, 7, 8, 9, 10}

/* Device Connection RGB Indicator Light Index And Color */
#define HS_RGB_BLINK_INDEX_BT1 28 
#define HS_RGB_BLINK_INDEX_BT2 27 
#define HS_RGB_BLINK_INDEX_BT3 26 
#define HS_RGB_BLINK_INDEX_2G4 25 

#define HS_LBACK_COLOR_BT1 RGB_BLUE
#define HS_LBACK_COLOR_BT2 RGB_YELLOW
#define HS_LBACK_COLOR_BT3 RGB_PURPLE
#define HS_LBACK_COLOR_2G4 RGB_GREEN

#define HS_PAIR_COLOR_BT1 RGB_BLUE
#define HS_PAIR_COLOR_BT2 RGB_YELLOW
#define HS_PAIR_COLOR_BT3 RGB_PURPLE
#define HS_PAIR_COLOR_2G4 RGB_GREEN

/* Status Indicator Lamp */
#define HS_MATRIX_BLINK_INDEX_BAT 58
#define HS_RGB_INDEX_CAPS 30
#define HS_RGB_INDEX_WIN_LOCK 59
#define HS_RGB_BLINK_INDEX_VAI 45
#define HS_RGB_BLINK_INDEX_VAD 66
#define HS_RGB_BLINK_INDEX_SPI 67
#define HS_RGB_BLINK_INDEX_SPD 65
#define HS_RGB_BLINK_INDEX_WIN 31
#define HS_RGB_BLINK_INDEX_MAC 32

/* UART */
#define SERIAL_DRIVER SD3
#define SD1_TX_PIN C10
#define SD1_RX_PIN C11

/* Encoder */
#define ENCODER_MAP_KEY_DELAY 1

/* SPI */
#define SPI_DRIVER SPIDQ
#define SPI_SCK_PIN B3
#define SPI_MOSI_PIN B5
#define SPI_MISO_PIN B4

/* Flash */
#define EXTERNAL_FLASH_SPI_SLAVE_SELECT_PIN C12
#define WEAR_LEVELING_LOGICAL_SIZE (WEAR_LEVELING_BACKING_SIZE / 2)

/* RGB Matrix */
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

/* WS2812 */
#define WS2812_SPI_DRIVER SPIDM2
#define WS2812_SPI_DIVISOR 32
