#pragma once


#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD

#define ONESHOT_TAP_TOGGLE 10
#define ONESHOT_TIMEOUT 500
#define COMBO_TERM 200

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// disable shit
#define NO_MUSIC_MODE

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE    