#pragma once

#define HOLD_ON_OTHER_KEYPRESS
#define LAYER_STATE_8BIT
#define TAPPING_TERM 150
#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL
#define MK_C_INTERVAL_0 16
#define MK_C_INTERVAL_1 32
#define MK_C_INTERVAL_2 64