#pragma once

#ifdef KEYBOARD_evyd13_plain60

#define AUDIO_PIN B7
#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(GUITAR_SOUND)
#endif

#endif

#ifdef KEYBOARD_xd84

#undef RGBLED_NUM
#define RGBLED_NUM 20

#undef RGBLIGHT_EFFECT_BREATHING
#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
#undef RGBLIGHT_EFFECT_RGB_TEST
#undef RGBLIGHT_EFFECT_ALTERNATING
#undef RGBLIGHT_EFFECT_TWINKLE
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL

#endif
