#pragma once

#define PERMISSIVE_HOLD

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    0

#undef MOUSEKEY_WHEEL_MAX_SPEED
#undef MOUSEKEY_WHEEL_TIME_TO_MAX

#define MOUSEKEY_WHEEL_MAX_SPEED    1
#define MOUSEKEY_WHEEL_TIME_TO_MAX  0

#define MK_C_OFFSET_1 20
#define MK_C_OFFSET_2 30

#undef MK_MOMENTARY_ACCEL
