
KEYBOARD_SHARED_EP = yes

REPEAT_KEY_ENABLE = yes
RAW_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
OPT_DEFS += -DRGBLIGHT_CUSTOM_ENABLE
OPT_DEFS += -DRGB_MATRIX_DISABLE_SHARED_KEYCODES
SRC += rgblight.c
