#pragma once

#define ENCODERS_PAD_A { GP16, GP18, GP20}
#define ENCODERS_PAD_B { GP17, GP19, GP21}
#define MAX_QUEUED_ENCODER_EVENTS 4

#define MIDI_ADVANCED

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE