OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
AUTO_SHIFT_ENABLE = yes  # Enable autoshift
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
BOOTMAGIC_ENABLE = no
RAW_ENABLE = yes
Link_Time_Optimization = yes
EXTRAFLAGS = -flto
