#define VIAL_KEYBOARD_UID {0x81, 0xD4, 0x20, 0x6E, 0x3B, 0x5B, 0xBC, 0x9D}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 11 }

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
