/* Enable CapsLcok LED*/
#define CAPS_LOCK_LED_INDEX 40

#define VIA_EEPROM_ALLOW_RESET TRUE

/* RGB Matrix */
#ifdef RGB_MATRIX_ENABLE
//#   define RGB_MATRIX_KEYPRESSES // reacts to keypresses
#   define RGB_MATRIX_FRAMEBUFFER_EFFECTS
//#   define RGB_MATRIX_LED_FLUSH_LIMIT 26
#   define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
#   define RGB_MATRIX_DEFAULT_HUE 170
#	define RGB_MATRIX_DEFAULT_SAT 255
#	define RGB_MATRIX_DEFAULT_VAL 150
#   define RGB_MATRIX_DEFAULT_SPD 128
#	define RGB_MATRIX_SPD_STEP 48
#	define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200 
#	define RGB_MATRIX_VAL_STEP 50
#	define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT
#endif