#ifndef _GFXCONF_H
#define _GFXCONF_H

#define GFX_USE_GFILE				GFXON

#define GFILE_NEED_FATFS			GFXON
#define GFILE_NEED_NOAUTOMOUNT		GFXON
#define GFILE_NEED_PRINTG			GFXON

#endif /* _GFXCONF_H */