// TREASURE TYPE-30

#pragma once

#define NO_ACTION_TAPPING
#define NO_ACTION_ONESHOT

#define RGB_MATRIX_SLEEP
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT