#ifndef DISABLE_RGB_MATRIX_CUSTOM_berryLerp
    RGB_MATRIX_EFFECT(berryLerp)
#endif  // DISABLE_RGB_MATRIX_CUSTOM_berryLerp

#ifdef RGB_MATRIX_CUSTOM_EFFECT_IMPLS
    #ifndef DISABLE_RGB_MATRIX_CUSTOM_berryLerp
        #include "lighting/animations/common.h"
    #endif // DISABLE_RGB_MATRIX_CUSTOM_berryLerp -- add more conditions

    #ifndef DISABLE_RGB_MATRIX_CUSTOM_berryLerp
        #include "lighting/animations/berry_lerp.h"
    #endif // DISABLE_RGB_MATRIX_CUSTOM_berryLerp
#endif // RGB_MATRIX_CUSTOM_EFFECT_IMPLS
