RGBLIGHT_ENABLE    = no
RGB_MATRIX_ENABLE  = yes
MOUSEKEY_ENABLE    = no
NKRO_ENABLE        = no
OLED_ENABLE        = yes
LTO_ENABLE         = yes
SLEEP_LED_ENABLE   = yes
WPM_ENABLE         = yes


#Dont use
CONSOLE_ENABLE     = no
MOUSEKEY_ENABLE    = no
BOOTMAGIC_ENABLE   = no
COMBO_ENABLE	   = no
AUDIO_ENABLE	   = no
MIDI_ENABLE		   = no
BLUETOOTH_ENABLE   = no
