#include QMK_KEYBOARD_H

// https://github.com/qmk/qmk_firmware/blob/master/quantum/keymap_extras/keymap_german_mac_iso.h
#include "keymap_german_mac_iso.h"

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layers {
    _DEFAULT = 0,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_3x6_3(DE_EXLM, KC_Q, KC_W, KC_E, KC_R, KC_T, DE_Z, KC_U, KC_I, KC_O, KC_P, DE_QUES, KC_TAB, LSFT_T(KC_A), LCTL_T(KC_S), LALT_T(KC_D), LGUI_T(KC_F), KC_G, KC_H, RGUI_T(KC_J), RALT_T(KC_K), RCTL_T(KC_L), RSFT_T(KC_NO), KC_PENT, LGUI(LCTL((KC_Q))), DE_Y, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, DE_MINS, KC_ESCAPE, KC_NO, KC_NO, LT(2, KC_SPC), LT(1, KC_BSPC), KC_DEL, KC_NO),
                                                              [1] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P7, KC_P8, KC_P9, KC_PAST, KC_PMNS, KC_NO, LGUI(KC_A), LGUI(KC_X), LGUI(KC_C), LGUI(KC_V), LSFT(LGUI(DE_Z)), LGUI(DE_Z), KC_P4, KC_P5, KC_P6, KC_NO, KC_PPLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_P0, KC_P1, KC_P2, KC_P3, KC_NO, KC_PENT, KC_NO, KC_NO, MO(3), KC_TRNS, KC_NO, KC_NO),
                                                              [2] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_LGUI, KC_LALT, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, MO(3), KC_NO, KC_NO),
                                                              [3] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, DE_EQL, DE_AT, DE_SLSH, LSFT(LALT(DE_SLSH)), DE_DQUO, DE_QUOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_ASTR, KC_LPRN, LALT(KC_8), LALT(KC_9), DE_MINS, DE_UNDS, LALT(KC_5), LALT(KC_6), DE_CIRC, LSFT(DE_CIRC), KC_NO, LALT(KC_N), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, DE_PIPE, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO)};
