#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_5x4(RGB_TOG, RGB_SAI, RGB_SPI, BL_TOGG, RGB_MOD, RGB_SAD, RGB_SPD, BL_STEP, RGB_RMOD, RGB_VAI, KC_NO, BL_ON, RGB_HUI, RGB_VAD, TO(1), BL_OFF, RGB_HUD, BL_BRTG, BL_INC, BL_DEC),
	[1] = LAYOUT_ortho_5x4(KC_NO, KC_NO, KC_NO, KC_NO, KC_BTN1, KC_MS_U, KC_BTN2, KC_WH_U, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_WH_L, KC_WH_R, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
