#pragma once

#    define TAPPING_TERM 170
#    define TAPPING_TERM_PER_KEY
#    define QUICK_TAP_TERM TAPPING_TERM / 2
#    define QUICK_TAP_TERM_PER_KEY
#    define PERMISSIVE_HOLD_PER_KEY
#    define HOLD_ON_OTHER_KEY_PRESS_PER_KEY