.build/obj_ergodox_via/keyboards/ergodox/keymaps/via/keymap.o: \
 keyboards/ergodox/keymaps/via/keymap.c keyboards/ergodox/config.h \
 quantum/config_common.h quantum/audio/song_list.h \
 quantum/audio/musical_notes.h keyboards/ergodox/post_config.h \
 quantum/version.h

keyboards/ergodox/config.h:

quantum/config_common.h:

quantum/audio/song_list.h:

quantum/audio/musical_notes.h:

keyboards/ergodox/post_config.h:

quantum/version.h:
