EXTRAFLAGS        += -flto
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
CONSOLE_ENABLE = no
MIDI_ENABLE = no
TERMINAL_ENABLE = no
STENO_ENABLE = no

