
OLED_DRIVER_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = no
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no
RGBLIGHT_DRIVER = WS2812
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
SPLIT_KEYBOARD = yes
MOUSEKEY_ENABLE = no
