#include QMK_KEYBOARD_H

// Each layer gets a name for readability, which is then used in the keymap matrix below.
// The underscores don't mean anything - you can have a layer called STUFF or any other name.
// Layer names don't all need to be of the same length, obviously, and you can also skip them
// entirely and just use numbers.
#define _QWERTY 0
#define _NAV 1
#define _MOD 2
#define _MOD2 3

enum custom_keycodes {
  QWERTY = SAFE_RANGE,
  NAV,
};


#define KC_CPNV LT(_NAV, KC_CAPS)
#define KC_MOD LT(_MOD, KC_BSPC)
#define KC_MOD2 LT(_MOD2, KC_ENT)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [_QWERTY] = LAYOUT(
     KC_ESC  ,KC_1    ,KC_2    ,KC_3    ,KC_4   ,KC_5    ,KC_6    ,XXXXXXX,                KC_7,   KC_8     ,KC_9    ,KC_0    ,KC_MINS ,KC_EQL  ,KC_BSPC  , XXXXXXX,
     KC_TAB  ,KC_Q    ,KC_W    ,KC_E    ,KC_R   ,KC_T    ,XXXXXXX ,XXXXXXX,                KC_Y,   KC_U     ,KC_I    ,KC_O    ,KC_P    ,KC_LBRC ,KC_RBRC  , KC_BSLS, 
     KC_CPNV ,KC_A    ,KC_S    ,KC_D    ,KC_F   ,KC_G    ,XXXXXXX ,XXXXXXX,                KC_H,   KC_J     ,KC_K    ,KC_L    ,KC_SCLN ,KC_QUOT ,KC_ENT   , XXXXXXX,
     KC_LSFT ,KC_Z    ,KC_X    ,KC_C    ,KC_V   ,KC_B    ,XXXXXXX ,XXXXXXX,                KC_N,   KC_M     ,KC_COMM ,KC_DOT  ,KC_SLSH ,KC_UP   ,KC_RSFT  , XXXXXXX,
     KC_LCTL ,KC_LGUI ,KC_LALT ,KC_LALT ,KC_SPC ,KC_MOD  ,XXXXXXX ,XXXXXXX,                KC_MOD2, KC_SPC   ,KC_RSFT ,KC_RALT ,KC_LEFT ,KC_DOWN ,KC_RGHT  , XXXXXXX
  ),  
   

  [_NAV] = LAYOUT(
     S(KC_GRV),_______ ,_______ ,_______ ,A(KC_F4),_______,XXXXXXX,XXXXXXX,              _______ ,_______  ,_______ ,_______ ,_______ ,_______ ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,KC_ESC  ,KC_MS_U ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              _______ ,KC_WH_U  ,KC_HOME ,KC_END  ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,KC_MS_L ,KC_MS_D ,KC_MS_R ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_LEFT ,KC_DOWN  ,KC_UP   ,KC_RGHT , XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_WH_D ,KC_WH_L  ,KC_WH_R ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,XXXXXXX ,XXXXXXX ,KC_ACL0 ,KC_ACL1 ,KC_ACL2 ,XXXXXXX,XXXXXXX,              KC_BTN2 ,KC_BTN1  ,KC_BTN3 ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX , XXXXXXX
  ),
  
  [_MOD] = LAYOUT(
     KC_F1   ,KC_F2   ,KC_F3   ,KC_F4   ,KC_F5   ,KC_F6   ,XXXXXXX,XXXXXXX,              KC_MUTE ,KC_VOLD  ,KC_VOLU ,KC_BRID ,KC_BRIU ,XXXXXXX ,XXXXXXX ,KC_DEL,                   
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              XXXXXXX ,KC_PGUP  ,KC_HOME ,KC_END  ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX, 
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_LEFT ,KC_DOWN  ,KC_UP   ,KC_RGHT ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_PGDN ,KC_WH_L  ,KC_WH_R ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_BTN2 ,KC_BTN1  ,KC_BTN3 ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX
  ),

  [_MOD2] = LAYOUT(
     KC_F1   ,KC_F2   ,KC_F3   ,KC_F4   ,KC_F5   ,KC_F6   ,XXXXXXX,XXXXXXX,              KC_F7   ,KC_F8    ,KC_F9   ,KC_F10  ,KC_F11  ,KC_F12  ,XXXXXXX ,KC_DEL,                   
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              XXXXXXX ,KC_PGUP  ,KC_HOME ,KC_END  ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX, 
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_LEFT ,KC_DOWN  ,KC_UP   ,KC_RGHT ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_PGDN ,KC_WH_L  ,KC_WH_R ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,
     XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX,XXXXXXX,              KC_BTN2 ,KC_BTN1  ,KC_BTN3 ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX ,XXXXXXX
  ),

  
};