AUDIO_ENABLE      = no
RGBLIGHT_ENABLE   = yes
BACKLIGHT_ENABLE  = no
NO_SECRETS        = yes
BOOTMAGIC_ENABLE = lite     # Enable Bootmagic Lite
INDICATOR_LIGHTS  = no
MAKE_BOOTLOADER   = yes
RGBLIGHT_STARTUP_ANIMATION = yes
