// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

/*******************************************************************************
  88888888888 888      d8b                .d888 d8b 888               d8b
      888     888      Y8P               d88P"  Y8P 888               Y8P
      888     888                        888        888
      888     88888b.  888 .d8888b       888888 888 888  .d88b.       888 .d8888b
      888     888 "88b 888 88K           888    888 888 d8P  Y8b      888 88K
      888     888  888 888 "Y8888b.      888    888 888 88888888      888 "Y8888b.
      888     888  888 888      X88      888    888 888 Y8b.          888      X88
      888     888  888 888  88888P'      888    888 888  "Y8888       888  88888P'
                                                        888                 888
                                                        888                 888
                                                        888                 888
     .d88b.   .d88b.  88888b.   .d88b.  888d888 8888b.  888888 .d88b.   .d88888
    d88P"88b d8P  Y8b 888 "88b d8P  Y8b 888P"      "88b 888   d8P  Y8b d88" 888
    888  888 88888888 888  888 88888888 888    .d888888 888   88888888 888  888
    Y88b 888 Y8b.     888  888 Y8b.     888    888  888 Y88b. Y8b.     Y88b 888
     "Y88888  "Y8888  888  888  "Y8888  888    "Y888888  "Y888 "Y8888   "Y88888
         888
    Y8b d88P
     "Y88P"
*******************************************************************************/

#pragma once
// clang-format off

#define FOREACH_QK_KEYCODE_RANGE(XX) \
    XX(QK_BASIC,               0x0000, 0x00FF) \
    XX(QK_MODS,                0x0100, 0x1FFF) \
    XX(QK_MOD_TAP,             0x2000, 0x3FFF) \
    XX(QK_LAYER_TAP,           0x4000, 0x4FFF) \
    XX(QK_LAYER_MOD,           0x5000, 0x51FF) \
    XX(QK_TO,                  0x5200, 0x521F) \
    XX(QK_MOMENTARY,           0x5220, 0x523F) \
    XX(QK_DEF_LAYER,           0x5240, 0x525F) \
    XX(QK_TOGGLE_LAYER,        0x5260, 0x527F) \
    XX(QK_ONE_SHOT_LAYER,      0x5280, 0x529F) \
    XX(QK_ONE_SHOT_MOD,        0x52A0, 0x52BF) \
    XX(QK_LAYER_TAP_TOGGLE,    0x52C0, 0x52DF) \
    XX(QK_SWAP_HANDS,          0x5600, 0x56FF) \
    XX(QK_TAP_DANCE,           0x5700, 0x57FF) \
    XX(QK_MAGIC,               0x7000, 0x70FF) \
    XX(QK_MIDI,                0x7100, 0x71FF) \
    XX(QK_SEQUENCER,           0x7200, 0x73FF) \
    XX(QK_JOYSTICK,            0x7400, 0x743F) \
    XX(QK_PROGRAMMABLE_BUTTON, 0x7440, 0x747F) \
    XX(QK_AUDIO,               0x7480, 0x74BF) \
    XX(QK_STENO,               0x74C0, 0x74FF) \
    XX(QK_MACRO,               0x7700, 0x777F) \
    XX(QK_LIGHTING,            0x7800, 0x78FF) \
    XX(QK_QUANTUM,             0x7C00, 0x7DFF) \
    XX(QK_KB,                  0x7E00, 0x7E3F) \
    XX(QK_USER,                0x7E40, 0x7FFF) \
    XX(QK_UNICODEMAP,          0x8000, 0xBFFF) \
    XX(QK_UNICODE,             0x8000, 0xFFFF) \
    XX(QK_UNICODEMAP_PAIR,     0xC000, 0xFFFF) \
    /* End */

enum qk_keycode_ranges {
#define ENUM_OUTPUT(name, lo, hi) \
    name = lo, \
    name ## _MAX = hi,
FOREACH_QK_KEYCODE_RANGE(ENUM_OUTPUT)
#undef ENUM_OUTPUT
};

/* Actual Keycodes */
#define FOREACH_QK_KEYCODE_DEFINE(XX) \
    XX(KC_NO,                                        0x0000) \
    XX(KC_TRANSPARENT,                               0x0001) \
    XX(KC_A,                                         0x0004) \
    XX(KC_B,                                         0x0005) \
    XX(KC_C,                                         0x0006) \
    XX(KC_D,                                         0x0007) \
    XX(KC_E,                                         0x0008) \
    XX(KC_F,                                         0x0009) \
    XX(KC_G,                                         0x000A) \
    XX(KC_H,                                         0x000B) \
    XX(KC_I,                                         0x000C) \
    XX(KC_J,                                         0x000D) \
    XX(KC_K,                                         0x000E) \
    XX(KC_L,                                         0x000F) \
    XX(KC_M,                                         0x0010) \
    XX(KC_N,                                         0x0011) \
    XX(KC_O,                                         0x0012) \
    XX(KC_P,                                         0x0013) \
    XX(KC_Q,                                         0x0014) \
    XX(KC_R,                                         0x0015) \
    XX(KC_S,                                         0x0016) \
    XX(KC_T,                                         0x0017) \
    XX(KC_U,                                         0x0018) \
    XX(KC_V,                                         0x0019) \
    XX(KC_W,                                         0x001A) \
    XX(KC_X,                                         0x001B) \
    XX(KC_Y,                                         0x001C) \
    XX(KC_Z,                                         0x001D) \
    XX(KC_1,                                         0x001E) \
    XX(KC_2,                                         0x001F) \
    XX(KC_3,                                         0x0020) \
    XX(KC_4,                                         0x0021) \
    XX(KC_5,                                         0x0022) \
    XX(KC_6,                                         0x0023) \
    XX(KC_7,                                         0x0024) \
    XX(KC_8,                                         0x0025) \
    XX(KC_9,                                         0x0026) \
    XX(KC_0,                                         0x0027) \
    XX(KC_ENTER,                                     0x0028) \
    XX(KC_ESCAPE,                                    0x0029) \
    XX(KC_BACKSPACE,                                 0x002A) \
    XX(KC_TAB,                                       0x002B) \
    XX(KC_SPACE,                                     0x002C) \
    XX(KC_MINUS,                                     0x002D) \
    XX(KC_EQUAL,                                     0x002E) \
    XX(KC_LEFT_BRACKET,                              0x002F) \
    XX(KC_RIGHT_BRACKET,                             0x0030) \
    XX(KC_BACKSLASH,                                 0x0031) \
    XX(KC_NONUS_HASH,                                0x0032) \
    XX(KC_SEMICOLON,                                 0x0033) \
    XX(KC_QUOTE,                                     0x0034) \
    XX(KC_GRAVE,                                     0x0035) \
    XX(KC_COMMA,                                     0x0036) \
    XX(KC_DOT,                                       0x0037) \
    XX(KC_SLASH,                                     0x0038) \
    XX(KC_CAPS_LOCK,                                 0x0039) \
    XX(KC_F1,                                        0x003A) \
    XX(KC_F2,                                        0x003B) \
    XX(KC_F3,                                        0x003C) \
    XX(KC_F4,                                        0x003D) \
    XX(KC_F5,                                        0x003E) \
    XX(KC_F6,                                        0x003F) \
    XX(KC_F7,                                        0x0040) \
    XX(KC_F8,                                        0x0041) \
    XX(KC_F9,                                        0x0042) \
    XX(KC_F10,                                       0x0043) \
    XX(KC_F11,                                       0x0044) \
    XX(KC_F12,                                       0x0045) \
    XX(KC_PRINT_SCREEN,                              0x0046) \
    XX(KC_SCROLL_LOCK,                               0x0047) \
    XX(KC_PAUSE,                                     0x0048) \
    XX(KC_INSERT,                                    0x0049) \
    XX(KC_HOME,                                      0x004A) \
    XX(KC_PAGE_UP,                                   0x004B) \
    XX(KC_DELETE,                                    0x004C) \
    XX(KC_END,                                       0x004D) \
    XX(KC_PAGE_DOWN,                                 0x004E) \
    XX(KC_RIGHT,                                     0x004F) \
    XX(KC_LEFT,                                      0x0050) \
    XX(KC_DOWN,                                      0x0051) \
    XX(KC_UP,                                        0x0052) \
    XX(KC_NUM_LOCK,                                  0x0053) \
    XX(KC_KP_SLASH,                                  0x0054) \
    XX(KC_KP_ASTERISK,                               0x0055) \
    XX(KC_KP_MINUS,                                  0x0056) \
    XX(KC_KP_PLUS,                                   0x0057) \
    XX(KC_KP_ENTER,                                  0x0058) \
    XX(KC_KP_1,                                      0x0059) \
    XX(KC_KP_2,                                      0x005A) \
    XX(KC_KP_3,                                      0x005B) \
    XX(KC_KP_4,                                      0x005C) \
    XX(KC_KP_5,                                      0x005D) \
    XX(KC_KP_6,                                      0x005E) \
    XX(KC_KP_7,                                      0x005F) \
    XX(KC_KP_8,                                      0x0060) \
    XX(KC_KP_9,                                      0x0061) \
    XX(KC_KP_0,                                      0x0062) \
    XX(KC_KP_DOT,                                    0x0063) \
    XX(KC_NONUS_BACKSLASH,                           0x0064) \
    XX(KC_APPLICATION,                               0x0065) \
    XX(KC_KB_POWER,                                  0x0066) \
    XX(KC_KP_EQUAL,                                  0x0067) \
    XX(KC_F13,                                       0x0068) \
    XX(KC_F14,                                       0x0069) \
    XX(KC_F15,                                       0x006A) \
    XX(KC_F16,                                       0x006B) \
    XX(KC_F17,                                       0x006C) \
    XX(KC_F18,                                       0x006D) \
    XX(KC_F19,                                       0x006E) \
    XX(KC_F20,                                       0x006F) \
    XX(KC_F21,                                       0x0070) \
    XX(KC_F22,                                       0x0071) \
    XX(KC_F23,                                       0x0072) \
    XX(KC_F24,                                       0x0073) \
    XX(KC_EXECUTE,                                   0x0074) \
    XX(KC_HELP,                                      0x0075) \
    XX(KC_MENU,                                      0x0076) \
    XX(KC_SELECT,                                    0x0077) \
    XX(KC_STOP,                                      0x0078) \
    XX(KC_AGAIN,                                     0x0079) \
    XX(KC_UNDO,                                      0x007A) \
    XX(KC_CUT,                                       0x007B) \
    XX(KC_COPY,                                      0x007C) \
    XX(KC_PASTE,                                     0x007D) \
    XX(KC_FIND,                                      0x007E) \
    XX(KC_KB_MUTE,                                   0x007F) \
    XX(KC_KB_VOLUME_UP,                              0x0080) \
    XX(KC_KB_VOLUME_DOWN,                            0x0081) \
    XX(KC_LOCKING_CAPS_LOCK,                         0x0082) \
    XX(KC_LOCKING_NUM_LOCK,                          0x0083) \
    XX(KC_LOCKING_SCROLL_LOCK,                       0x0084) \
    XX(KC_KP_COMMA,                                  0x0085) \
    XX(KC_KP_EQUAL_AS400,                            0x0086) \
    XX(KC_INTERNATIONAL_1,                           0x0087) \
    XX(KC_INTERNATIONAL_2,                           0x0088) \
    XX(KC_INTERNATIONAL_3,                           0x0089) \
    XX(KC_INTERNATIONAL_4,                           0x008A) \
    XX(KC_INTERNATIONAL_5,                           0x008B) \
    XX(KC_INTERNATIONAL_6,                           0x008C) \
    XX(KC_INTERNATIONAL_7,                           0x008D) \
    XX(KC_INTERNATIONAL_8,                           0x008E) \
    XX(KC_INTERNATIONAL_9,                           0x008F) \
    XX(KC_LANGUAGE_1,                                0x0090) \
    XX(KC_LANGUAGE_2,                                0x0091) \
    XX(KC_LANGUAGE_3,                                0x0092) \
    XX(KC_LANGUAGE_4,                                0x0093) \
    XX(KC_LANGUAGE_5,                                0x0094) \
    XX(KC_LANGUAGE_6,                                0x0095) \
    XX(KC_LANGUAGE_7,                                0x0096) \
    XX(KC_LANGUAGE_8,                                0x0097) \
    XX(KC_LANGUAGE_9,                                0x0098) \
    XX(KC_ALTERNATE_ERASE,                           0x0099) \
    XX(KC_SYSTEM_REQUEST,                            0x009A) \
    XX(KC_CANCEL,                                    0x009B) \
    XX(KC_CLEAR,                                     0x009C) \
    XX(KC_PRIOR,                                     0x009D) \
    XX(KC_RETURN,                                    0x009E) \
    XX(KC_SEPARATOR,                                 0x009F) \
    XX(KC_OUT,                                       0x00A0) \
    XX(KC_OPER,                                      0x00A1) \
    XX(KC_CLEAR_AGAIN,                               0x00A2) \
    XX(KC_CRSEL,                                     0x00A3) \
    XX(KC_EXSEL,                                     0x00A4) \
    XX(KC_SYSTEM_POWER,                              0x00A5) \
    XX(KC_SYSTEM_SLEEP,                              0x00A6) \
    XX(KC_SYSTEM_WAKE,                               0x00A7) \
    XX(KC_AUDIO_MUTE,                                0x00A8) \
    XX(KC_AUDIO_VOL_UP,                              0x00A9) \
    XX(KC_AUDIO_VOL_DOWN,                            0x00AA) \
    XX(KC_MEDIA_NEXT_TRACK,                          0x00AB) \
    XX(KC_MEDIA_PREV_TRACK,                          0x00AC) \
    XX(KC_MEDIA_STOP,                                0x00AD) \
    XX(KC_MEDIA_PLAY_PAUSE,                          0x00AE) \
    XX(KC_MEDIA_SELECT,                              0x00AF) \
    XX(KC_MEDIA_EJECT,                               0x00B0) \
    XX(KC_MAIL,                                      0x00B1) \
    XX(KC_CALCULATOR,                                0x00B2) \
    XX(KC_MY_COMPUTER,                               0x00B3) \
    XX(KC_WWW_SEARCH,                                0x00B4) \
    XX(KC_WWW_HOME,                                  0x00B5) \
    XX(KC_WWW_BACK,                                  0x00B6) \
    XX(KC_WWW_FORWARD,                               0x00B7) \
    XX(KC_WWW_STOP,                                  0x00B8) \
    XX(KC_WWW_REFRESH,                               0x00B9) \
    XX(KC_WWW_FAVORITES,                             0x00BA) \
    XX(KC_MEDIA_FAST_FORWARD,                        0x00BB) \
    XX(KC_MEDIA_REWIND,                              0x00BC) \
    XX(KC_BRIGHTNESS_UP,                             0x00BD) \
    XX(KC_BRIGHTNESS_DOWN,                           0x00BE) \
    XX(KC_CONTROL_PANEL,                             0x00BF) \
    XX(KC_ASSISTANT,                                 0x00C0) \
    XX(KC_MISSION_CONTROL,                           0x00C1) \
    XX(KC_LAUNCHPAD,                                 0x00C2) \
    XX(KC_MS_UP,                                     0x00CD) \
    XX(KC_MS_DOWN,                                   0x00CE) \
    XX(KC_MS_LEFT,                                   0x00CF) \
    XX(KC_MS_RIGHT,                                  0x00D0) \
    XX(KC_MS_BTN1,                                   0x00D1) \
    XX(KC_MS_BTN2,                                   0x00D2) \
    XX(KC_MS_BTN3,                                   0x00D3) \
    XX(KC_MS_BTN4,                                   0x00D4) \
    XX(KC_MS_BTN5,                                   0x00D5) \
    XX(KC_MS_BTN6,                                   0x00D6) \
    XX(KC_MS_BTN7,                                   0x00D7) \
    XX(KC_MS_BTN8,                                   0x00D8) \
    XX(KC_MS_WH_UP,                                  0x00D9) \
    XX(KC_MS_WH_DOWN,                                0x00DA) \
    XX(KC_MS_WH_LEFT,                                0x00DB) \
    XX(KC_MS_WH_RIGHT,                               0x00DC) \
    XX(KC_MS_ACCEL0,                                 0x00DD) \
    XX(KC_MS_ACCEL1,                                 0x00DE) \
    XX(KC_MS_ACCEL2,                                 0x00DF) \
    XX(KC_LEFT_CTRL,                                 0x00E0) \
    XX(KC_LEFT_SHIFT,                                0x00E1) \
    XX(KC_LEFT_ALT,                                  0x00E2) \
    XX(KC_LEFT_GUI,                                  0x00E3) \
    XX(KC_RIGHT_CTRL,                                0x00E4) \
    XX(KC_RIGHT_SHIFT,                               0x00E5) \
    XX(KC_RIGHT_ALT,                                 0x00E6) \
    XX(KC_RIGHT_GUI,                                 0x00E7) \
    XX(QK_SWAP_HANDS_TOGGLE,                         0x56F0) \
    XX(QK_SWAP_HANDS_TAP_TOGGLE,                     0x56F1) \
    XX(QK_SWAP_HANDS_MOMENTARY_ON,                   0x56F2) \
    XX(QK_SWAP_HANDS_MOMENTARY_OFF,                  0x56F3) \
    XX(QK_SWAP_HANDS_OFF,                            0x56F4) \
    XX(QK_SWAP_HANDS_ON,                             0x56F5) \
    XX(QK_SWAP_HANDS_ONE_SHOT,                       0x56F6) \
    XX(QK_MAGIC_SWAP_CONTROL_CAPS_LOCK,              0x7000) \
    XX(QK_MAGIC_UNSWAP_CONTROL_CAPS_LOCK,            0x7001) \
    XX(QK_MAGIC_TOGGLE_CONTROL_CAPS_LOCK,            0x7002) \
    XX(QK_MAGIC_CAPS_LOCK_AS_CONTROL_OFF,            0x7003) \
    XX(QK_MAGIC_CAPS_LOCK_AS_CONTROL_ON,             0x7004) \
    XX(QK_MAGIC_SWAP_LALT_LGUI,                      0x7005) \
    XX(QK_MAGIC_UNSWAP_LALT_LGUI,                    0x7006) \
    XX(QK_MAGIC_SWAP_RALT_RGUI,                      0x7007) \
    XX(QK_MAGIC_UNSWAP_RALT_RGUI,                    0x7008) \
    XX(QK_MAGIC_GUI_ON,                              0x7009) \
    XX(QK_MAGIC_GUI_OFF,                             0x700A) \
    XX(QK_MAGIC_TOGGLE_GUI,                          0x700B) \
    XX(QK_MAGIC_SWAP_GRAVE_ESC,                      0x700C) \
    XX(QK_MAGIC_UNSWAP_GRAVE_ESC,                    0x700D) \
    XX(QK_MAGIC_SWAP_BACKSLASH_BACKSPACE,            0x700E) \
    XX(QK_MAGIC_UNSWAP_BACKSLASH_BACKSPACE,          0x700F) \
    XX(QK_MAGIC_TOGGLE_BACKSLASH_BACKSPACE,          0x7010) \
    XX(QK_MAGIC_NKRO_ON,                             0x7011) \
    XX(QK_MAGIC_NKRO_OFF,                            0x7012) \
    XX(QK_MAGIC_TOGGLE_NKRO,                         0x7013) \
    XX(QK_MAGIC_SWAP_ALT_GUI,                        0x7014) \
    XX(QK_MAGIC_UNSWAP_ALT_GUI,                      0x7015) \
    XX(QK_MAGIC_TOGGLE_ALT_GUI,                      0x7016) \
    XX(QK_MAGIC_SWAP_LCTL_LGUI,                      0x7017) \
    XX(QK_MAGIC_UNSWAP_LCTL_LGUI,                    0x7018) \
    XX(QK_MAGIC_SWAP_RCTL_RGUI,                      0x7019) \
    XX(QK_MAGIC_UNSWAP_RCTL_RGUI,                    0x701A) \
    XX(QK_MAGIC_SWAP_CTL_GUI,                        0x701B) \
    XX(QK_MAGIC_UNSWAP_CTL_GUI,                      0x701C) \
    XX(QK_MAGIC_TOGGLE_CTL_GUI,                      0x701D) \
    XX(QK_MAGIC_EE_HANDS_LEFT,                       0x701E) \
    XX(QK_MAGIC_EE_HANDS_RIGHT,                      0x701F) \
    XX(QK_MAGIC_SWAP_ESCAPE_CAPS_LOCK,               0x7020) \
    XX(QK_MAGIC_UNSWAP_ESCAPE_CAPS_LOCK,             0x7021) \
    XX(QK_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK,             0x7022) \
    XX(QK_MIDI_ON,                                   0x7100) \
    XX(QK_MIDI_OFF,                                  0x7101) \
    XX(QK_MIDI_TOGGLE,                               0x7102) \
    XX(QK_MIDI_NOTE_C_0,                             0x7103) \
    XX(QK_MIDI_NOTE_C_SHARP_0,                       0x7104) \
    XX(QK_MIDI_NOTE_D_0,                             0x7105) \
    XX(QK_MIDI_NOTE_D_SHARP_0,                       0x7106) \
    XX(QK_MIDI_NOTE_E_0,                             0x7107) \
    XX(QK_MIDI_NOTE_F_0,                             0x7108) \
    XX(QK_MIDI_NOTE_F_SHARP_0,                       0x7109) \
    XX(QK_MIDI_NOTE_G_0,                             0x710A) \
    XX(QK_MIDI_NOTE_G_SHARP_0,                       0x710B) \
    XX(QK_MIDI_NOTE_A_0,                             0x710C) \
    XX(QK_MIDI_NOTE_A_SHARP_0,                       0x710D) \
    XX(QK_MIDI_NOTE_B_0,                             0x710E) \
    XX(QK_MIDI_NOTE_C_1,                             0x710F) \
    XX(QK_MIDI_NOTE_C_SHARP_1,                       0x7110) \
    XX(QK_MIDI_NOTE_D_1,                             0x7111) \
    XX(QK_MIDI_NOTE_D_SHARP_1,                       0x7112) \
    XX(QK_MIDI_NOTE_E_1,                             0x7113) \
    XX(QK_MIDI_NOTE_F_1,                             0x7114) \
    XX(QK_MIDI_NOTE_F_SHARP_1,                       0x7115) \
    XX(QK_MIDI_NOTE_G_1,                             0x7116) \
    XX(QK_MIDI_NOTE_G_SHARP_1,                       0x7117) \
    XX(QK_MIDI_NOTE_A_1,                             0x7118) \
    XX(QK_MIDI_NOTE_A_SHARP_1,                       0x7119) \
    XX(QK_MIDI_NOTE_B_1,                             0x711A) \
    XX(QK_MIDI_NOTE_C_2,                             0x711B) \
    XX(QK_MIDI_NOTE_C_SHARP_2,                       0x711C) \
    XX(QK_MIDI_NOTE_D_2,                             0x711D) \
    XX(QK_MIDI_NOTE_D_SHARP_2,                       0x711E) \
    XX(QK_MIDI_NOTE_E_2,                             0x711F) \
    XX(QK_MIDI_NOTE_F_2,                             0x7120) \
    XX(QK_MIDI_NOTE_F_SHARP_2,                       0x7121) \
    XX(QK_MIDI_NOTE_G_2,                             0x7122) \
    XX(QK_MIDI_NOTE_G_SHARP_2,                       0x7123) \
    XX(QK_MIDI_NOTE_A_2,                             0x7124) \
    XX(QK_MIDI_NOTE_A_SHARP_2,                       0x7125) \
    XX(QK_MIDI_NOTE_B_2,                             0x7126) \
    XX(QK_MIDI_NOTE_C_3,                             0x7127) \
    XX(QK_MIDI_NOTE_C_SHARP_3,                       0x7128) \
    XX(QK_MIDI_NOTE_D_3,                             0x7129) \
    XX(QK_MIDI_NOTE_D_SHARP_3,                       0x712A) \
    XX(QK_MIDI_NOTE_E_3,                             0x712B) \
    XX(QK_MIDI_NOTE_F_3,                             0x712C) \
    XX(QK_MIDI_NOTE_F_SHARP_3,                       0x712D) \
    XX(QK_MIDI_NOTE_G_3,                             0x712E) \
    XX(QK_MIDI_NOTE_G_SHARP_3,                       0x712F) \
    XX(QK_MIDI_NOTE_A_3,                             0x7130) \
    XX(QK_MIDI_NOTE_A_SHARP_3,                       0x7131) \
    XX(QK_MIDI_NOTE_B_3,                             0x7132) \
    XX(QK_MIDI_NOTE_C_4,                             0x7133) \
    XX(QK_MIDI_NOTE_C_SHARP_4,                       0x7134) \
    XX(QK_MIDI_NOTE_D_4,                             0x7135) \
    XX(QK_MIDI_NOTE_D_SHARP_4,                       0x7136) \
    XX(QK_MIDI_NOTE_E_4,                             0x7137) \
    XX(QK_MIDI_NOTE_F_4,                             0x7138) \
    XX(QK_MIDI_NOTE_F_SHARP_4,                       0x7139) \
    XX(QK_MIDI_NOTE_G_4,                             0x713A) \
    XX(QK_MIDI_NOTE_G_SHARP_4,                       0x713B) \
    XX(QK_MIDI_NOTE_A_4,                             0x713C) \
    XX(QK_MIDI_NOTE_A_SHARP_4,                       0x713D) \
    XX(QK_MIDI_NOTE_B_4,                             0x713E) \
    XX(QK_MIDI_NOTE_C_5,                             0x713F) \
    XX(QK_MIDI_NOTE_C_SHARP_5,                       0x7140) \
    XX(QK_MIDI_NOTE_D_5,                             0x7141) \
    XX(QK_MIDI_NOTE_D_SHARP_5,                       0x7142) \
    XX(QK_MIDI_NOTE_E_5,                             0x7143) \
    XX(QK_MIDI_NOTE_F_5,                             0x7144) \
    XX(QK_MIDI_NOTE_F_SHARP_5,                       0x7145) \
    XX(QK_MIDI_NOTE_G_5,                             0x7146) \
    XX(QK_MIDI_NOTE_G_SHARP_5,                       0x7147) \
    XX(QK_MIDI_NOTE_A_5,                             0x7148) \
    XX(QK_MIDI_NOTE_A_SHARP_5,                       0x7149) \
    XX(QK_MIDI_NOTE_B_5,                             0x714A) \
    XX(QK_MIDI_OCTAVE_N2,                            0x714B) \
    XX(QK_MIDI_OCTAVE_N1,                            0x714C) \
    XX(QK_MIDI_OCTAVE_0,                             0x714D) \
    XX(QK_MIDI_OCTAVE_1,                             0x714E) \
    XX(QK_MIDI_OCTAVE_2,                             0x714F) \
    XX(QK_MIDI_OCTAVE_3,                             0x7150) \
    XX(QK_MIDI_OCTAVE_4,                             0x7151) \
    XX(QK_MIDI_OCTAVE_5,                             0x7152) \
    XX(QK_MIDI_OCTAVE_6,                             0x7153) \
    XX(QK_MIDI_OCTAVE_7,                             0x7154) \
    XX(QK_MIDI_OCTAVE_DOWN,                          0x7155) \
    XX(QK_MIDI_OCTAVE_UP,                            0x7156) \
    XX(QK_MIDI_TRANSPOSE_N6,                         0x7157) \
    XX(QK_MIDI_TRANSPOSE_N5,                         0x7158) \
    XX(QK_MIDI_TRANSPOSE_N4,                         0x7159) \
    XX(QK_MIDI_TRANSPOSE_N3,                         0x715A) \
    XX(QK_MIDI_TRANSPOSE_N2,                         0x715B) \
    XX(QK_MIDI_TRANSPOSE_N1,                         0x715C) \
    XX(QK_MIDI_TRANSPOSE_0,                          0x715D) \
    XX(QK_MIDI_TRANSPOSE_1,                          0x715E) \
    XX(QK_MIDI_TRANSPOSE_2,                          0x715F) \
    XX(QK_MIDI_TRANSPOSE_3,                          0x7160) \
    XX(QK_MIDI_TRANSPOSE_4,                          0x7161) \
    XX(QK_MIDI_TRANSPOSE_5,                          0x7162) \
    XX(QK_MIDI_TRANSPOSE_6,                          0x7163) \
    XX(QK_MIDI_TRANSPOSE_DOWN,                       0x7164) \
    XX(QK_MIDI_TRANSPOSE_UP,                         0x7165) \
    XX(QK_MIDI_VELOCITY_0,                           0x7166) \
    XX(QK_MIDI_VELOCITY_1,                           0x7167) \
    XX(QK_MIDI_VELOCITY_2,                           0x7168) \
    XX(QK_MIDI_VELOCITY_3,                           0x7169) \
    XX(QK_MIDI_VELOCITY_4,                           0x716A) \
    XX(QK_MIDI_VELOCITY_5,                           0x716B) \
    XX(QK_MIDI_VELOCITY_6,                           0x716C) \
    XX(QK_MIDI_VELOCITY_7,                           0x716D) \
    XX(QK_MIDI_VELOCITY_8,                           0x716E) \
    XX(QK_MIDI_VELOCITY_9,                           0x716F) \
    XX(QK_MIDI_VELOCITY_10,                          0x7170) \
    XX(QK_MIDI_VELOCITY_DOWN,                        0x7171) \
    XX(QK_MIDI_VELOCITY_UP,                          0x7172) \
    XX(QK_MIDI_CHANNEL_1,                            0x7173) \
    XX(QK_MIDI_CHANNEL_2,                            0x7174) \
    XX(QK_MIDI_CHANNEL_3,                            0x7175) \
    XX(QK_MIDI_CHANNEL_4,                            0x7176) \
    XX(QK_MIDI_CHANNEL_5,                            0x7177) \
    XX(QK_MIDI_CHANNEL_6,                            0x7178) \
    XX(QK_MIDI_CHANNEL_7,                            0x7179) \
    XX(QK_MIDI_CHANNEL_8,                            0x717A) \
    XX(QK_MIDI_CHANNEL_9,                            0x717B) \
    XX(QK_MIDI_CHANNEL_10,                           0x717C) \
    XX(QK_MIDI_CHANNEL_11,                           0x717D) \
    XX(QK_MIDI_CHANNEL_12,                           0x717E) \
    XX(QK_MIDI_CHANNEL_13,                           0x717F) \
    XX(QK_MIDI_CHANNEL_14,                           0x7180) \
    XX(QK_MIDI_CHANNEL_15,                           0x7181) \
    XX(QK_MIDI_CHANNEL_16,                           0x7182) \
    XX(QK_MIDI_CHANNEL_DOWN,                         0x7183) \
    XX(QK_MIDI_CHANNEL_UP,                           0x7184) \
    XX(QK_MIDI_ALL_NOTES_OFF,                        0x7185) \
    XX(QK_MIDI_SUSTAIN,                              0x7186) \
    XX(QK_MIDI_PORTAMENTO,                           0x7187) \
    XX(QK_MIDI_SOSTENUTO,                            0x7188) \
    XX(QK_MIDI_SOFT,                                 0x7189) \
    XX(QK_MIDI_LEGATO,                               0x718A) \
    XX(QK_MIDI_MODULATION,                           0x718B) \
    XX(QK_MIDI_MODULATION_SPEED_DOWN,                0x718C) \
    XX(QK_MIDI_MODULATION_SPEED_UP,                  0x718D) \
    XX(QK_MIDI_PITCH_BEND_DOWN,                      0x718E) \
    XX(QK_MIDI_PITCH_BEND_UP,                        0x718F) \
    XX(QK_SEQUENCER_ON,                              0x7200) \
    XX(QK_SEQUENCER_OFF,                             0x7201) \
    XX(QK_SEQUENCER_TOGGLE,                          0x7202) \
    XX(QK_SEQUENCER_TEMPO_DOWN,                      0x7203) \
    XX(QK_SEQUENCER_TEMPO_UP,                        0x7204) \
    XX(QK_SEQUENCER_RESOLUTION_DOWN,                 0x7205) \
    XX(QK_SEQUENCER_RESOLUTION_UP,                   0x7206) \
    XX(QK_SEQUENCER_STEPS_ALL,                       0x7207) \
    XX(QK_SEQUENCER_STEPS_CLEAR,                     0x7208) \
    XX(QK_JOYSTICK_BUTTON_0,                         0x7400) \
    XX(QK_JOYSTICK_BUTTON_1,                         0x7401) \
    XX(QK_JOYSTICK_BUTTON_2,                         0x7402) \
    XX(QK_JOYSTICK_BUTTON_3,                         0x7403) \
    XX(QK_JOYSTICK_BUTTON_4,                         0x7404) \
    XX(QK_JOYSTICK_BUTTON_5,                         0x7405) \
    XX(QK_JOYSTICK_BUTTON_6,                         0x7406) \
    XX(QK_JOYSTICK_BUTTON_7,                         0x7407) \
    XX(QK_JOYSTICK_BUTTON_8,                         0x7408) \
    XX(QK_JOYSTICK_BUTTON_9,                         0x7409) \
    XX(QK_JOYSTICK_BUTTON_10,                        0x740A) \
    XX(QK_JOYSTICK_BUTTON_11,                        0x740B) \
    XX(QK_JOYSTICK_BUTTON_12,                        0x740C) \
    XX(QK_JOYSTICK_BUTTON_13,                        0x740D) \
    XX(QK_JOYSTICK_BUTTON_14,                        0x740E) \
    XX(QK_JOYSTICK_BUTTON_15,                        0x740F) \
    XX(QK_JOYSTICK_BUTTON_16,                        0x7410) \
    XX(QK_JOYSTICK_BUTTON_17,                        0x7411) \
    XX(QK_JOYSTICK_BUTTON_18,                        0x7412) \
    XX(QK_JOYSTICK_BUTTON_19,                        0x7413) \
    XX(QK_JOYSTICK_BUTTON_20,                        0x7414) \
    XX(QK_JOYSTICK_BUTTON_21,                        0x7415) \
    XX(QK_JOYSTICK_BUTTON_22,                        0x7416) \
    XX(QK_JOYSTICK_BUTTON_23,                        0x7417) \
    XX(QK_JOYSTICK_BUTTON_24,                        0x7418) \
    XX(QK_JOYSTICK_BUTTON_25,                        0x7419) \
    XX(QK_JOYSTICK_BUTTON_26,                        0x741A) \
    XX(QK_JOYSTICK_BUTTON_27,                        0x741B) \
    XX(QK_JOYSTICK_BUTTON_28,                        0x741C) \
    XX(QK_JOYSTICK_BUTTON_29,                        0x741D) \
    XX(QK_JOYSTICK_BUTTON_30,                        0x741E) \
    XX(QK_JOYSTICK_BUTTON_31,                        0x741F) \
    XX(QK_PROGRAMMABLE_BUTTON_1,                     0x7440) \
    XX(QK_PROGRAMMABLE_BUTTON_2,                     0x7441) \
    XX(QK_PROGRAMMABLE_BUTTON_3,                     0x7442) \
    XX(QK_PROGRAMMABLE_BUTTON_4,                     0x7443) \
    XX(QK_PROGRAMMABLE_BUTTON_5,                     0x7444) \
    XX(QK_PROGRAMMABLE_BUTTON_6,                     0x7445) \
    XX(QK_PROGRAMMABLE_BUTTON_7,                     0x7446) \
    XX(QK_PROGRAMMABLE_BUTTON_8,                     0x7447) \
    XX(QK_PROGRAMMABLE_BUTTON_9,                     0x7448) \
    XX(QK_PROGRAMMABLE_BUTTON_10,                    0x7449) \
    XX(QK_PROGRAMMABLE_BUTTON_11,                    0x744A) \
    XX(QK_PROGRAMMABLE_BUTTON_12,                    0x744B) \
    XX(QK_PROGRAMMABLE_BUTTON_13,                    0x744C) \
    XX(QK_PROGRAMMABLE_BUTTON_14,                    0x744D) \
    XX(QK_PROGRAMMABLE_BUTTON_15,                    0x744E) \
    XX(QK_PROGRAMMABLE_BUTTON_16,                    0x744F) \
    XX(QK_PROGRAMMABLE_BUTTON_17,                    0x7450) \
    XX(QK_PROGRAMMABLE_BUTTON_18,                    0x7451) \
    XX(QK_PROGRAMMABLE_BUTTON_19,                    0x7452) \
    XX(QK_PROGRAMMABLE_BUTTON_20,                    0x7453) \
    XX(QK_PROGRAMMABLE_BUTTON_21,                    0x7454) \
    XX(QK_PROGRAMMABLE_BUTTON_22,                    0x7455) \
    XX(QK_PROGRAMMABLE_BUTTON_23,                    0x7456) \
    XX(QK_PROGRAMMABLE_BUTTON_24,                    0x7457) \
    XX(QK_PROGRAMMABLE_BUTTON_25,                    0x7458) \
    XX(QK_PROGRAMMABLE_BUTTON_26,                    0x7459) \
    XX(QK_PROGRAMMABLE_BUTTON_27,                    0x745A) \
    XX(QK_PROGRAMMABLE_BUTTON_28,                    0x745B) \
    XX(QK_PROGRAMMABLE_BUTTON_29,                    0x745C) \
    XX(QK_PROGRAMMABLE_BUTTON_30,                    0x745D) \
    XX(QK_PROGRAMMABLE_BUTTON_31,                    0x745E) \
    XX(QK_PROGRAMMABLE_BUTTON_32,                    0x745F) \
    XX(QK_AUDIO_ON,                                  0x7480) \
    XX(QK_AUDIO_OFF,                                 0x7481) \
    XX(QK_AUDIO_TOGGLE,                              0x7482) \
    XX(QK_AUDIO_CLICKY_TOGGLE,                       0x748A) \
    XX(QK_AUDIO_CLICKY_ON,                           0x748B) \
    XX(QK_AUDIO_CLICKY_OFF,                          0x748C) \
    XX(QK_AUDIO_CLICKY_UP,                           0x748D) \
    XX(QK_AUDIO_CLICKY_DOWN,                         0x748E) \
    XX(QK_AUDIO_CLICKY_RESET,                        0x748F) \
    XX(QK_MUSIC_ON,                                  0x7490) \
    XX(QK_MUSIC_OFF,                                 0x7491) \
    XX(QK_MUSIC_TOGGLE,                              0x7492) \
    XX(QK_MUSIC_MODE_NEXT,                           0x7493) \
    XX(QK_AUDIO_VOICE_NEXT,                          0x7494) \
    XX(QK_AUDIO_VOICE_PREVIOUS,                      0x7495) \
    XX(QK_STENO_BOLT,                                0x74F0) \
    XX(QK_STENO_GEMINI,                              0x74F1) \
    XX(QK_STENO_COMB,                                0x74F2) \
    XX(QK_STENO_COMB_MAX,                            0x74FC) \
    XX(QK_MACRO_0,                                   0x7700) \
    XX(QK_MACRO_1,                                   0x7701) \
    XX(QK_MACRO_2,                                   0x7702) \
    XX(QK_MACRO_3,                                   0x7703) \
    XX(QK_MACRO_4,                                   0x7704) \
    XX(QK_MACRO_5,                                   0x7705) \
    XX(QK_MACRO_6,                                   0x7706) \
    XX(QK_MACRO_7,                                   0x7707) \
    XX(QK_MACRO_8,                                   0x7708) \
    XX(QK_MACRO_9,                                   0x7709) \
    XX(QK_MACRO_10,                                  0x770A) \
    XX(QK_MACRO_11,                                  0x770B) \
    XX(QK_MACRO_12,                                  0x770C) \
    XX(QK_MACRO_13,                                  0x770D) \
    XX(QK_MACRO_14,                                  0x770E) \
    XX(QK_MACRO_15,                                  0x770F) \
    XX(QK_MACRO_16,                                  0x7710) \
    XX(QK_MACRO_17,                                  0x7711) \
    XX(QK_MACRO_18,                                  0x7712) \
    XX(QK_MACRO_19,                                  0x7713) \
    XX(QK_MACRO_20,                                  0x7714) \
    XX(QK_MACRO_21,                                  0x7715) \
    XX(QK_MACRO_22,                                  0x7716) \
    XX(QK_MACRO_23,                                  0x7717) \
    XX(QK_MACRO_24,                                  0x7718) \
    XX(QK_MACRO_25,                                  0x7719) \
    XX(QK_MACRO_26,                                  0x771A) \
    XX(QK_MACRO_27,                                  0x771B) \
    XX(QK_MACRO_28,                                  0x771C) \
    XX(QK_MACRO_29,                                  0x771D) \
    XX(QK_MACRO_30,                                  0x771E) \
    XX(QK_MACRO_31,                                  0x771F) \
    XX(QK_BACKLIGHT_ON,                              0x7800) \
    XX(QK_BACKLIGHT_OFF,                             0x7801) \
    XX(QK_BACKLIGHT_TOGGLE,                          0x7802) \
    XX(QK_BACKLIGHT_DOWN,                            0x7803) \
    XX(QK_BACKLIGHT_UP,                              0x7804) \
    XX(QK_BACKLIGHT_STEP,                            0x7805) \
    XX(QK_BACKLIGHT_TOGGLE_BREATHING,                0x7806) \
    XX(RGB_TOG,                                      0x7820) \
    XX(RGB_MODE_FORWARD,                             0x7821) \
    XX(RGB_MODE_REVERSE,                             0x7822) \
    XX(RGB_HUI,                                      0x7823) \
    XX(RGB_HUD,                                      0x7824) \
    XX(RGB_SAI,                                      0x7825) \
    XX(RGB_SAD,                                      0x7826) \
    XX(RGB_VAI,                                      0x7827) \
    XX(RGB_VAD,                                      0x7828) \
    XX(RGB_SPI,                                      0x7829) \
    XX(RGB_SPD,                                      0x782A) \
    XX(RGB_MODE_PLAIN,                               0x782B) \
    XX(RGB_MODE_BREATHE,                             0x782C) \
    XX(RGB_MODE_RAINBOW,                             0x782D) \
    XX(RGB_MODE_SWIRL,                               0x782E) \
    XX(RGB_MODE_SNAKE,                               0x782F) \
    XX(RGB_MODE_KNIGHT,                              0x7830) \
    XX(RGB_MODE_XMAS,                                0x7831) \
    XX(RGB_MODE_GRADIENT,                            0x7832) \
    XX(RGB_MODE_RGBTEST,                             0x7833) \
    XX(RGB_MODE_TWINKLE,                             0x7834) \
    XX(QK_BOOTLOADER,                                0x7C00) \
    XX(QK_REBOOT,                                    0x7C01) \
    XX(QK_DEBUG_TOGGLE,                              0x7C02) \
    XX(QK_CLEAR_EEPROM,                              0x7C03) \
    XX(QK_MAKE,                                      0x7C04) \
    XX(QK_AUTO_SHIFT_DOWN,                           0x7C10) \
    XX(QK_AUTO_SHIFT_UP,                             0x7C11) \
    XX(QK_AUTO_SHIFT_REPORT,                         0x7C12) \
    XX(QK_AUTO_SHIFT_ON,                             0x7C13) \
    XX(QK_AUTO_SHIFT_OFF,                            0x7C14) \
    XX(QK_AUTO_SHIFT_TOGGLE,                         0x7C15) \
    XX(QK_GRAVE_ESCAPE,                              0x7C16) \
    XX(QK_VELOCIKEY_TOGGLE,                          0x7C17) \
    XX(QK_SPACE_CADET_LEFT_CTRL_PARENTHESIS_OPEN,    0x7C18) \
    XX(QK_SPACE_CADET_RIGHT_CTRL_PARENTHESIS_CLOSE,  0x7C19) \
    XX(QK_SPACE_CADET_LEFT_SHIFT_PARENTHESIS_OPEN,   0x7C1A) \
    XX(QK_SPACE_CADET_RIGHT_SHIFT_PARENTHESIS_CLOSE, 0x7C1B) \
    XX(QK_SPACE_CADET_LEFT_ALT_PARENTHESIS_OPEN,     0x7C1C) \
    XX(QK_SPACE_CADET_RIGHT_ALT_PARENTHESIS_CLOSE,   0x7C1D) \
    XX(QK_SPACE_CADET_RIGHT_SHIFT_ENTER,             0x7C1E) \
    XX(QK_OUTPUT_AUTO,                               0x7C20) \
    XX(QK_OUTPUT_USB,                                0x7C21) \
    XX(QK_OUTPUT_BLUETOOTH,                          0x7C22) \
    XX(QK_UNICODE_MODE_NEXT,                         0x7C30) \
    XX(QK_UNICODE_MODE_PREVIOUS,                     0x7C31) \
    XX(QK_UNICODE_MODE_MACOS,                        0x7C32) \
    XX(QK_UNICODE_MODE_LINUX,                        0x7C33) \
    XX(QK_UNICODE_MODE_WINDOWS,                      0x7C34) \
    XX(QK_UNICODE_MODE_BSD,                          0x7C35) \
    XX(QK_UNICODE_MODE_WINCOMPOSE,                   0x7C36) \
    XX(QK_UNICODE_MODE_EMACS,                        0x7C37) \
    XX(QK_HAPTIC_ON,                                 0x7C40) \
    XX(QK_HAPTIC_OFF,                                0x7C41) \
    XX(QK_HAPTIC_TOGGLE,                             0x7C42) \
    XX(QK_HAPTIC_RESET,                              0x7C43) \
    XX(QK_HAPTIC_FEEDBACK_TOGGLE,                    0x7C44) \
    XX(QK_HAPTIC_BUZZ_TOGGLE,                        0x7C45) \
    XX(QK_HAPTIC_MODE_NEXT,                          0x7C46) \
    XX(QK_HAPTIC_MODE_PREVIOUS,                      0x7C47) \
    XX(QK_HAPTIC_CONTINUOUS_TOGGLE,                  0x7C48) \
    XX(QK_HAPTIC_CONTINUOUS_UP,                      0x7C49) \
    XX(QK_HAPTIC_CONTINUOUS_DOWN,                    0x7C4A) \
    XX(QK_HAPTIC_DWELL_UP,                           0x7C4B) \
    XX(QK_HAPTIC_DWELL_DOWN,                         0x7C4C) \
    XX(QK_COMBO_ON,                                  0x7C50) \
    XX(QK_COMBO_OFF,                                 0x7C51) \
    XX(QK_COMBO_TOGGLE,                              0x7C52) \
    XX(QK_DYNAMIC_MACRO_RECORD_START_1,              0x7C53) \
    XX(QK_DYNAMIC_MACRO_RECORD_START_2,              0x7C54) \
    XX(QK_DYNAMIC_MACRO_RECORD_STOP,                 0x7C55) \
    XX(QK_DYNAMIC_MACRO_PLAY_1,                      0x7C56) \
    XX(QK_DYNAMIC_MACRO_PLAY_2,                      0x7C57) \
    XX(QK_LEADER,                                    0x7C58) \
    XX(QK_LOCK,                                      0x7C59) \
    XX(QK_ONE_SHOT_ON,                               0x7C5A) \
    XX(QK_ONE_SHOT_OFF,                              0x7C5B) \
    XX(QK_ONE_SHOT_TOGGLE,                           0x7C5C) \
    XX(QK_KEY_OVERRIDE_TOGGLE,                       0x7C5D) \
    XX(QK_KEY_OVERRIDE_ON,                           0x7C5E) \
    XX(QK_KEY_OVERRIDE_OFF,                          0x7C5F) \
    XX(QK_SECURE_LOCK,                               0x7C60) \
    XX(QK_SECURE_UNLOCK,                             0x7C61) \
    XX(QK_SECURE_TOGGLE,                             0x7C62) \
    XX(QK_SECURE_REQUEST,                            0x7C63) \
    XX(QK_DYNAMIC_TAPPING_TERM_PRINT,                0x7C70) \
    XX(QK_DYNAMIC_TAPPING_TERM_UP,                   0x7C71) \
    XX(QK_DYNAMIC_TAPPING_TERM_DOWN,                 0x7C72) \
    XX(QK_CAPS_WORD_TOGGLE,                          0x7C73) \
    XX(QK_AUTOCORRECT_ON,                            0x7C74) \
    XX(QK_AUTOCORRECT_OFF,                           0x7C75) \
    XX(QK_AUTOCORRECT_TOGGLE,                        0x7C76) \
    XX(QK_TRI_LAYER_LOWER,                           0x7C77) \
    XX(QK_TRI_LAYER_UPPER,                           0x7C78) \
    XX(QK_REPEAT_KEY,                                0x7C79) \
    XX(QK_ALT_REPEAT_KEY,                            0x7C7A) \
    XX(QK_KB_0,                                      0x7E00) \
    XX(QK_KB_1,                                      0x7E01) \
    XX(QK_KB_2,                                      0x7E02) \
    XX(QK_KB_3,                                      0x7E03) \
    XX(QK_KB_4,                                      0x7E04) \
    XX(QK_KB_5,                                      0x7E05) \
    XX(QK_KB_6,                                      0x7E06) \
    XX(QK_KB_7,                                      0x7E07) \
    XX(QK_KB_8,                                      0x7E08) \
    XX(QK_KB_9,                                      0x7E09) \
    XX(QK_KB_10,                                     0x7E0A) \
    XX(QK_KB_11,                                     0x7E0B) \
    XX(QK_KB_12,                                     0x7E0C) \
    XX(QK_KB_13,                                     0x7E0D) \
    XX(QK_KB_14,                                     0x7E0E) \
    XX(QK_KB_15,                                     0x7E0F) \
    XX(QK_KB_16,                                     0x7E10) \
    XX(QK_KB_17,                                     0x7E11) \
    XX(QK_KB_18,                                     0x7E12) \
    XX(QK_KB_19,                                     0x7E13) \
    XX(QK_KB_20,                                     0x7E14) \
    XX(QK_KB_21,                                     0x7E15) \
    XX(QK_KB_22,                                     0x7E16) \
    XX(QK_KB_23,                                     0x7E17) \
    XX(QK_KB_24,                                     0x7E18) \
    XX(QK_KB_25,                                     0x7E19) \
    XX(QK_KB_26,                                     0x7E1A) \
    XX(QK_KB_27,                                     0x7E1B) \
    XX(QK_KB_28,                                     0x7E1C) \
    XX(QK_KB_29,                                     0x7E1D) \
    XX(QK_KB_30,                                     0x7E1E) \
    XX(QK_KB_31,                                     0x7E1F) \
    XX(QK_USER_0,                                    0x7E40) \
    XX(QK_USER_1,                                    0x7E41) \
    XX(QK_USER_2,                                    0x7E42) \
    XX(QK_USER_3,                                    0x7E43) \
    XX(QK_USER_4,                                    0x7E44) \
    XX(QK_USER_5,                                    0x7E45) \
    XX(QK_USER_6,                                    0x7E46) \
    XX(QK_USER_7,                                    0x7E47) \
    XX(QK_USER_8,                                    0x7E48) \
    XX(QK_USER_9,                                    0x7E49) \
    XX(QK_USER_10,                                   0x7E4A) \
    XX(QK_USER_11,                                   0x7E4B) \
    XX(QK_USER_12,                                   0x7E4C) \
    XX(QK_USER_13,                                   0x7E4D) \
    XX(QK_USER_14,                                   0x7E4E) \
    XX(QK_USER_15,                                   0x7E4F) \
    XX(QK_USER_16,                                   0x7E50) \
    XX(QK_USER_17,                                   0x7E51) \
    XX(QK_USER_18,                                   0x7E52) \
    XX(QK_USER_19,                                   0x7E53) \
    XX(QK_USER_20,                                   0x7E54) \
    XX(QK_USER_21,                                   0x7E55) \
    XX(QK_USER_22,                                   0x7E56) \
    XX(QK_USER_23,                                   0x7E57) \
    XX(QK_USER_24,                                   0x7E58) \
    XX(QK_USER_25,                                   0x7E59) \
    XX(QK_USER_26,                                   0x7E5A) \
    XX(QK_USER_27,                                   0x7E5B) \
    XX(QK_USER_28,                                   0x7E5C) \
    XX(QK_USER_29,                                   0x7E5D) \
    XX(QK_USER_30,                                   0x7E5E) \
    XX(QK_USER_31,                                   0x7E5F) \
    /* End */

/* Aliases */
#define FOREACH_QK_KEYCODE_ALIAS(XX) \
    XX(XXXXXXX,  KC_NO) \
    XX(_______,  KC_TRANSPARENT) \
    XX(KC_TRNS,  KC_TRANSPARENT) \
    XX(KC_ENT,   KC_ENTER) \
    XX(KC_ESC,   KC_ESCAPE) \
    XX(KC_BSPC,  KC_BACKSPACE) \
    XX(KC_SPC,   KC_SPACE) \
    XX(KC_MINS,  KC_MINUS) \
    XX(KC_EQL,   KC_EQUAL) \
    XX(KC_LBRC,  KC_LEFT_BRACKET) \
    XX(KC_RBRC,  KC_RIGHT_BRACKET) \
    XX(KC_BSLS,  KC_BACKSLASH) \
    XX(KC_NUHS,  KC_NONUS_HASH) \
    XX(KC_SCLN,  KC_SEMICOLON) \
    XX(KC_QUOT,  KC_QUOTE) \
    XX(KC_GRV,   KC_GRAVE) \
    XX(KC_COMM,  KC_COMMA) \
    XX(KC_SLSH,  KC_SLASH) \
    XX(KC_CAPS,  KC_CAPS_LOCK) \
    XX(KC_PSCR,  KC_PRINT_SCREEN) \
    XX(KC_SCRL,  KC_SCROLL_LOCK) \
    XX(KC_BRMD,  KC_SCROLL_LOCK) \
    XX(KC_PAUS,  KC_PAUSE) \
    XX(KC_BRK,   KC_PAUSE) \
    XX(KC_BRMU,  KC_PAUSE) \
    XX(KC_INS,   KC_INSERT) \
    XX(KC_PGUP,  KC_PAGE_UP) \
    XX(KC_DEL,   KC_DELETE) \
    XX(KC_PGDN,  KC_PAGE_DOWN) \
    XX(KC_RGHT,  KC_RIGHT) \
    XX(KC_NUM,   KC_NUM_LOCK) \
    XX(KC_PSLS,  KC_KP_SLASH) \
    XX(KC_PAST,  KC_KP_ASTERISK) \
    XX(KC_PMNS,  KC_KP_MINUS) \
    XX(KC_PPLS,  KC_KP_PLUS) \
    XX(KC_PENT,  KC_KP_ENTER) \
    XX(KC_P1,    KC_KP_1) \
    XX(KC_P2,    KC_KP_2) \
    XX(KC_P3,    KC_KP_3) \
    XX(KC_P4,    KC_KP_4) \
    XX(KC_P5,    KC_KP_5) \
    XX(KC_P6,    KC_KP_6) \
    XX(KC_P7,    KC_KP_7) \
    XX(KC_P8,    KC_KP_8) \
    XX(KC_P9,    KC_KP_9) \
    XX(KC_P0,    KC_KP_0) \
    XX(KC_PDOT,  KC_KP_DOT) \
    XX(KC_NUBS,  KC_NONUS_BACKSLASH) \
    XX(KC_APP,   KC_APPLICATION) \
    XX(KC_PEQL,  KC_KP_EQUAL) \
    XX(KC_EXEC,  KC_EXECUTE) \
    XX(KC_SLCT,  KC_SELECT) \
    XX(KC_AGIN,  KC_AGAIN) \
    XX(KC_PSTE,  KC_PASTE) \
    XX(KC_LCAP,  KC_LOCKING_CAPS_LOCK) \
    XX(KC_LNUM,  KC_LOCKING_NUM_LOCK) \
    XX(KC_LSCR,  KC_LOCKING_SCROLL_LOCK) \
    XX(KC_PCMM,  KC_KP_COMMA) \
    XX(KC_INT1,  KC_INTERNATIONAL_1) \
    XX(KC_INT2,  KC_INTERNATIONAL_2) \
    XX(KC_INT3,  KC_INTERNATIONAL_3) \
    XX(KC_INT4,  KC_INTERNATIONAL_4) \
    XX(KC_INT5,  KC_INTERNATIONAL_5) \
    XX(KC_INT6,  KC_INTERNATIONAL_6) \
    XX(KC_INT7,  KC_INTERNATIONAL_7) \
    XX(KC_INT8,  KC_INTERNATIONAL_8) \
    XX(KC_INT9,  KC_INTERNATIONAL_9) \
    XX(KC_LNG1,  KC_LANGUAGE_1) \
    XX(KC_LNG2,  KC_LANGUAGE_2) \
    XX(KC_LNG3,  KC_LANGUAGE_3) \
    XX(KC_LNG4,  KC_LANGUAGE_4) \
    XX(KC_LNG5,  KC_LANGUAGE_5) \
    XX(KC_LNG6,  KC_LANGUAGE_6) \
    XX(KC_LNG7,  KC_LANGUAGE_7) \
    XX(KC_LNG8,  KC_LANGUAGE_8) \
    XX(KC_LNG9,  KC_LANGUAGE_9) \
    XX(KC_ERAS,  KC_ALTERNATE_ERASE) \
    XX(KC_SYRQ,  KC_SYSTEM_REQUEST) \
    XX(KC_CNCL,  KC_CANCEL) \
    XX(KC_CLR,   KC_CLEAR) \
    XX(KC_PRIR,  KC_PRIOR) \
    XX(KC_RETN,  KC_RETURN) \
    XX(KC_SEPR,  KC_SEPARATOR) \
    XX(KC_CLAG,  KC_CLEAR_AGAIN) \
    XX(KC_CRSL,  KC_CRSEL) \
    XX(KC_EXSL,  KC_EXSEL) \
    XX(KC_PWR,   KC_SYSTEM_POWER) \
    XX(KC_SLEP,  KC_SYSTEM_SLEEP) \
    XX(KC_WAKE,  KC_SYSTEM_WAKE) \
    XX(KC_MUTE,  KC_AUDIO_MUTE) \
    XX(KC_VOLU,  KC_AUDIO_VOL_UP) \
    XX(KC_VOLD,  KC_AUDIO_VOL_DOWN) \
    XX(KC_MNXT,  KC_MEDIA_NEXT_TRACK) \
    XX(KC_MPRV,  KC_MEDIA_PREV_TRACK) \
    XX(KC_MSTP,  KC_MEDIA_STOP) \
    XX(KC_MPLY,  KC_MEDIA_PLAY_PAUSE) \
    XX(KC_MSEL,  KC_MEDIA_SELECT) \
    XX(KC_EJCT,  KC_MEDIA_EJECT) \
    XX(KC_CALC,  KC_CALCULATOR) \
    XX(KC_MYCM,  KC_MY_COMPUTER) \
    XX(KC_WSCH,  KC_WWW_SEARCH) \
    XX(KC_WHOM,  KC_WWW_HOME) \
    XX(KC_WBAK,  KC_WWW_BACK) \
    XX(KC_WFWD,  KC_WWW_FORWARD) \
    XX(KC_WSTP,  KC_WWW_STOP) \
    XX(KC_WREF,  KC_WWW_REFRESH) \
    XX(KC_WFAV,  KC_WWW_FAVORITES) \
    XX(KC_MFFD,  KC_MEDIA_FAST_FORWARD) \
    XX(KC_MRWD,  KC_MEDIA_REWIND) \
    XX(KC_BRIU,  KC_BRIGHTNESS_UP) \
    XX(KC_BRID,  KC_BRIGHTNESS_DOWN) \
    XX(KC_CPNL,  KC_CONTROL_PANEL) \
    XX(KC_ASST,  KC_ASSISTANT) \
    XX(KC_MCTL,  KC_MISSION_CONTROL) \
    XX(KC_LPAD,  KC_LAUNCHPAD) \
    XX(KC_MS_U,  KC_MS_UP) \
    XX(KC_MS_D,  KC_MS_DOWN) \
    XX(KC_MS_L,  KC_MS_LEFT) \
    XX(KC_MS_R,  KC_MS_RIGHT) \
    XX(KC_BTN1,  KC_MS_BTN1) \
    XX(KC_BTN2,  KC_MS_BTN2) \
    XX(KC_BTN3,  KC_MS_BTN3) \
    XX(KC_BTN4,  KC_MS_BTN4) \
    XX(KC_BTN5,  KC_MS_BTN5) \
    XX(KC_BTN6,  KC_MS_BTN6) \
    XX(KC_BTN7,  KC_MS_BTN7) \
    XX(KC_BTN8,  KC_MS_BTN8) \
    XX(KC_WH_U,  KC_MS_WH_UP) \
    XX(KC_WH_D,  KC_MS_WH_DOWN) \
    XX(KC_WH_L,  KC_MS_WH_LEFT) \
    XX(KC_WH_R,  KC_MS_WH_RIGHT) \
    XX(KC_ACL0,  KC_MS_ACCEL0) \
    XX(KC_ACL1,  KC_MS_ACCEL1) \
    XX(KC_ACL2,  KC_MS_ACCEL2) \
    XX(KC_LCTL,  KC_LEFT_CTRL) \
    XX(KC_LSFT,  KC_LEFT_SHIFT) \
    XX(KC_LALT,  KC_LEFT_ALT) \
    XX(KC_LOPT,  KC_LEFT_ALT) \
    XX(KC_LGUI,  KC_LEFT_GUI) \
    XX(KC_LCMD,  KC_LEFT_GUI) \
    XX(KC_LWIN,  KC_LEFT_GUI) \
    XX(KC_RCTL,  KC_RIGHT_CTRL) \
    XX(KC_RSFT,  KC_RIGHT_SHIFT) \
    XX(KC_RALT,  KC_RIGHT_ALT) \
    XX(KC_ROPT,  KC_RIGHT_ALT) \
    XX(KC_ALGR,  KC_RIGHT_ALT) \
    XX(KC_RGUI,  KC_RIGHT_GUI) \
    XX(KC_RCMD,  KC_RIGHT_GUI) \
    XX(KC_RWIN,  KC_RIGHT_GUI) \
    XX(SH_TOGG,  QK_SWAP_HANDS_TOGGLE) \
    XX(SH_TT,    QK_SWAP_HANDS_TAP_TOGGLE) \
    XX(SH_MON,   QK_SWAP_HANDS_MOMENTARY_ON) \
    XX(SH_MOFF,  QK_SWAP_HANDS_MOMENTARY_OFF) \
    XX(SH_OFF,   QK_SWAP_HANDS_OFF) \
    XX(SH_ON,    QK_SWAP_HANDS_ON) \
    XX(SH_OS,    QK_SWAP_HANDS_ONE_SHOT) \
    XX(CL_SWAP,  QK_MAGIC_SWAP_CONTROL_CAPS_LOCK) \
    XX(CL_NORM,  QK_MAGIC_UNSWAP_CONTROL_CAPS_LOCK) \
    XX(CL_TOGG,  QK_MAGIC_TOGGLE_CONTROL_CAPS_LOCK) \
    XX(CL_CAPS,  QK_MAGIC_CAPS_LOCK_AS_CONTROL_OFF) \
    XX(CL_CTRL,  QK_MAGIC_CAPS_LOCK_AS_CONTROL_ON) \
    XX(AG_LSWP,  QK_MAGIC_SWAP_LALT_LGUI) \
    XX(AG_LNRM,  QK_MAGIC_UNSWAP_LALT_LGUI) \
    XX(AG_RSWP,  QK_MAGIC_SWAP_RALT_RGUI) \
    XX(AG_RNRM,  QK_MAGIC_UNSWAP_RALT_RGUI) \
    XX(GU_ON,    QK_MAGIC_GUI_ON) \
    XX(GU_OFF,   QK_MAGIC_GUI_OFF) \
    XX(GU_TOGG,  QK_MAGIC_TOGGLE_GUI) \
    XX(GE_SWAP,  QK_MAGIC_SWAP_GRAVE_ESC) \
    XX(GE_NORM,  QK_MAGIC_UNSWAP_GRAVE_ESC) \
    XX(BS_SWAP,  QK_MAGIC_SWAP_BACKSLASH_BACKSPACE) \
    XX(BS_NORM,  QK_MAGIC_UNSWAP_BACKSLASH_BACKSPACE) \
    XX(BS_TOGG,  QK_MAGIC_TOGGLE_BACKSLASH_BACKSPACE) \
    XX(NK_ON,    QK_MAGIC_NKRO_ON) \
    XX(NK_OFF,   QK_MAGIC_NKRO_OFF) \
    XX(NK_TOGG,  QK_MAGIC_TOGGLE_NKRO) \
    XX(AG_SWAP,  QK_MAGIC_SWAP_ALT_GUI) \
    XX(AG_NORM,  QK_MAGIC_UNSWAP_ALT_GUI) \
    XX(AG_TOGG,  QK_MAGIC_TOGGLE_ALT_GUI) \
    XX(CG_LSWP,  QK_MAGIC_SWAP_LCTL_LGUI) \
    XX(CG_LNRM,  QK_MAGIC_UNSWAP_LCTL_LGUI) \
    XX(CG_RSWP,  QK_MAGIC_SWAP_RCTL_RGUI) \
    XX(CG_RNRM,  QK_MAGIC_UNSWAP_RCTL_RGUI) \
    XX(CG_SWAP,  QK_MAGIC_SWAP_CTL_GUI) \
    XX(CG_NORM,  QK_MAGIC_UNSWAP_CTL_GUI) \
    XX(CG_TOGG,  QK_MAGIC_TOGGLE_CTL_GUI) \
    XX(EH_LEFT,  QK_MAGIC_EE_HANDS_LEFT) \
    XX(EH_RGHT,  QK_MAGIC_EE_HANDS_RIGHT) \
    XX(EC_SWAP,  QK_MAGIC_SWAP_ESCAPE_CAPS_LOCK) \
    XX(EC_NORM,  QK_MAGIC_UNSWAP_ESCAPE_CAPS_LOCK) \
    XX(EC_TOGG,  QK_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK) \
    XX(MI_ON,    QK_MIDI_ON) \
    XX(MI_OFF,   QK_MIDI_OFF) \
    XX(MI_TOGG,  QK_MIDI_TOGGLE) \
    XX(MI_C,     QK_MIDI_NOTE_C_0) \
    XX(MI_Cs,    QK_MIDI_NOTE_C_SHARP_0) \
    XX(MI_Db,    QK_MIDI_NOTE_C_SHARP_0) \
    XX(MI_D,     QK_MIDI_NOTE_D_0) \
    XX(MI_Ds,    QK_MIDI_NOTE_D_SHARP_0) \
    XX(MI_Eb,    QK_MIDI_NOTE_D_SHARP_0) \
    XX(MI_E,     QK_MIDI_NOTE_E_0) \
    XX(MI_F,     QK_MIDI_NOTE_F_0) \
    XX(MI_Fs,    QK_MIDI_NOTE_F_SHARP_0) \
    XX(MI_Gb,    QK_MIDI_NOTE_F_SHARP_0) \
    XX(MI_G,     QK_MIDI_NOTE_G_0) \
    XX(MI_Gs,    QK_MIDI_NOTE_G_SHARP_0) \
    XX(MI_Ab,    QK_MIDI_NOTE_G_SHARP_0) \
    XX(MI_A,     QK_MIDI_NOTE_A_0) \
    XX(MI_As,    QK_MIDI_NOTE_A_SHARP_0) \
    XX(MI_Bb,    QK_MIDI_NOTE_A_SHARP_0) \
    XX(MI_B,     QK_MIDI_NOTE_B_0) \
    XX(MI_C1,    QK_MIDI_NOTE_C_1) \
    XX(MI_Cs1,   QK_MIDI_NOTE_C_SHARP_1) \
    XX(MI_Db1,   QK_MIDI_NOTE_C_SHARP_1) \
    XX(MI_D1,    QK_MIDI_NOTE_D_1) \
    XX(MI_Ds1,   QK_MIDI_NOTE_D_SHARP_1) \
    XX(MI_Eb1,   QK_MIDI_NOTE_D_SHARP_1) \
    XX(MI_E1,    QK_MIDI_NOTE_E_1) \
    XX(MI_F1,    QK_MIDI_NOTE_F_1) \
    XX(MI_Fs1,   QK_MIDI_NOTE_F_SHARP_1) \
    XX(MI_Gb1,   QK_MIDI_NOTE_F_SHARP_1) \
    XX(MI_G1,    QK_MIDI_NOTE_G_1) \
    XX(MI_Gs1,   QK_MIDI_NOTE_G_SHARP_1) \
    XX(MI_Ab1,   QK_MIDI_NOTE_G_SHARP_1) \
    XX(MI_A1,    QK_MIDI_NOTE_A_1) \
    XX(MI_As1,   QK_MIDI_NOTE_A_SHARP_1) \
    XX(MI_Bb1,   QK_MIDI_NOTE_A_SHARP_1) \
    XX(MI_B1,    QK_MIDI_NOTE_B_1) \
    XX(MI_C2,    QK_MIDI_NOTE_C_2) \
    XX(MI_Cs2,   QK_MIDI_NOTE_C_SHARP_2) \
    XX(MI_Db2,   QK_MIDI_NOTE_C_SHARP_2) \
    XX(MI_D2,    QK_MIDI_NOTE_D_2) \
    XX(MI_Ds2,   QK_MIDI_NOTE_D_SHARP_2) \
    XX(MI_Eb2,   QK_MIDI_NOTE_D_SHARP_2) \
    XX(MI_E2,    QK_MIDI_NOTE_E_2) \
    XX(MI_F2,    QK_MIDI_NOTE_F_2) \
    XX(MI_Fs2,   QK_MIDI_NOTE_F_SHARP_2) \
    XX(MI_Gb2,   QK_MIDI_NOTE_F_SHARP_2) \
    XX(MI_G2,    QK_MIDI_NOTE_G_2) \
    XX(MI_Gs2,   QK_MIDI_NOTE_G_SHARP_2) \
    XX(MI_Ab2,   QK_MIDI_NOTE_G_SHARP_2) \
    XX(MI_A2,    QK_MIDI_NOTE_A_2) \
    XX(MI_As2,   QK_MIDI_NOTE_A_SHARP_2) \
    XX(MI_Bb2,   QK_MIDI_NOTE_A_SHARP_2) \
    XX(MI_B2,    QK_MIDI_NOTE_B_2) \
    XX(MI_C3,    QK_MIDI_NOTE_C_3) \
    XX(MI_Cs3,   QK_MIDI_NOTE_C_SHARP_3) \
    XX(MI_Db3,   QK_MIDI_NOTE_C_SHARP_3) \
    XX(MI_D3,    QK_MIDI_NOTE_D_3) \
    XX(MI_Ds3,   QK_MIDI_NOTE_D_SHARP_3) \
    XX(MI_Eb3,   QK_MIDI_NOTE_D_SHARP_3) \
    XX(MI_E3,    QK_MIDI_NOTE_E_3) \
    XX(MI_F3,    QK_MIDI_NOTE_F_3) \
    XX(MI_Fs3,   QK_MIDI_NOTE_F_SHARP_3) \
    XX(MI_Gb3,   QK_MIDI_NOTE_F_SHARP_3) \
    XX(MI_G3,    QK_MIDI_NOTE_G_3) \
    XX(MI_Gs3,   QK_MIDI_NOTE_G_SHARP_3) \
    XX(MI_Ab3,   QK_MIDI_NOTE_G_SHARP_3) \
    XX(MI_A3,    QK_MIDI_NOTE_A_3) \
    XX(MI_As3,   QK_MIDI_NOTE_A_SHARP_3) \
    XX(MI_Bb3,   QK_MIDI_NOTE_A_SHARP_3) \
    XX(MI_B3,    QK_MIDI_NOTE_B_3) \
    XX(MI_C4,    QK_MIDI_NOTE_C_4) \
    XX(MI_Cs4,   QK_MIDI_NOTE_C_SHARP_4) \
    XX(MI_Db4,   QK_MIDI_NOTE_C_SHARP_4) \
    XX(MI_D4,    QK_MIDI_NOTE_D_4) \
    XX(MI_Ds4,   QK_MIDI_NOTE_D_SHARP_4) \
    XX(MI_Eb4,   QK_MIDI_NOTE_D_SHARP_4) \
    XX(MI_E4,    QK_MIDI_NOTE_E_4) \
    XX(MI_F4,    QK_MIDI_NOTE_F_4) \
    XX(MI_Fs4,   QK_MIDI_NOTE_F_SHARP_4) \
    XX(MI_Gb4,   QK_MIDI_NOTE_F_SHARP_4) \
    XX(MI_G4,    QK_MIDI_NOTE_G_4) \
    XX(MI_Gs4,   QK_MIDI_NOTE_G_SHARP_4) \
    XX(MI_Ab4,   QK_MIDI_NOTE_G_SHARP_4) \
    XX(MI_A4,    QK_MIDI_NOTE_A_4) \
    XX(MI_As4,   QK_MIDI_NOTE_A_SHARP_4) \
    XX(MI_Bb4,   QK_MIDI_NOTE_A_SHARP_4) \
    XX(MI_B4,    QK_MIDI_NOTE_B_4) \
    XX(MI_C5,    QK_MIDI_NOTE_C_5) \
    XX(MI_Cs5,   QK_MIDI_NOTE_C_SHARP_5) \
    XX(MI_Db5,   QK_MIDI_NOTE_C_SHARP_5) \
    XX(MI_D5,    QK_MIDI_NOTE_D_5) \
    XX(MI_Ds5,   QK_MIDI_NOTE_D_SHARP_5) \
    XX(MI_Eb5,   QK_MIDI_NOTE_D_SHARP_5) \
    XX(MI_E5,    QK_MIDI_NOTE_E_5) \
    XX(MI_F5,    QK_MIDI_NOTE_F_5) \
    XX(MI_Fs5,   QK_MIDI_NOTE_F_SHARP_5) \
    XX(MI_Gb5,   QK_MIDI_NOTE_F_SHARP_5) \
    XX(MI_G5,    QK_MIDI_NOTE_G_5) \
    XX(MI_Gs5,   QK_MIDI_NOTE_G_SHARP_5) \
    XX(MI_Ab5,   QK_MIDI_NOTE_G_SHARP_5) \
    XX(MI_A5,    QK_MIDI_NOTE_A_5) \
    XX(MI_As5,   QK_MIDI_NOTE_A_SHARP_5) \
    XX(MI_Bb5,   QK_MIDI_NOTE_A_SHARP_5) \
    XX(MI_B5,    QK_MIDI_NOTE_B_5) \
    XX(MI_OCN2,  QK_MIDI_OCTAVE_N2) \
    XX(MI_OCN1,  QK_MIDI_OCTAVE_N1) \
    XX(MI_OC0,   QK_MIDI_OCTAVE_0) \
    XX(MI_OC1,   QK_MIDI_OCTAVE_1) \
    XX(MI_OC2,   QK_MIDI_OCTAVE_2) \
    XX(MI_OC3,   QK_MIDI_OCTAVE_3) \
    XX(MI_OC4,   QK_MIDI_OCTAVE_4) \
    XX(MI_OC5,   QK_MIDI_OCTAVE_5) \
    XX(MI_OC6,   QK_MIDI_OCTAVE_6) \
    XX(MI_OC7,   QK_MIDI_OCTAVE_7) \
    XX(MI_OCTD,  QK_MIDI_OCTAVE_DOWN) \
    XX(MI_OCTU,  QK_MIDI_OCTAVE_UP) \
    XX(MI_TRN6,  QK_MIDI_TRANSPOSE_N6) \
    XX(MI_TRN5,  QK_MIDI_TRANSPOSE_N5) \
    XX(MI_TRN4,  QK_MIDI_TRANSPOSE_N4) \
    XX(MI_TRN3,  QK_MIDI_TRANSPOSE_N3) \
    XX(MI_TRN2,  QK_MIDI_TRANSPOSE_N2) \
    XX(MI_TRN1,  QK_MIDI_TRANSPOSE_N1) \
    XX(MI_TR0,   QK_MIDI_TRANSPOSE_0) \
    XX(MI_TR1,   QK_MIDI_TRANSPOSE_1) \
    XX(MI_TR2,   QK_MIDI_TRANSPOSE_2) \
    XX(MI_TR3,   QK_MIDI_TRANSPOSE_3) \
    XX(MI_TR4,   QK_MIDI_TRANSPOSE_4) \
    XX(MI_TR5,   QK_MIDI_TRANSPOSE_5) \
    XX(MI_TR6,   QK_MIDI_TRANSPOSE_6) \
    XX(MI_TRSD,  QK_MIDI_TRANSPOSE_DOWN) \
    XX(MI_TRSU,  QK_MIDI_TRANSPOSE_UP) \
    XX(MI_VL0,   QK_MIDI_VELOCITY_0) \
    XX(MI_VL1,   QK_MIDI_VELOCITY_1) \
    XX(MI_VL2,   QK_MIDI_VELOCITY_2) \
    XX(MI_VL3,   QK_MIDI_VELOCITY_3) \
    XX(MI_VL4,   QK_MIDI_VELOCITY_4) \
    XX(MI_VL5,   QK_MIDI_VELOCITY_5) \
    XX(MI_VL6,   QK_MIDI_VELOCITY_6) \
    XX(MI_VL7,   QK_MIDI_VELOCITY_7) \
    XX(MI_VL8,   QK_MIDI_VELOCITY_8) \
    XX(MI_VL9,   QK_MIDI_VELOCITY_9) \
    XX(MI_VL10,  QK_MIDI_VELOCITY_10) \
    XX(MI_VELD,  QK_MIDI_VELOCITY_DOWN) \
    XX(MI_VELU,  QK_MIDI_VELOCITY_UP) \
    XX(MI_CH1,   QK_MIDI_CHANNEL_1) \
    XX(MI_CH2,   QK_MIDI_CHANNEL_2) \
    XX(MI_CH3,   QK_MIDI_CHANNEL_3) \
    XX(MI_CH4,   QK_MIDI_CHANNEL_4) \
    XX(MI_CH5,   QK_MIDI_CHANNEL_5) \
    XX(MI_CH6,   QK_MIDI_CHANNEL_6) \
    XX(MI_CH7,   QK_MIDI_CHANNEL_7) \
    XX(MI_CH8,   QK_MIDI_CHANNEL_8) \
    XX(MI_CH9,   QK_MIDI_CHANNEL_9) \
    XX(MI_CH10,  QK_MIDI_CHANNEL_10) \
    XX(MI_CH11,  QK_MIDI_CHANNEL_11) \
    XX(MI_CH12,  QK_MIDI_CHANNEL_12) \
    XX(MI_CH13,  QK_MIDI_CHANNEL_13) \
    XX(MI_CH14,  QK_MIDI_CHANNEL_14) \
    XX(MI_CH15,  QK_MIDI_CHANNEL_15) \
    XX(MI_CH16,  QK_MIDI_CHANNEL_16) \
    XX(MI_CHND,  QK_MIDI_CHANNEL_DOWN) \
    XX(MI_CHNU,  QK_MIDI_CHANNEL_UP) \
    XX(MI_AOFF,  QK_MIDI_ALL_NOTES_OFF) \
    XX(MI_SUST,  QK_MIDI_SUSTAIN) \
    XX(MI_PORT,  QK_MIDI_PORTAMENTO) \
    XX(MI_SOST,  QK_MIDI_SOSTENUTO) \
    XX(MI_SOFT,  QK_MIDI_SOFT) \
    XX(MI_LEG,   QK_MIDI_LEGATO) \
    XX(MI_MOD,   QK_MIDI_MODULATION) \
    XX(MI_MODD,  QK_MIDI_MODULATION_SPEED_DOWN) \
    XX(MI_MODU,  QK_MIDI_MODULATION_SPEED_UP) \
    XX(MI_BNDD,  QK_MIDI_PITCH_BEND_DOWN) \
    XX(MI_BNDU,  QK_MIDI_PITCH_BEND_UP) \
    XX(SQ_ON,    QK_SEQUENCER_ON) \
    XX(SQ_OFF,   QK_SEQUENCER_OFF) \
    XX(SQ_TOGG,  QK_SEQUENCER_TOGGLE) \
    XX(SQ_TMPD,  QK_SEQUENCER_TEMPO_DOWN) \
    XX(SQ_TMPU,  QK_SEQUENCER_TEMPO_UP) \
    XX(SQ_RESD,  QK_SEQUENCER_RESOLUTION_DOWN) \
    XX(SQ_RESU,  QK_SEQUENCER_RESOLUTION_UP) \
    XX(SQ_SALL,  QK_SEQUENCER_STEPS_ALL) \
    XX(SQ_SCLR,  QK_SEQUENCER_STEPS_CLEAR) \
    XX(JS_0,     QK_JOYSTICK_BUTTON_0) \
    XX(JS_1,     QK_JOYSTICK_BUTTON_1) \
    XX(JS_2,     QK_JOYSTICK_BUTTON_2) \
    XX(JS_3,     QK_JOYSTICK_BUTTON_3) \
    XX(JS_4,     QK_JOYSTICK_BUTTON_4) \
    XX(JS_5,     QK_JOYSTICK_BUTTON_5) \
    XX(JS_6,     QK_JOYSTICK_BUTTON_6) \
    XX(JS_7,     QK_JOYSTICK_BUTTON_7) \
    XX(JS_8,     QK_JOYSTICK_BUTTON_8) \
    XX(JS_9,     QK_JOYSTICK_BUTTON_9) \
    XX(JS_10,    QK_JOYSTICK_BUTTON_10) \
    XX(JS_11,    QK_JOYSTICK_BUTTON_11) \
    XX(JS_12,    QK_JOYSTICK_BUTTON_12) \
    XX(JS_13,    QK_JOYSTICK_BUTTON_13) \
    XX(JS_14,    QK_JOYSTICK_BUTTON_14) \
    XX(JS_15,    QK_JOYSTICK_BUTTON_15) \
    XX(JS_16,    QK_JOYSTICK_BUTTON_16) \
    XX(JS_17,    QK_JOYSTICK_BUTTON_17) \
    XX(JS_18,    QK_JOYSTICK_BUTTON_18) \
    XX(JS_19,    QK_JOYSTICK_BUTTON_19) \
    XX(JS_20,    QK_JOYSTICK_BUTTON_20) \
    XX(JS_21,    QK_JOYSTICK_BUTTON_21) \
    XX(JS_22,    QK_JOYSTICK_BUTTON_22) \
    XX(JS_23,    QK_JOYSTICK_BUTTON_23) \
    XX(JS_24,    QK_JOYSTICK_BUTTON_24) \
    XX(JS_25,    QK_JOYSTICK_BUTTON_25) \
    XX(JS_26,    QK_JOYSTICK_BUTTON_26) \
    XX(JS_27,    QK_JOYSTICK_BUTTON_27) \
    XX(JS_28,    QK_JOYSTICK_BUTTON_28) \
    XX(JS_29,    QK_JOYSTICK_BUTTON_29) \
    XX(JS_30,    QK_JOYSTICK_BUTTON_30) \
    XX(JS_31,    QK_JOYSTICK_BUTTON_31) \
    XX(PB_1,     QK_PROGRAMMABLE_BUTTON_1) \
    XX(PB_2,     QK_PROGRAMMABLE_BUTTON_2) \
    XX(PB_3,     QK_PROGRAMMABLE_BUTTON_3) \
    XX(PB_4,     QK_PROGRAMMABLE_BUTTON_4) \
    XX(PB_5,     QK_PROGRAMMABLE_BUTTON_5) \
    XX(PB_6,     QK_PROGRAMMABLE_BUTTON_6) \
    XX(PB_7,     QK_PROGRAMMABLE_BUTTON_7) \
    XX(PB_8,     QK_PROGRAMMABLE_BUTTON_8) \
    XX(PB_9,     QK_PROGRAMMABLE_BUTTON_9) \
    XX(PB_10,    QK_PROGRAMMABLE_BUTTON_10) \
    XX(PB_11,    QK_PROGRAMMABLE_BUTTON_11) \
    XX(PB_12,    QK_PROGRAMMABLE_BUTTON_12) \
    XX(PB_13,    QK_PROGRAMMABLE_BUTTON_13) \
    XX(PB_14,    QK_PROGRAMMABLE_BUTTON_14) \
    XX(PB_15,    QK_PROGRAMMABLE_BUTTON_15) \
    XX(PB_16,    QK_PROGRAMMABLE_BUTTON_16) \
    XX(PB_17,    QK_PROGRAMMABLE_BUTTON_17) \
    XX(PB_18,    QK_PROGRAMMABLE_BUTTON_18) \
    XX(PB_19,    QK_PROGRAMMABLE_BUTTON_19) \
    XX(PB_20,    QK_PROGRAMMABLE_BUTTON_20) \
    XX(PB_21,    QK_PROGRAMMABLE_BUTTON_21) \
    XX(PB_22,    QK_PROGRAMMABLE_BUTTON_22) \
    XX(PB_23,    QK_PROGRAMMABLE_BUTTON_23) \
    XX(PB_24,    QK_PROGRAMMABLE_BUTTON_24) \
    XX(PB_25,    QK_PROGRAMMABLE_BUTTON_25) \
    XX(PB_26,    QK_PROGRAMMABLE_BUTTON_26) \
    XX(PB_27,    QK_PROGRAMMABLE_BUTTON_27) \
    XX(PB_28,    QK_PROGRAMMABLE_BUTTON_28) \
    XX(PB_29,    QK_PROGRAMMABLE_BUTTON_29) \
    XX(PB_30,    QK_PROGRAMMABLE_BUTTON_30) \
    XX(PB_31,    QK_PROGRAMMABLE_BUTTON_31) \
    XX(PB_32,    QK_PROGRAMMABLE_BUTTON_32) \
    XX(AU_ON,    QK_AUDIO_ON) \
    XX(AU_OFF,   QK_AUDIO_OFF) \
    XX(AU_TOGG,  QK_AUDIO_TOGGLE) \
    XX(CK_TOGG,  QK_AUDIO_CLICKY_TOGGLE) \
    XX(CK_ON,    QK_AUDIO_CLICKY_ON) \
    XX(CK_OFF,   QK_AUDIO_CLICKY_OFF) \
    XX(CK_UP,    QK_AUDIO_CLICKY_UP) \
    XX(CK_DOWN,  QK_AUDIO_CLICKY_DOWN) \
    XX(CK_RST,   QK_AUDIO_CLICKY_RESET) \
    XX(MU_ON,    QK_MUSIC_ON) \
    XX(MU_OFF,   QK_MUSIC_OFF) \
    XX(MU_TOGG,  QK_MUSIC_TOGGLE) \
    XX(MU_NEXT,  QK_MUSIC_MODE_NEXT) \
    XX(AU_NEXT,  QK_AUDIO_VOICE_NEXT) \
    XX(AU_PREV,  QK_AUDIO_VOICE_PREVIOUS) \
    XX(MC_0,     QK_MACRO_0) \
    XX(MC_1,     QK_MACRO_1) \
    XX(MC_2,     QK_MACRO_2) \
    XX(MC_3,     QK_MACRO_3) \
    XX(MC_4,     QK_MACRO_4) \
    XX(MC_5,     QK_MACRO_5) \
    XX(MC_6,     QK_MACRO_6) \
    XX(MC_7,     QK_MACRO_7) \
    XX(MC_8,     QK_MACRO_8) \
    XX(MC_9,     QK_MACRO_9) \
    XX(MC_10,    QK_MACRO_10) \
    XX(MC_11,    QK_MACRO_11) \
    XX(MC_12,    QK_MACRO_12) \
    XX(MC_13,    QK_MACRO_13) \
    XX(MC_14,    QK_MACRO_14) \
    XX(MC_15,    QK_MACRO_15) \
    XX(MC_16,    QK_MACRO_16) \
    XX(MC_17,    QK_MACRO_17) \
    XX(MC_18,    QK_MACRO_18) \
    XX(MC_19,    QK_MACRO_19) \
    XX(MC_20,    QK_MACRO_20) \
    XX(MC_21,    QK_MACRO_21) \
    XX(MC_22,    QK_MACRO_22) \
    XX(MC_23,    QK_MACRO_23) \
    XX(MC_24,    QK_MACRO_24) \
    XX(MC_25,    QK_MACRO_25) \
    XX(MC_26,    QK_MACRO_26) \
    XX(MC_27,    QK_MACRO_27) \
    XX(MC_28,    QK_MACRO_28) \
    XX(MC_29,    QK_MACRO_29) \
    XX(MC_30,    QK_MACRO_30) \
    XX(MC_31,    QK_MACRO_31) \
    XX(BL_ON,    QK_BACKLIGHT_ON) \
    XX(BL_OFF,   QK_BACKLIGHT_OFF) \
    XX(BL_TOGG,  QK_BACKLIGHT_TOGGLE) \
    XX(BL_DOWN,  QK_BACKLIGHT_DOWN) \
    XX(BL_UP,    QK_BACKLIGHT_UP) \
    XX(BL_STEP,  QK_BACKLIGHT_STEP) \
    XX(BL_BRTG,  QK_BACKLIGHT_TOGGLE_BREATHING) \
    XX(RGB_MOD,  RGB_MODE_FORWARD) \
    XX(RGB_RMOD, RGB_MODE_REVERSE) \
    XX(RGB_M_P,  RGB_MODE_PLAIN) \
    XX(RGB_M_B,  RGB_MODE_BREATHE) \
    XX(RGB_M_R,  RGB_MODE_RAINBOW) \
    XX(RGB_M_SW, RGB_MODE_SWIRL) \
    XX(RGB_M_SN, RGB_MODE_SNAKE) \
    XX(RGB_M_K,  RGB_MODE_KNIGHT) \
    XX(RGB_M_X,  RGB_MODE_XMAS) \
    XX(RGB_M_G,  RGB_MODE_GRADIENT) \
    XX(RGB_M_T,  RGB_MODE_RGBTEST) \
    XX(RGB_M_TW, RGB_MODE_TWINKLE) \
    XX(QK_BOOT,  QK_BOOTLOADER) \
    XX(QK_RBT,   QK_REBOOT) \
    XX(DB_TOGG,  QK_DEBUG_TOGGLE) \
    XX(EE_CLR,   QK_CLEAR_EEPROM) \
    XX(AS_DOWN,  QK_AUTO_SHIFT_DOWN) \
    XX(AS_UP,    QK_AUTO_SHIFT_UP) \
    XX(AS_RPT,   QK_AUTO_SHIFT_REPORT) \
    XX(AS_ON,    QK_AUTO_SHIFT_ON) \
    XX(AS_OFF,   QK_AUTO_SHIFT_OFF) \
    XX(AS_TOGG,  QK_AUTO_SHIFT_TOGGLE) \
    XX(QK_GESC,  QK_GRAVE_ESCAPE) \
    XX(VK_TOGG,  QK_VELOCIKEY_TOGGLE) \
    XX(SC_LCPO,  QK_SPACE_CADET_LEFT_CTRL_PARENTHESIS_OPEN) \
    XX(SC_RCPC,  QK_SPACE_CADET_RIGHT_CTRL_PARENTHESIS_CLOSE) \
    XX(SC_LSPO,  QK_SPACE_CADET_LEFT_SHIFT_PARENTHESIS_OPEN) \
    XX(SC_RSPC,  QK_SPACE_CADET_RIGHT_SHIFT_PARENTHESIS_CLOSE) \
    XX(SC_LAPO,  QK_SPACE_CADET_LEFT_ALT_PARENTHESIS_OPEN) \
    XX(SC_RAPC,  QK_SPACE_CADET_RIGHT_ALT_PARENTHESIS_CLOSE) \
    XX(SC_SENT,  QK_SPACE_CADET_RIGHT_SHIFT_ENTER) \
    XX(OU_AUTO,  QK_OUTPUT_AUTO) \
    XX(OU_USB,   QK_OUTPUT_USB) \
    XX(OU_BT,    QK_OUTPUT_BLUETOOTH) \
    XX(UC_NEXT,  QK_UNICODE_MODE_NEXT) \
    XX(UC_PREV,  QK_UNICODE_MODE_PREVIOUS) \
    XX(UC_MAC,   QK_UNICODE_MODE_MACOS) \
    XX(UC_LINX,  QK_UNICODE_MODE_LINUX) \
    XX(UC_WIN,   QK_UNICODE_MODE_WINDOWS) \
    XX(UC_BSD,   QK_UNICODE_MODE_BSD) \
    XX(UC_WINC,  QK_UNICODE_MODE_WINCOMPOSE) \
    XX(UC_EMAC,  QK_UNICODE_MODE_EMACS) \
    XX(HF_ON,    QK_HAPTIC_ON) \
    XX(HF_OFF,   QK_HAPTIC_OFF) \
    XX(HF_TOGG,  QK_HAPTIC_TOGGLE) \
    XX(HF_RST,   QK_HAPTIC_RESET) \
    XX(HF_FDBK,  QK_HAPTIC_FEEDBACK_TOGGLE) \
    XX(HF_BUZZ,  QK_HAPTIC_BUZZ_TOGGLE) \
    XX(HF_NEXT,  QK_HAPTIC_MODE_NEXT) \
    XX(HF_PREV,  QK_HAPTIC_MODE_PREVIOUS) \
    XX(HF_CONT,  QK_HAPTIC_CONTINUOUS_TOGGLE) \
    XX(HF_CONU,  QK_HAPTIC_CONTINUOUS_UP) \
    XX(HF_COND,  QK_HAPTIC_CONTINUOUS_DOWN) \
    XX(HF_DWLU,  QK_HAPTIC_DWELL_UP) \
    XX(HF_DWLD,  QK_HAPTIC_DWELL_DOWN) \
    XX(CM_ON,    QK_COMBO_ON) \
    XX(CM_OFF,   QK_COMBO_OFF) \
    XX(CM_TOGG,  QK_COMBO_TOGGLE) \
    XX(DM_REC1,  QK_DYNAMIC_MACRO_RECORD_START_1) \
    XX(DM_REC2,  QK_DYNAMIC_MACRO_RECORD_START_2) \
    XX(DM_RSTP,  QK_DYNAMIC_MACRO_RECORD_STOP) \
    XX(DM_PLY1,  QK_DYNAMIC_MACRO_PLAY_1) \
    XX(DM_PLY2,  QK_DYNAMIC_MACRO_PLAY_2) \
    XX(QK_LEAD,  QK_LEADER) \
    XX(OS_ON,    QK_ONE_SHOT_ON) \
    XX(OS_OFF,   QK_ONE_SHOT_OFF) \
    XX(OS_TOGG,  QK_ONE_SHOT_TOGGLE) \
    XX(KO_TOGG,  QK_KEY_OVERRIDE_TOGGLE) \
    XX(KO_ON,    QK_KEY_OVERRIDE_ON) \
    XX(KO_OFF,   QK_KEY_OVERRIDE_OFF) \
    XX(SE_LOCK,  QK_SECURE_LOCK) \
    XX(SE_UNLK,  QK_SECURE_UNLOCK) \
    XX(SE_TOGG,  QK_SECURE_TOGGLE) \
    XX(SE_REQ,   QK_SECURE_REQUEST) \
    XX(DT_PRNT,  QK_DYNAMIC_TAPPING_TERM_PRINT) \
    XX(DT_UP,    QK_DYNAMIC_TAPPING_TERM_UP) \
    XX(DT_DOWN,  QK_DYNAMIC_TAPPING_TERM_DOWN) \
    XX(CW_TOGG,  QK_CAPS_WORD_TOGGLE) \
    XX(AC_ON,    QK_AUTOCORRECT_ON) \
    XX(AC_OFF,   QK_AUTOCORRECT_OFF) \
    XX(AC_TOGG,  QK_AUTOCORRECT_TOGGLE) \
    XX(TL_LOWR,  QK_TRI_LAYER_LOWER) \
    XX(TL_UPPR,  QK_TRI_LAYER_UPPER) \
    XX(QK_REP,   QK_REPEAT_KEY) \
    XX(QK_AREP,  QK_ALT_REPEAT_KEY) \
    /* End */

/* Combination */
#define FOREACH_QK_KEYCODE(XX) \
    FOREACH_QK_KEYCODE_DEFINE(XX) \
    FOREACH_QK_KEYCODE_ALIAS(XX)

enum qk_keycode_defines {
#define ENUM_OUTPUT(name, value) \
  name = value,
FOREACH_QK_KEYCODE(ENUM_OUTPUT)
#undef ENUM_OUTPUT
};

// Range Helpers
#define IS_QK_BASIC(code) ((code) >= QK_BASIC && (code) <= QK_BASIC_MAX)
#define IS_QK_MODS(code) ((code) >= QK_MODS && (code) <= QK_MODS_MAX)
#define IS_QK_MOD_TAP(code) ((code) >= QK_MOD_TAP && (code) <= QK_MOD_TAP_MAX)
#define IS_QK_LAYER_TAP(code) ((code) >= QK_LAYER_TAP && (code) <= QK_LAYER_TAP_MAX)
#define IS_QK_LAYER_MOD(code) ((code) >= QK_LAYER_MOD && (code) <= QK_LAYER_MOD_MAX)
#define IS_QK_TO(code) ((code) >= QK_TO && (code) <= QK_TO_MAX)
#define IS_QK_MOMENTARY(code) ((code) >= QK_MOMENTARY && (code) <= QK_MOMENTARY_MAX)
#define IS_QK_DEF_LAYER(code) ((code) >= QK_DEF_LAYER && (code) <= QK_DEF_LAYER_MAX)
#define IS_QK_TOGGLE_LAYER(code) ((code) >= QK_TOGGLE_LAYER && (code) <= QK_TOGGLE_LAYER_MAX)
#define IS_QK_ONE_SHOT_LAYER(code) ((code) >= QK_ONE_SHOT_LAYER && (code) <= QK_ONE_SHOT_LAYER_MAX)
#define IS_QK_ONE_SHOT_MOD(code) ((code) >= QK_ONE_SHOT_MOD && (code) <= QK_ONE_SHOT_MOD_MAX)
#define IS_QK_LAYER_TAP_TOGGLE(code) ((code) >= QK_LAYER_TAP_TOGGLE && (code) <= QK_LAYER_TAP_TOGGLE_MAX)
#define IS_QK_SWAP_HANDS(code) ((code) >= QK_SWAP_HANDS && (code) <= QK_SWAP_HANDS_MAX)
#define IS_QK_TAP_DANCE(code) ((code) >= QK_TAP_DANCE && (code) <= QK_TAP_DANCE_MAX)
#define IS_QK_MAGIC(code) ((code) >= QK_MAGIC && (code) <= QK_MAGIC_MAX)
#define IS_QK_MIDI(code) ((code) >= QK_MIDI && (code) <= QK_MIDI_MAX)
#define IS_QK_SEQUENCER(code) ((code) >= QK_SEQUENCER && (code) <= QK_SEQUENCER_MAX)
#define IS_QK_JOYSTICK(code) ((code) >= QK_JOYSTICK && (code) <= QK_JOYSTICK_MAX)
#define IS_QK_PROGRAMMABLE_BUTTON(code) ((code) >= QK_PROGRAMMABLE_BUTTON && (code) <= QK_PROGRAMMABLE_BUTTON_MAX)
#define IS_QK_AUDIO(code) ((code) >= QK_AUDIO && (code) <= QK_AUDIO_MAX)
#define IS_QK_STENO(code) ((code) >= QK_STENO && (code) <= QK_STENO_MAX)
#define IS_QK_MACRO(code) ((code) >= QK_MACRO && (code) <= QK_MACRO_MAX)
#define IS_QK_LIGHTING(code) ((code) >= QK_LIGHTING && (code) <= QK_LIGHTING_MAX)
#define IS_QK_QUANTUM(code) ((code) >= QK_QUANTUM && (code) <= QK_QUANTUM_MAX)
#define IS_QK_KB(code) ((code) >= QK_KB && (code) <= QK_KB_MAX)
#define IS_QK_USER(code) ((code) >= QK_USER && (code) <= QK_USER_MAX)
#define IS_QK_UNICODEMAP(code) ((code) >= QK_UNICODEMAP && (code) <= QK_UNICODEMAP_MAX)
#define IS_QK_UNICODE(code) ((code) >= QK_UNICODE && (code) <= QK_UNICODE_MAX)
#define IS_QK_UNICODEMAP_PAIR(code) ((code) >= QK_UNICODEMAP_PAIR && (code) <= QK_UNICODEMAP_PAIR_MAX)

// Group Helpers
#define IS_INTERNAL_KEYCODE(code) ((code) >= KC_NO && (code) <= KC_TRANSPARENT)
#define IS_BASIC_KEYCODE(code) ((code) >= KC_A && (code) <= KC_EXSEL)
#define IS_SYSTEM_KEYCODE(code) ((code) >= KC_SYSTEM_POWER && (code) <= KC_SYSTEM_WAKE)
#define IS_CONSUMER_KEYCODE(code) ((code) >= KC_AUDIO_MUTE && (code) <= KC_LAUNCHPAD)
#define IS_MOUSE_KEYCODE(code) ((code) >= KC_MS_UP && (code) <= KC_MS_ACCEL2)
#define IS_MODIFIER_KEYCODE(code) ((code) >= KC_LEFT_CTRL && (code) <= KC_RIGHT_GUI)
#define IS_SWAP_HANDS_KEYCODE(code) ((code) >= QK_SWAP_HANDS_TOGGLE && (code) <= QK_SWAP_HANDS_ONE_SHOT)
#define IS_MAGIC_KEYCODE(code) ((code) >= QK_MAGIC_SWAP_CONTROL_CAPS_LOCK && (code) <= QK_MAGIC_TOGGLE_ESCAPE_CAPS_LOCK)
#define IS_MIDI_KEYCODE(code) ((code) >= QK_MIDI_ON && (code) <= QK_MIDI_PITCH_BEND_UP)
#define IS_SEQUENCER_KEYCODE(code) ((code) >= QK_SEQUENCER_ON && (code) <= QK_SEQUENCER_STEPS_CLEAR)
#define IS_JOYSTICK_KEYCODE(code) ((code) >= QK_JOYSTICK_BUTTON_0 && (code) <= QK_JOYSTICK_BUTTON_31)
#define IS_PROGRAMMABLE_BUTTON_KEYCODE(code) ((code) >= QK_PROGRAMMABLE_BUTTON_1 && (code) <= QK_PROGRAMMABLE_BUTTON_32)
#define IS_AUDIO_KEYCODE(code) ((code) >= QK_AUDIO_ON && (code) <= QK_AUDIO_VOICE_PREVIOUS)
#define IS_STENO_KEYCODE(code) ((code) >= QK_STENO_BOLT && (code) <= QK_STENO_COMB_MAX)
#define IS_MACRO_KEYCODE(code) ((code) >= QK_MACRO_0 && (code) <= QK_MACRO_31)
#define IS_BACKLIGHT_KEYCODE(code) ((code) >= QK_BACKLIGHT_ON && (code) <= QK_BACKLIGHT_TOGGLE_BREATHING)
#define IS_RGB_KEYCODE(code) ((code) >= RGB_TOG && (code) <= RGB_MODE_TWINKLE)
#define IS_QUANTUM_KEYCODE(code) ((code) >= QK_BOOTLOADER && (code) <= QK_ALT_REPEAT_KEY)
#define IS_KB_KEYCODE(code) ((code) >= QK_KB_0 && (code) <= QK_KB_31)
#define IS_USER_KEYCODE(code) ((code) >= QK_USER_0 && (code) <= QK_USER_31)
