#pragma once

#include "quantum.h"
#include "webusb.h"

#ifndef WEBUSB_ENABLE
#    error "WebUSB needs to be enabled, please enable it!"
#endif

#ifndef DYNAMIC_KEYMAP_ENABLE
#    error "Dynamic Keymaps are not enabled. It must be enabled"
#endif

// enum Oryx_Status_code {
//     PLACEHOLDER = WEBUSB_STATUS_SAFE_RANGE,
// }

enum Oryx_Command_Code {
    ORYX_GET_LAYER = WEBUSB_CMD_SAFE_RANGE,
    ORYX_CMD_LIVE_TRAINING,
    ORYX_CMD_LIVE_UPDATE_GET_KEYCODE,
    ORYX_CMD_LIVE_UPDATE_SET_KEYCODE,
    ORYX_CMD_LIVE_UPDATE_KEYMAP_RESET,
    ORYX_CMD_LIVE_UPDATE_GET_BUFFER,
    ORYX_CMD_LIVE_UPDATE_SET_BUFFER,
    ORYX_CMD_LIVE_UPDATE_GET_LAYER_COUNT,
    ORYX_CMD_LIVE_UPDATE_GET_MACRO_COUNT,
    ORYX_CMD_LIVE_UPDATE_GET_MACRO_BUFFER_SIZE,
    ORYX_CMD_LIVE_UPDATE_GET_MACRO_BUFFER,
    ORYX_CMD_LIVE_UPDATE_SET_MACRO_BUFFER,
    ORYX_CMD_LIVE_UPDATE_MACRO_RESET,
    ORYX_CMD_LIVE_UPDATE_EEPROM_RESET,
    ORYX_CMD_LIVE_UPDATE_KEYBOARD_RESET,

};

enum Oryx_Event_Code {
    ORYX_EVT_LAYER = WEBUSB_EVT_SAFE_RANGE,
    ORYX_EVT_LIVE_TRAINING,
    ORYX_EVT_LIVE_UPDATE_GET_KEYCODE,
    ORYX_EVT_LIVE_UPDATE_SET_KEYCODE,
    ORYX_EVT_LIVE_UPDATE_KEYMAP_RESET,
    ORYX_EVT_LIVE_UPDATE_GET_BUFFER,
    ORYX_EVT_LIVE_UPDATE_SET_BUFFER,
    ORYX_EVT_LIVE_UPDATE_GET_LAYER_COUNT,
    ORYX_EVT_LIVE_UPDATE_GET_MACRO_COUNT,
    ORYX_EVT_LIVE_UPDATE_GET_MACRO_BUFFER_SIZE,
    ORYX_EVT_LIVE_UPDATE_GET_MACRO_BUFFER,
    ORYX_EVT_LIVE_UPDATE_SET_MACRO_BUFFER,
    ORYX_EVT_LIVE_UPDATE_MACRO_RESET,
    ORYX_EVT_LIVE_UPDATE_EEPROM_RESET,
    ORYX_EVT_LIVE_UPDATE_KEYBOARD_RESET,
    ORYX_EVT_KEYDOWN,
    ORYX_EVT_KEYUP,
};



extern bool oryx_state_live_training_enabled;

bool webusb_receive_oryx(uint8_t *data, uint8_t length);
void oryx_layer_event(void);
bool is_oryx_live_training_enabled(void);

void keyboard_pre_init_oryx(void);
