#pragma once

// clang-format off

// Deprecated Quantum keycodes
#define RGB_TOG QK_UNDERGLOW_TOGGLE
#define RGB_MOD QK_UNDERGLOW_MODE_NEXT
#define RGB_MODE_FORWARD QK_UNDERGLOW_MODE_NEXT
#define RGB_RMOD QK_UNDERGLOW_MODE_PREVIOUS
#define RGB_MODE_REVERSE QK_UNDERGLOW_MODE_PREVIOUS
#define RGB_HUI QK_UNDERGLOW_HUE_UP
#define RGB_HUD QK_UNDERGLOW_HUE_DOWN
#define RGB_SAI QK_UNDERGLOW_SATURATION_UP
#define RGB_SAD QK_UNDERGLOW_SATURATION_DOWN
#define RGB_VAI QK_UNDERGLOW_VALUE_UP
#define RGB_VAD QK_UNDERGLOW_VALUE_DOWN
#define RGB_SPI QK_UNDERGLOW_SPEED_UP
#define RGB_SPD QK_UNDERGLOW_SPEED_DOWN

#define KC_MS_UP QK_MOUSE_CURSOR_UP
#define KC_MS_U QK_MOUSE_CURSOR_UP
#define KC_MS_DOWN QK_MOUSE_CURSOR_DOWN
#define KC_MS_D QK_MOUSE_CURSOR_DOWN
#define KC_MS_LEFT QK_MOUSE_CURSOR_LEFT
#define KC_MS_L QK_MOUSE_CURSOR_LEFT
#define KC_MS_RIGHT QK_MOUSE_CURSOR_RIGHT
#define KC_MS_R QK_MOUSE_CURSOR_RIGHT
#define KC_MS_BTN1 QK_MOUSE_BUTTON_1
#define KC_BTN1 QK_MOUSE_BUTTON_1
#define KC_MS_BTN2 QK_MOUSE_BUTTON_2
#define KC_BTN2 QK_MOUSE_BUTTON_2
#define KC_MS_BTN3 QK_MOUSE_BUTTON_3
#define KC_BTN3 QK_MOUSE_BUTTON_3
#define KC_MS_BTN4 QK_MOUSE_BUTTON_4
#define KC_BTN4 QK_MOUSE_BUTTON_4
#define KC_MS_BTN5 QK_MOUSE_BUTTON_5
#define KC_BTN5 QK_MOUSE_BUTTON_5
#define KC_MS_BTN6 QK_MOUSE_BUTTON_6
#define KC_BTN6 QK_MOUSE_BUTTON_6
#define KC_MS_BTN7 QK_MOUSE_BUTTON_7
#define KC_BTN7 QK_MOUSE_BUTTON_7
#define KC_MS_BTN8 QK_MOUSE_BUTTON_8
#define KC_BTN8 QK_MOUSE_BUTTON_8
#define KC_MS_WH_UP QK_MOUSE_WHEEL_UP
#define KC_WH_U QK_MOUSE_WHEEL_UP
#define KC_MS_WH_DOWN QK_MOUSE_WHEEL_DOWN
#define KC_WH_D QK_MOUSE_WHEEL_DOWN
#define KC_MS_WH_LEFT QK_MOUSE_WHEEL_LEFT
#define KC_WH_L QK_MOUSE_WHEEL_LEFT
#define KC_MS_WH_RIGHT QK_MOUSE_WHEEL_RIGHT
#define KC_WH_R QK_MOUSE_WHEEL_RIGHT
#define KC_MS_ACCEL0 QK_MOUSE_ACCELERATION_0
#define KC_ACL0 QK_MOUSE_ACCELERATION_0
#define KC_MS_ACCEL1 QK_MOUSE_ACCELERATION_1
#define KC_ACL1 QK_MOUSE_ACCELERATION_1
#define KC_MS_ACCEL2 QK_MOUSE_ACCELERATION_2
#define KC_ACL2 QK_MOUSE_ACCELERATION_2

#define QK_OUTPUT_AUTO OU_AUTO

#define C_S_T(kc) LCS_T(kc)
