#ifndef SEND_STRING_KEYCODES
#define SEND_STRING_KEYCODES

#define X_NO              00
#define X_ROLL_OVER       01
#define X_POST_FAIL       02
#define X_UNDEFINED       03
#define X_A               04
#define X_B               05
#define X_C               06
#define X_D               07
#define X_E               08
#define X_F               09
#define X_G               0A
#define X_H               0B
#define X_I               0C
#define X_J               0D
#define X_K               0E
#define X_L               0F
#define X_M               10
#define X_N               11
#define X_O               12
#define X_P               13
#define X_Q               14
#define X_R               15
#define X_S               16                          
#define X_T               17                        
#define X_U               18                        
#define X_V               19                        
#define X_W               1A                        
#define X_X               1B                        
#define X_Y               1C                        
#define X_Z               1D                          
#define X_1               1E                          
#define X_2               1F                          
#define X_3               20
#define X_4               21                        
#define X_5               22                        
#define X_6               23                        
#define X_7               24                        
#define X_8               25                        
#define X_9               26                        
#define X_0               27                        
#define X_ENTER           28                            
#define X_ESCAPE          29                             
#define X_BSPACE          2A                             
#define X_TAB             2B                          
#define X_SPACE           2C                            
#define X_MINUS           2D                            
#define X_EQUAL           2E                            
#define X_LBRACKET        2F                               
#define X_RBRACKET        30
#define X_BSLASH          31                                     
#define X_NONUS_HASH      32                                      
#define X_SCOLON          33                                     
#define X_QUOTE           34                                      
#define X_GRAVE           35                                      
#define X_COMMA           36                                     
#define X_DOT             37                                
#define X_SLASH           38                                     
#define X_CAPSLOCK        39                               
#define X_F1              3A                         
#define X_F2              3B                         
#define X_F3              3C                         
#define X_F4              3D                         
#define X_F5              3E                         
#define X_F6              3F                         
#define X_F7              40                                       
#define X_F8              41                          
#define X_F9              42                         
#define X_F10             43                          
#define X_F11             44                          
#define X_F12             45                          
#define X_PSCREEN         46                              
#define X_SCROLLLOCK      47                                 
#define X_PAUSE           48                            
#define X_INSERT          49                             
#define X_HOME            4A                           
#define X_PGUP            4B                           
#define X_DELETE          4C                             
#define X_END             4D                          
#define X_PGDOWN          4E                             
#define X_RIGHT           4F                            
#define X_LEFT            50                                      
#define X_DOWN            51                           
#define X_UP              52                         
#define X_NUMLOCK         53                              
#define X_KP_SLASH        54                               
#define X_KP_ASTERISK     55                                  
#define X_KP_MINUS        56                               
#define X_KP_PLUS         57                              
#define X_KP_ENTER        58                               
#define X_KP_1            59                           
#define X_KP_2            5A                           
#define X_KP_3            5B                           
#define X_KP_4            5C                           
#define X_KP_5            5D                           
#define X_KP_6            5E                           
#define X_KP_7            5F                           
#define X_KP_8            60                                      
#define X_KP_9            61                           
#define X_KP_0            62                           
#define X_KP_DOT          63                             
#define X_NONUS_BSLASH    64                                      
#define X_APPLICATION     65                                  
#define X_POWER           66                            
#define X_KP_EQUAL        67                               
#define X_F13             68                          
#define X_F14             69                          
#define X_F15             6A                          
#define X_F16             6B                          
#define X_F17             6C                          
#define X_F18             6D                          
#define X_F19             6E                          
#define X_F20             6F                          
#define X_F21             70                                      
#define X_F22             71                          
#define X_F23             72                          
#define X_F24             73                          
#define X_EXECUTE         74                              
#define X_HELP            75                           
#define X_MENU            76                           
#define X_SELECT          77                             
#define X_STOP            78                           
#define X_AGAIN           79                            
#define X_UNDO            7A                           
#define X_CUT             7B                          
#define X_COPY            7C                           
#define X_PASTE           7D                            
#define X_FIND            7E                           
#define X__MUTE           7F                            
#define X__VOLUP          80                                       
#define X__VOLDOWN        81                               
#define X_LOCKING_CAPS    82                                     
#define X_LOCKING_NUM     83                                      
#define X_LOCKING_SCROLL  84                                     
#define X_KP_COMMA        85                               
#define X_KP_EQUAL_AS400  86                                       
#define X_INT1            87                           
#define X_INT2            88                           
#define X_INT3            89                           
#define X_INT4            8A                           
#define X_INT5            8B                           
#define X_INT6            8C                           
#define X_INT7            8D                           
#define X_INT8            8E                           
#define X_INT9            8F                           
#define X_LANG1           90                                    
#define X_LANG2           91                            
#define X_LANG3           92                            
#define X_LANG4           93                            
#define X_LANG5           94                            
#define X_LANG6           95                            
#define X_LANG7           96                            
#define X_LANG8           97                            
#define X_LANG9           98                            

/* Modifiers */
#define X_LCTRL           e0
#define X_LSHIFT          e1                              
#define X_LALT            e2                           
#define X_LGUI            e3                           
#define X_RCTRL           e4                            
#define X_RSHIFT          e5                             
#define X_RALT            e6                           
#define X_RGUI            e7                           

#endif