#define FEE_PAGE_SIZE 0x800
#define FEE_PAGE_COUNT 8
#define FEE_MCU_FLASH_SIZE 128

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define DYNAMIC_KEYMAP_MACRO_EEPROM_SIZE 4608
#define DYNAMIC_KEYMAP_MACRO_COUNT 64

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2
