enum layer_type {
    CH_CUSTOM_WINDOWS,
    CH_CUSTOM_MACOS,
    CH_ZOOM_WINDOWS,
    CH_ZOOM_MACOS,
    CH_TEAMS_WINDOWS,
    CH_TEAMS_MACOS,
    CH_SKYPE_WINDOWS,
    CH_SKYPE_MACOS,
    CH_GOOGLE_MEET_WINDOWS,
    CH_GOOGLE_MEET_MACOS,
};