CONSOLE_ENABLE = no
COMMAND_ENABME = no
OLED_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = no
AUTO_SHIFT_ENABLE= no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
NKRO_ENABLE = yes
SRC+=oco9oco.c
MOUSEKEY_ENABLE = yes
# RGB 라이트 기능 활성화
RGBLIGHT_ENABLE = no
