BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE            = yes      # Mouse keys
EXTRAKEY_ENABLE            = yes      # Audio control and System control
CONSOLE_ENABLE             = yes      # Console for debug
COMMAND_ENABLE             = no       # Commands for debug and configuration
NKRO_ENABLE                = yes      # USB Nkey Rollover
UNICODE_ENABLE             = yes      # Unicode
OLED_ENABLE                = yes
OLED_DRIVER                = SSD1306  # Enables the use of OLED displays
ENCODER_ENABLE             = yes      # Enables the use of one or more encoders

RGBLIGHT_ENABLE            = no       # Enable keyboard RGB underglow
RGBLIGHT_STARTUP_ANIMATION = yes
RGB_MATRIX_ENABLE          = yes
TAP_DANCE_ENABLE           = yes
KEY_LOCK_ENABLE            = no
WPM_ENABLE                 = yes
SWAP_HANDS_ENABLE          = yes
LTO_ENABLE                 = no
CTPC                       = yes
