// #pragma once

// #ifdef RGB_MATRIX_ENABLE
// #define MY_RGB_MATRIX_NONE 0
// #define MY_RGB_MATRIX_SOLID_COLOR 1
// #define MY_RGB_MATRIX_ALPHAS_MODS 2
// #define MY_RGB_MATRIX_GRADIENT_UP_DOWN 3
// #define MY_RGB_MATRIX_GRADIENT_LEFT_RIGHT 4
// #define MY_RGB_MATRIX_BREATHING 5
// #define MY_RGB_MATRIX_BAND_SAT 6
// #define MY_RGB_MATRIX_BAND_VAL 7
// #define MY_RGB_MATRIX_BAND_PINWHEEL_SAT 8
// #define MY_RGB_MATRIX_BAND_PINWHEEL_VAL 9
// #define MY_RGB_MATRIX_BAND_SPIRAL_SAT 10
// #define MY_RGB_MATRIX_BAND_SPIRAL_VAL 11
// #define MY_RGB_MATRIX_CYCLE_ALL 12
// #define MY_RGB_MATRIX_CYCLE_LEFT_RIGHT 13
// #define MY_RGB_MATRIX_CYCLE_UP_DOWN 14
// #define MY_RGB_MATRIX_CYCLE_OUT_IN 15
// #define MY_RGB_MATRIX_CYCLE_OUT_IN_DUAL 16
// #define MY_RGB_MATRIX_RAINBOW_MOVING_CHEVRON 17
// #define MY_RGB_MATRIX_CYCLE_PINWHEEL 18
// #define MY_RGB_MATRIX_CYCLE_SPIRAL 19
// #define MY_RGB_MATRIX_DUAL_BEACON 20
// #define MY_RGB_MATRIX_RAINBOW_BEACON 21
// #define MY_RGB_MATRIX_RAINBOW_PINWHEELS 22
// #define MY_RGB_MATRIX_RAINDROPS 23
// #define MY_RGB_MATRIX_JELLYBEAN_RAINDROPS 24
// #define MY_RGB_MATRIX_HUE_BREATHING 25
// #define MY_RGB_MATRIX_HUE_PENDULUM 26
// #define MY_RGB_MATRIX_HUE_WAVE 27
// #if defined(RGB_MATRIX_FRAMEBUFFER_EFFECTS)
// #    define MY_RGB_MATRIX_TYPING_HEATMAP 28
// #    define MY_RGB_MATRIX_DIGITAL_RAIN 29
// #endif
// #if defined(RGB_MATRIX_KEYPRESSES) || defined(RGB_MATRIX_KEYRELEASES)
// #    define MY_RGB_MATRIX_SOLID_REACTIVE_SIMPLE 30
// #    define MY_RGB_MATRIX_SOLID_REACTIVE 31
// #    define MY_RGB_MATRIX_SOLID_REACTIVE_WIDE 32
// #    define MY_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE 33
// #    define MY_RGB_MATRIX_SOLID_REACTIVE_CROSS 34
// #    define MY_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS 35
// #    define MY_RGB_MATRIX_SOLID_REACTIVE_NEXUS 36
// #    define MY_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS 37
// #    define MY_RGB_MATRIX_SPLASH 38
// #    define MY_RGB_MATRIX_MULTISPLASH 39
// #    define MY_RGB_MATRIX_SOLID_SPLASH 40
// #    define MY_RGB_MATRIX_SOLID_MULTISPLASH 41
// #endif
// #define MY_RGB_MATRIX_EFFECT_MAX 42

// #endif // RGB_MATRIX_ENABLE