# Automatically flash the board with the default layout
flash:
    qmk flash -kb dasbob -km nilscc

make layout="nilscc":
    make -C ../.. dasbob:{{ layout }}

flash-left:
    qmk flash -kb dasbob -km nilscc -bl uf2-split-left

flash-right:
    qmk flash -kb dasbob -km nilscc -bl uf2-split-left
