#define COMBO_COUNT 4
#define COMBO_TERM 200

//#define UNICODE_SELECTED_MODES UC_WINC

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYER_BLINK

#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_TWINKLE

