#pragma once
#define MK_3_SPEED 
#define TAPPING_TERM 20
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_TIME_TO_MAX 10
#define MOUSEKEY_WHEEL_MAX_SPEED 4
#define MOUSEKEY_WHEEL_TIME_TO_MAX 10
#define MK_C_OFFSET_0 4
#define MK_C_INTERVAL_0 30
#define MK_C_OFFSET_1 8
#define MK_C_INTERVAL_1 20
#define MK_C_OFFSET_2 16
#define MK_C_INTERVAL_2 20
#define MK_C_OFFSET_UNMOD 3
#define MK_C_INTERVAL_UNMOD 25
