VIA_ENABLE = no
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes
BOOTMAGIC_ENABLE = yes # Enable Bootmagic Lite

TD_LSFT_CAPSLOCK_ENABLE = yes
IDLE_TIMEOUT_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
ENCODER_DEFAULTACTIONS_ENABLE = yes
ALTTAB_SCROLL_ENABLE = yes

INVERT_NUMLOCK_INDICATOR = yes

RGB_MATRIX_FUNCTION_COLOR = RGB_GOLD # See https://docs.qmk.fm/#/feature_rgb_matrix?id=colors

RGB_MATRIX_KEYPRESSES = yes
RGB_MATRIX_FRAMEBUFFER_EFFECTS = yes
