
#pragma once

// SPLIT
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_DRIVER UARTD0
#define SPLIT_HAND_PIN_LOW_IS_LEFT

#define MASTER_RIGHT
#define POINTING_DEVICE_RIGHT


// TRACKBALL (PMW3389 SPI) 
#define SPLIT_POINTING_ENABLE
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP4
#define PMW33XX_CS_PIN GP5
#define PMW33XX_LIFTOFF_DISTANCE 0x03
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X

// DPI Trackball
#define CHARYBDIS_MINIMUM_DEFAULT_DPI        600
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP    200
#define CHARYBDIS_MINIMUM_SNIPING_DPI        400
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP    100
#define CHARYBDIS_DRAGSCROLL_DPI             200
#define CHARYBDIS_DRAGSCROLL_BUFFER_SIZE     6

// I2C OLED
#define I2C_DRIVER I2CD1
#define I2C1_SCL_PIN GP15
#define I2C1_SDA_PIN GP14

// OLED
#define OLED_DISPLAY_128X32
#define OLED_TIMEOUT 20000
#define OLED_BRIGHTNESS 128  // 0 - 255, default 255
