BOOTMAGIC_ENABLE  = no
COMMAND_ENABLE    = yes
CONSOLE_ENABLE    = no
EXTRAKEY_ENABLE   = yes
MOUSEKEY_ENABLE   = yes
NKRO_ENABLE       = yes
TAP_DANCE_ENABLE  = yes
UNICODEMAP_ENABLE = no

BACKLIGHT_ENABLE = yes
RGBLIGHT_ENABLE  = yes
