
#define WEAR_LEVELING_LOGICAL_SIZE 32768
#define WEAR_LEVELING_BACKING_SIZE 65536

#define DYNAMIC_KEYMAP_LAYER_COUNT 16

#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define COMBO_TERM_PER_COMBO
#define COMBO_SHOULD_TRIGGER
#define COMBO_STRICT_TIMER

#define COMBO_TERM 20
#define TAPPING_TERM 150

#define ONESHOT_TIMEOUT 1500
#define CAPS_WORD_IDLE_TIMEOUT 1500

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_MOVE_DELTA 8
#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_TIME_TO_MAX 10

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 30
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0

#define SPLIT_TRANSACTION_IDS_USER USER_SYNC_A
