#ifndef KEYBOARDS_CHIBIOS_TEST_CHIBIOS_TEST_H_
#define KEYBOARDS_CHIBIOS_TEST_CHIBIOS_TEST_H_

#include "quantum.h"

#define LAYOUT(k00) {{ k00 }}

#endif /* KEYBOARDS_CHIBIOS_TEST_CHIBIOS_TEST_H_ */
