// Copyright 2022 w0rk4h011c (@w0rk4h011c)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// #define SERIAL_USART_FULL_DUPLEX //FULL DUPULEX OPTION
// #define SERIAL_USART_TX_PIN GP0 //FULL DUPULEX OPTION
// #define SERIAL_USART_RX_PIN GP1 //FULL DUPULEX OPTION

#define SERIAL_USART_TX_PIN GP1 //HARF DUPULEX OPTION
#define SERIAL_PIO_USE_PIO1     //HARF DUPULEX OPTION
#define SPLIT_USB_TIMEOUT 5000
#define SPLIT_USB_TIMEOUT_POLL 25
