<<<<<<< HEAD
BOOTMAGIC_ENABLE = lite
=======
BOOTMAGIC_ENABLE = full
>>>>>>> b3b7d0e2675c0a60bd4c60251cb74794f997d8bb
MOUSEKEY_ENABLE = no
STENO_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = yes
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE = yes
LEADER_ENABLE = yes

# save me space!
EXTRAFLAGS += -flto
