#pragma once

#define MATRIX_ROWS 4
#define MATRIX_COLS 12

#define MATRIX_ROW_PINS \
    { GP26, GP27, GP28, GP29 }

#define ROWS_PER_COL \
    { 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3 }

#define AMUX_MAX_COLS_COUNT 12

#define AMUX_SEL_PINS \
    { GP4, GP5, GP6, GP7, GP8, GP9 }
#define AMUX_COL_CHANNELS \
    { 0, 1, 2, 3, 4, 5, 56, 57, 58, 59, 60, 61 }

#define DEFAULT_ACTUATION_MODE 0
#define DEFAULT_MODE_0_ACTUATION_LEVEL 350
#define DEFAULT_MODE_0_RELEASE_LEVEL 400
#define DEFAULT_MODE_1_INITIAL_DEADZONE_OFFSET DEFAULT_MODE_0_ACTUATION_LEVEL
#define DEFAULT_MODE_1_ACTUATION_OFFSET 70
#define DEFAULT_MODE_1_RELEASE_OFFSET 70
#define DEFAULT_EXTREMUM 1023
#define NOISE_CEILING_THRESHOLD 50
#define BOTTOMING_CALIBRATION_THRESHOLD 50
#define DEFAULT_NOISE_CEILING_SAMPLING_COUNT 30
#define DEFAULT_BOTTOMING_READING 0
#define DEFAULT_CALIBRATION_STARTER true

#define EECONFIG_KB_DATA_SIZE 256

#define DEBUG_MATRIX_SCAN_RATE

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
