#pragma once

//#define ROTATIONAL_TRANSFORM_ANGLE 5

/* PMW3360 Settings */
#define PMW33XX_LIFTOFF_DISTANCE 0x02
#define PMW33XX_CS_PIN GP5
#define SPI_SCK_PIN GP2
#define SPI_MISO_PIN GP4
#define SPI_MOSI_PIN GP3
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
