#pragma once
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_WPM_ENABLE
#define SPLIT_OLED_ENABLE
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define OLED_BRIGHTNESS 10
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT
