CAPS_WORD_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = no
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
RAW_ENABLE = yes
SPLIT_KEYBOARD = yes
WPM_ENABLE = yes

#Debug - yes to enable
CONSOLE_ENABLE = no

#Space saving
# EXTRAFLAGS += -flto
