// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define NO_ACTION_ONESHOT

#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL

#define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0x1
