USER_NAME := twaauk
RGBLIGHT_ENABLE = no
COMBO_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes

VIA_ENABLE = yes
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
TAPPING_TERM_PER_KEY = yes
TAP_DANCE_ENABLE = yes
