USER_NAME := twaauk
#RGBLIGHT_ENABLE = yes
COMBO_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes

VIA_ENABLE = yes
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
USE_MINIZONE_EXTENSION = yes
TAPPING_TERM_PER_KEY = yes
