VIA_ENABLE = yes

BOOTMAGIC_ENABLE = lite

# save space
LTO_ENABLE = yes
LEADER_ENABLE = no
FAUXCLICKY_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
KEY_LOCK_ENABLE = no
TERMINAL_ENABLE = no
MOUSEKEY_ENABLE = no
