CONSOLE_ENABLE	       = no
MOUSEKEY_ENABLE        = yes
ENCODER_ENABLE         = yes
RGBLIGHT_ENABLE        = yes
OLED_DRIVER_ENABLE     = yes
OLED_ANIMATIONS_ENABLE = yes
THUMBSTICK_ENABLE  	   = yes
COMBO_ENABLE           = no
