CONSOLE_ENABLE	       = no
MOUSEKEY_ENABLE        = yes
ENCODER_ENABLE         = yes
RGBLIGHT_ENABLE        = no
OLED_DRIVER_ENABLE     = yes
OLED_ANIMATIONS_ENABLE = no
THUMBSTICK_ENABLE  	   = yes
COMBO_ENABLE           = yes
