MCU 				= atmega32u4
F_CPU 				= 16000000
ARCH				= AVR8
F_USB 				= $(F_CPU)
OPT_DEFS 			+= -DINTERRUPT_CONTROL_ENDPOINT
BOOTLOADER 			= caterina

EXTRAKEY_ENABLE 	= yes
NKRO_ENABLE 		= yes
CONSOLE_ENABLE		= yes
COMMAND_ENABLE		= yes
