
#ifdef REDUCE_RGB

// Matrix RGB

#ifdef RGB_MATRIX_KEYPRESSES
#undef RGB_MATRIX_KEYPRESSES
#endif

#ifdef RGB_MATRIX_FRAMEBUFFER_EFFECTS
#undef RGB_MATRIX_FRAMEBUFFER_EFFECTS
#endif

#ifdef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
#endif

#ifdef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#endif

#ifdef ENABLE_RGB_MATRIX_BREATHING
#undef ENABLE_RGB_MATRIX_BREATHING
#endif

#ifdef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_VAL
#endif

#ifdef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#endif

#ifdef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef ENABLE_RGB_MATRIX_CYCLE_ALL
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#endif

#ifdef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#endif

#ifdef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#endif

#ifdef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#endif

#ifdef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#endif

#ifdef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#endif

#ifdef ENABLE_RGB_MATRIX_RAINDROPS
#undef ENABLE_RGB_MATRIX_RAINDROPS
#endif

#ifdef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#endif

#ifdef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef ENABLE_RGB_MATRIX_HUE_BREATHING
#endif

#ifdef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
#endif

#ifdef ENABLE_RGB_MATRIX_HUE_WAVE
#undef ENABLE_RGB_MATRIX_HUE_WAVE
#endif

#ifdef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#endif

#ifdef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#endif

#ifdef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#endif

#ifdef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#endif

#ifdef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#endif

#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#endif

#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#endif

#ifdef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#endif

#endif

