SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
COMMAND_ENABLE   = no  # Commands for debug and configuration
RGBLIGHT_ENABLE = yes
MIDI_ENABLE = no

ifndef MAKEFILE_INCLUDED
	include ../../../Makefile
endif
