// Copyright 2024 Andrew Kannan
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64
