BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = yes        # Console for debug
COMMAND_ENABLE = yes        # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = yes          # Audio output
UNICODE_ENABLE = no         # Enable Unicode characters
UNICODEMAP_ENABLE = yes     # Enable Unicode Map
CUSTOM_MATRIX = yes
ENCODER_ENABLE = yes
DIP_SWITCH_ENABLE = yes
RGB_MATRIX_ENABLE = no      # Do not enable RGB_MATRIX_ENABLE together with RGBLIGHT_ENABLE
