#pragma once

// default but used in macros
#undef TAPPING_TERM
#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD

// Recommended for heavy chording.
#define QMK_KEYS_PER_SCAN 4
#define USB_POLLING_INTERVAL_MS 1

#define COMBO_TERM 50
#define COMBO_VARIABLE_LEN
#define COMBO_COUNT 5
#define COMBO_MUST_TAP_PER_COMBO

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define MACRO_TIMER 5
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 6
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 64
