BACKLIGHT_ENABLE   = no
BOOTMAGIC_ENABLE   = no
COMMAND_ENABLE     = yes
CONSOLE_ENABLE     = yes
EXTRAKEY_ENABLE    = yes
MOUSEKEY_ENABLE    = yes
NKRO_ENABLE        = yes
RGBLIGHT_ENABLE    = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE   = yes
UNICODEMAP_ENABLE  = no

USER_NAME = konstantin
