LTO_ENABLE = yes
BOOTMAGIC_ENABLE = yes

USER_NAME := chrisgve
APPLE_FN_ENABLE = yes
NKRO_ENABLE = yes
SRC += chrisgve.c
#REDUCE_RGB = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
SHIFT_ENABLE = yes

