#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_6x4(KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, KC_P7, KC_P8, KC_P9, KC_PPLS, KC_P4, KC_P5, KC_P6, KC_BSPC, KC_P1, KC_P2, KC_P3, KC_PENT, KC_P0, KC_UP, KC_PDOT, MO(1), KC_LEFT, KC_DOWN, KC_RGHT, KC_NO),
	[1] = LAYOUT_ortho_6x4(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_V, KC_NO, KC_NO, KC_J, KC_NO, KC_P, KC_NO, KC_NO, KC_C, KC_NO, KC_PENT, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO)
};
