BOARD = GENERIC_RP_RP2040
CONVERT_TO = kb2040

EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
RGB_MATRIX_SUPPORTED = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
