MCU = RP2040
BOOTLOADER = rp2040

EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
RGB_MATRIX_SUPPORTED = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor
AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
