AUTO_SHIFT_ENABLE = no
COMMAND_ENABLE = no
SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = yes
EXTRAKEY_ENABLE = no
KEY_LOCK_ENABLE = yes
LEADER_ENABLE = yes

UNICODE_ENABLE    = yes
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
