BOOTMAGIC_ENABLE   = yes
TAP_DANCE_ENABLE   = no
COMMAND_ENABLE     = no  # Commands for debug and configuration
CONSOLE_ENABLE 	   = yes
SPACE_CADET_ENABLE = no
KEY_LOCK_ENABLE    = yes
MOUSEKEY_ENABLE    = yes
EXTRAKEY_ENABLE	   = yes
LEADER_ENABLE	   = yes

UNICODE_ENABLE     = no
UNICODEMAP_ENABLE  = no
RGB_MATRIX_ENABLE  = no
RGBLIGHT_ENABLE    = no
