GRAVE_ESC_ENABLE		= no
SPACE_CADET_ENABLE 	= no

MOUSEKEY_ENABLE			= yes
EXTRAKEY_ENABLE			= yes
CAPS_WORD_ENABLE		= yes
KEY_OVERRIDE_ENABLE	= yes
COMBO_ENABLE				= yes
TAP_DANCE_ENABLE		= yes
TRI_LAYER_ENABLE 		= yes

POINTING_DEVICE_ENABLE = yes