MOUSEKEY_ENABLE        = yes                # Enable Mouse keys
RGBLIGHT_ENABLE        = no                 # Disable WS2812 RGB underlight.
VIA_ENABLE             = no                 # Disable VIA
TAP_DANCE_ENABLE       = yes                # Enable Tap Dance
OLED_ENABLE            = no                 # Disable OLED
OLED_DRIVER            = SSD1306            # Designate SSD1306as OLED driver
LTO_ENABLE             = yes			    # Enable Link Time Optimization
POINTING_DEVICE_ENABLE = yes				# Enable pointing device
POINTING_DEVICE_DRIVER = pimoroni_trackball # Designate Pimoroni Trackball as pointing device
UNICODE_ENABLE         = yes 			    # Enable unicode characters
