PRINTF_PATH = $(LIB_PATH)/printf

VPATH += $(PRINTF_PATH)
SRC += $(PRINTF_PATH)/printf.c
QUANTUM_SRC +=$(QUANTUM_DIR)/logging/print.c
OPT_DEFS += -DPRINTF_DISABLE_SUPPORT_FLOAT
OPT_DEFS += -DPRINTF_DISABLE_SUPPORT_EXPONENTIAL
OPT_DEFS += -DPRINTF_DISABLE_SUPPORT_LONG_LONG
OPT_DEFS += -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T
