BOOTLOADER = atmel-dfu

MOUSEKEY_ENABLE = yes
MOUSEKEY_INTERVAL = 16
MOUSEKEY_MAX_SPEED = 5

EXTRAKEY_ENABLE = yes       # Audio control and System control

# Via stuff
VIA_ENABLE = yes
LINK_TIME_OPTIMIZATION_ENABLE = yes
LEADER_ENABLE = no
FAUXCLICKY_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
KEY_LOCK_ENABLE = no
TERMINAL_ENABLE = no
