#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_REACTIVE
#define GRAVE_ESC_CTRL_OVERRIDE
#define RGBLIGHT_LAYERS
#define RGB_MATRIX_STARTUP_HUE 130
#define RGB_MATRIX_STARTUP_SAT 255
#define RGB_MATRIX_STARTUP_VAL 255

//Non-Shinethrough
// #define RGB_MATRIX_STARTUP_HUE 0
// #define RGB_MATRIX_STARTUP_SAT 0
// #define RGB_MATRIX_STARTUP_VAL 50