#define MIDI_ADVANCED
#define MIDI_USB

#define WS2812_DI_PIN GP22
#define RGBLIGHT_LED_COUNT 30
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB
#define MATRIX_ROWS 5
#define MATRIX_COLS 6

#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_ON true
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL