#define MIDI_ADVANCED
#define RGBLED_NUM 12
#ifndef RGBLIGHT_LED_COUNT
	#define RGBLIGHT_LED_COUNT RGBLED_NUM
#endif
#define WS2812_DI_PIN GP22
#define RGBLIGHT_LED_TYPE RGBW

#define MATRIX_ROWS 2
#define MATRIX_COLS 5

#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_ON true
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL