# Space-saving settings.
LTO_ENABLE = yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
