OLED_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = no
ENCODER_ENABLE = no
AUDIO_ENABLE = no
NKRO_ENABLE = no

MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_SUPPORTED = yes
BOOTMAGIC_ENABLE = yes
UNICODE_ENABLE = yes
SPLIT_KEYBOARD = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
LTO_ENABLE = yes
UNICODE_ENABLE = yes
OS_DETECTION_ENABLE = yes