MCU = atmega32u4
BOOTLOADER = caterina

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
UNICODE_ENABLE = yes
SPLIT_KEYBOARD = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes

LAYOUTS = split_3x5_3
