#pragma once

#ifndef TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD
#endif // TAPPING_FORCE_HOLD

#undef TAPPING_TERM
#define TAPPING_TERM 175

#define LSPO_KEYS MOD_LSFT, MOD_NONE, KC_LBRC
#define RSPC_KEYS MOD_RSFT, MOD_NONE, KC_RBRC
#define LCPO_KEYS MOD_LCTL, MOD_NONE, KC_MINS
#define RCPO_KEYS MOD_RCTL, MOD_NONE, KC_EQL
