MOUSEKEY_ENABLE     = no     # Mouse keys
RGBLIGHT_ENABLE     = yes    # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes         # Enable VIA
VIAL_ENABLE         = yes         # Enable VIAL
VIAL_INSECURE       = no
OLED_DRIVER_ENABLE  = no
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
QMK_SETTINGS        = no