data = {
    "TD(TD_QUOTES)":"\' \"",
    "DE_Z":"Z",
    "TD(TD_SLASH)":"/ \\",
    "LT(SPECIAL,KC_ENT)":"ENT_L01",
    "LT(SPECIAL2,KC_BSPC)":"BSP_L02",
    "LT(FKEYS,KC_SPC)":"SPC_FKeys",
    "LCTL(DE_Z)":"UNDO",
    "LCTL(LSFT(DE_Z))":"REDO",
    "DE_AT":"@",
    "DE_UNDS":"UNDS",
    "DE_MINS":"-",
    "DE_PIPE":"|",
    "TD(TD_AE)":"ä Ä",
    "TD(TD_OE)":"ö Ö",
    "TD(TD_UE)":"ü Ü",
    "DE_HASH":"#",
    "LSFT(KC_1)":"!",
    "LSFT(KC_MINS)":"?",
    "KC_EQL":"=",
    "DE_COLN":":",
    "DE_SCLN":";",
    "DE_SS":"ß",
    "DE_AMPR":"&",
    "DE_CIRC":"^",
    "DE_PERC":"%",
    "DE_PLUS":"+",
    "DE_TILD":"~",
    "DE_DLR":"$",
    "DE_ASTR":"*",
    "TD(TD_1_BRACKET)":"( [ {",
    "TD(TD_2_BRACKET)":") ] }",
    "DE_RABK":">",
    "DE_LABK":"<",
    "MO(MOUSE)":"Mouse",
    "LSFT(KC_8)":"(",
    "RALT(KC_8)":"[",
    "RALT(KC_7)":"{",
    "LSFT(KC_9)":")",
    "RALT(KC_9)":"]",
    "RALT(KC_0)":"}",
    "LCTL(KC_C)":"COPY",
    "LCTL(KC_X)":"CUT",
    "LCTL(KC_A)":"ALL",
    "LCTL(KC_V)":"PASTE",
    "LGUI(LSFT(KC_S))":"SCREEN",
    "LALT(LSFT(KC_TAB))":"SHIFT_+_ATAB",
    "LALT(KC_TAB)":"ATAB"
}
