#ifndef USERSPACE_CONFIG_H
#define USERSPACE_CONFIG_H

#define PREVENT_STUCK_MODIFIERS
#define IGNORE_MOD_TAP_INTERRUPT

#define RESET_LAYER 15

#ifdef KEYBOARD_1up60rgb
  #undef RGBLED_NUM
  #define RGBLED_NUM 16
#endif

#endif // !USERSPACE_CONFIG_H
