#ifndef USERSPACE_CONFIG_H
#define USERSPACE_CONFIG_H

#define PERMISSIVE_HOLD

#define RESET_LAYER 15

#define BOOTMAGIC_KEY_SALT KC_ESC
#define BOOTMAGIC_KEY_SKIP KC_I
#define BOOTMAGIC_KEY_EEPROM_CLEAR KC_E

#endif // !USERSPACE_CONFIG_H
