LTO_ENABLE = yes

USER_NAME := chrisgve

APPLE_FN_ENABLE = yes
NKRO_ENABLE = yes

SRC += chrisgve.c
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
RGBMATRIX_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
REDUCE_RGB = yes
SHIFT_ENABLE = yes
