// Copyright 2023 Jason Hazel (@jasonhazel)
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#define PERMISSIVE_HOLD
#define ONESHOT_TAP_TOGGLE 10
#define ONESHOT_TIMEOUT 500
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE
#define CIRQUE_DEVICE_GESTURES_SCROLL_ENABLE
