#define MOUSEKEY_DELAY             0
#define MOUSEKEY_INTERVAL          16
#define MOUSEKEY_MAX_SPEED         20
#define MOUSEKEY_TIME_TO_MAX       100
#define MOUSEKEY_WHEEL_DELAY       0
#define MOUSEKEY_WHEEL_MAX_SPEED   1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100
