// Copyright 2026 rkey-device
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#include_next <mcuconf.h>

/* 12 MHz crystal on board */
#undef STM32_PLLMUL_VALUE
#define STM32_PLLMUL_VALUE      6

#undef STM32_SPI_USE_SPI1
#define STM32_SPI_USE_SPI1 TRUE

#undef STM32_PPRE2
#define STM32_PPRE2 STM32_PPRE2_DIV1 // Должно быть DIV1

#undef STM32_DMA_USE_CHANNELS
#define STM32_DMA_USE_CHANNELS TRUE

#undef STM32_DAC_USE_DAC1_CH1
#define STM32_DAC_USE_DAC1_CH1 TRUE
#undef STM32_DAC_USE_DAC1_CH2
#define STM32_DAC_USE_DAC1_CH2 TRUE
#undef STM32_GPT_USE_TIM6
#define STM32_GPT_USE_TIM6 TRUE
#undef STM32_GPT_USE_TIM7
#define STM32_GPT_USE_TIM7 TRUE
#undef STM32_GPT_USE_TIM8
#define STM32_GPT_USE_TIM8 TRUE

#undef STM32_SPI_SPI1_TX_DMA_STREAM
#define STM32_SPI_SPI1_TX_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)


// #undef STM32_PWM_USE_TIM3
// #define STM32_PWM_USE_TIM3 TRUE

// #undef STM32_PWM_TIM3_CH2_DMA_STREAM
// #define STM32_PWM_TIM3_CH2_DMA_STREAM STM32_DMA_STREAM_ID(1, 3)
