#pragma once

#define POT1_PIN GP26

#define ENCODERS_PAD_A { GP14, GP21, GP19, GP17}
#define ENCODERS_PAD_B { GP15, GP22, GP20, GP18}
#define MAX_QUEUED_ENCODER_EVENTS 4

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE