ifndef QUANTUM_DIR
	include ../../../../Makefile
endif

API_SYSEX_ENABLE = no
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
BLUETOOTH_ENABLE = no
FAUXCLICKY_ENABLE = no
KEY_LOCK_ENABLE = no
RGBLIGHT_ENABLE = no
POINTING_DEVICE_ENABLE = no
AUDIO_ENABLE = no
#TAP_DANCE_ENABLE = yes
#PS2_MOUSE_ENABLE = yes
#PS2_USE_USART = yes
SRC += knob_v2.c taphold.c
