#
#             LUFA Library
#     Copyright (C) Dean Camera, 2013.
#
#  dean [at] fourwalledcubicle [dot] com
#           www.lufa-lib.org
#
# --------------------------------------
#         LUFA Project Makefile.
# --------------------------------------

# Run "make help" for target help.

MCU          = 
ARCH         = 
BOARD        = 
F_CPU        = $(F_USB)
F_USB        = 8000000
OPTIMIZATION = 1
TARGET       = Test
SRC          = $(TARGET).c
LUFA_PATH    = ../../LUFA
CC_FLAGS     = -Werror
DEBUG_LEVEL  = 0

# Include LUFA build script makefiles
include $(LUFA_PATH)/Build/lufa_build.mk