#
#             LUFA Library
#     Copyright (C) Dean Camera, 2012.
#
#  dean [at] fourwalledcubicle [dot] com
#           www.lufa-lib.org
#
# --------------------------------------
#         LUFA Project Makefile.
# --------------------------------------

MCU          = at90usb1287
ARCH         = AVR8
BOARD        = NONE
F_CPU        = 8000000
F_USB        = $(F_CPU)
OPTIMIZATION = 1
TARGET       = Test
SRC          = $(TARGET).c
LUFA_PATH    = ../../LUFA/
CC_FLAGS     = -Werror

# Include LUFA build script makefiles
include $(LUFA_PATH)/Build/lufa.build.in