RGBLIGHT_ENABLE = yes        # Enable WS2812 RGB underlight.  Do not enable this with audio at the same time.
AUDIO_ENABLE = no            # Audio disabled while using RGB underlight.

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
