OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = no
RGBLIGHT_ENABLE = yes
MOUSEKEY_ENABLE = yes

TAP_DANCE_ENABLE = no
STENO_ENABLE = no
BOOTMAGIC_ENABLE =no
TERMINAL_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
KEY_LOCK_ENABLE = no
AUDIO_ENABLE = no
CONSOLE_ENABLE = no
VELOCIKEY_ENABLE = no