#pragma once

#define TAPPING_TERM 150
#define RETRO_TAPPING

#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(NOCTURNE_OP_9_NO_1)
  #define AUDIO_CLICKY
  #define AUDIO_CLICKY_FREQ_RANDOMNESS 0.8f
#endif
