ifndef QUANTUM_DIR
	include ../../../../Makefile
endif

MOUSEKEY_ENABLE = no        # Mouse keys(+4700)
STENO_ENABLE = yes					# Enable TX Bolt protocol for Stenography, requires VIRTSER and may not work with mouse keys

