SRC += muse.c
SRC += tap.c
CONSOLE_ENABLE = no
LTO_ENABLE = yes

RGBLIGHT_ENABLE = yes
LEADER_ENABLE = no
AUDIO_ENABLE = yes
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
TERMINAL_ENABLE = no
KEY_LOCK_ENABLE = no
COMBO_ENABLE = yes

TAP_DANCE_ENABLE = yes
