MCU = atmega32u4

BOOTLOADER = caterina

BOOTMAGIC = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
MIDI_ENABLE = yes
AUDIO_ENABLE = yes
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
RGBLIGHT_ENABLE = yes

SLEEP_LED_ENABLE = no
SPLIT_KEYBOARD = yes
DEFAULT_FOLDER = lotus58/rev1
