/* SPDX-License-Identifier: GPL-2.0-or-later */

#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
		KC_NLCK, KC_PSLS, KC_PAST, KC_PMNS, KC_MUTE, 
    KC_P7, KC_P8, KC_P9, KC_PPLS, KC_TRNS, 
    KC_P4, KC_P5, KC_P6, KC_DEL, KC_TRNS, 
    KC_P1, KC_P2, KC_P3, KC_CALC, KC_TRNS,
    KC_P0, KC_PDOT, KC_COMM, KC_PENT, KC_ENT),

  	[1] = LAYOUT(
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ENT, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ENT, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ENT, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_ENT, 
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)

};


#ifdef ENCODER_MAP_ENABLE
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
  [0] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },
  [1] = { ENCODER_CCW_CW(_______, _______) }
};
#endif

