// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// reactive
#if defined(ENABLE_LED_MATRIX_SOLID_REACTIVE_SIMPLE)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_REACTIVE_WIDE)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTIWIDE)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_REACTIVE_CROSS)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTICROSS)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_REACTIVE_NEXUS)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_REACTIVE_MULTINEXUS)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_SPLASH)
#    define LED_MATRIX_KEYPRESSES
#endif
#if defined(ENABLE_LED_MATRIX_SOLID_MULTISPLASH)
#    define LED_MATRIX_KEYPRESSES
#endif
