MOUSEKEY_ENABLE = no    # Mouse keys
RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
EXTRAKEY_ENABLE = yes # for media keys
TAP_DANCE_ENABLE = yes
RGB_MATRIX_ENABLE = yes

SRC += oled.c

#Prueba 
BOOTMAGIC_ENABLE  =	no
SLEEP_LED_ENABLE  =	no
NKRO_ENABLE       =	no
BACKLIGHT_ENABLE  =	no
MIDI_ENABLE       =	no
UNICODE_ENABLE    =	no
BLUETOOTH_ENABLE  =	no
AUDIO_ENABLE      =	no
HD44780_ENABLE    =	no
FAUXCLICKY_ENABLE = no
CONSOLE_ENABLE    =	no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
#Prueba 

