SRC += art.c

COMBO_ENABLE = yes

# saving space
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no 
LTO_ENABLE = yes
MAGIC_ENABLE = no
# MOUSEKEY_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no