VIA_ENABLE = yes

MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes

TD_LSFT_CAPSLOCK_ENABLE = yes
STARTUP_NUMLOCK_ON = yes

BOOTMAGIC_ENABLE = lite     # Enable Bootmagic Lite

TD_LSFT_CAPSLOCK_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
ENCODER_DEFAULTACTIONS_ENABLE = yes
