VIA_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes

MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = yes

TD_LSFT_CAPSLOCK_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
ENCODER_DEFAULTACTIONS_ENABLE = yes
EMOTICON_ENABLE = yes
INVERT_NUMLOCK_INDICATOR = yes
