#pragma once

#define USB_POLLING_INTERVAL_MS 1
#define FORCE_NKRO

#define TAPPING_TERM 188
#define TAPPING_TERM_PER_KEY

#define COMBO_TERM 72
#define COMBO_KEY_BUFFER_LENGTH 16
#define COMBO_BUFFER_LENGTH 16
#define COMBO_STRICT_TIMER
#define EXTRA_SHORT_COMBOS


#define LEADER_TIMEOUT 480
#define LEADER_PER_KEY_TIMING

#define DYNAMIC_MACRO_SIZE 416
#define DYNAMIC_MACRO_DELAY 24

#define PROCESS_CUSTOM_SHIFT_KEYS

