#pragma once

// BACKLIGHT
#ifdef BACKLIGHT_ENABLE
#define BACKLIGHT_BREATHING
#define BREATHING_PERIOD 5
#endif // BACKLIGHT_ENABLE

// LED strip stuff
#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_HUE_STEP 6
#define RGBLIGHT_SAT_STEP 12
#define RGBLIGHT_VAL_STEP 20
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_SNAKE_LENGTH 6
#define RGBLIGHT_EFFECT_KNIGHT_LENGTH 2
#define RGBLIGHT_EFFECT_KNIGHT_OFFSET 6
#define RGBLIGHT_EFFECT_KNIGHT_LED_NUM 6
#define RGBLIGHT_EFFECT_CHRISTMAS_INTERVAL 2000
#define RGBLIGHT_EFFECT_CHRISTMAS_STEP 1
#ifdef KEYBOARD_planck_rev4
#define RGB_DI_PIN B2
#define RGBLED_NUM 12
#endif // KEYBOARD_planck_rev4
#endif // RGBLIGHT_ENABLE

#define ENCODER_RESOLUTION 4
