#pragma once

//#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
//#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U

#define SERIAL_USART_FULL_DUPLEX

#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
//#define SERIAL_USART_DRIVER SIO0

#define MASTER_RIGHT

//#define SERIAL_DEBUG

#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000
