== KLL vs TMK
1. **Shift** = Memontary
1. Latch = One shot
1. Lock  = Toggle

## KLL terminology
### Fall-through
When a key is undefined on a particular layer, the key
definition on the previously stacked layer will be used. Eventually
the key definition will be set to using the default layer. If the None
keyword is used, then the fall-through will stop and no action will
take place.
###Latch
When referring to keyboards, a key function that is only enabled
until the release of the next keypress.
###Lock
When referring to keyboards, a key function that is enabled until
that key is pressed again (e.g. Caps Lock).
### NKRO
N-Key Rollover is the capability to press N number of keys at the
same time on a keyboard and have them all register on the OS simultaneously.
### Scan Code
Row x Column code or native protocol code used by the keyboard.
### Shift
When referring to keyboards, a key function that is enabled while
that key is held.
### USB Code
Keyboard Press/Release codes as defined by the USB HID
Spec.