ENCODER_ENABLE = yes       # ENables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB light
LTO_ENABLE = yes 		   # significantly reduce the compiled size, but disable the legacy TMK Macros and Functions features
OLED_ENABLE = yes
OLED_DRIVER = SSD1306    # OLED display
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
WPM_ENABLE = yes
EXTRAFLAGS += -flto
MOUSEKEY_ENABLE = yes
