

MOUSEKEY_ENABLE      = yes    # Mouse keys
AUTO_SHIFT_ENABLE    = yes
DYNAMIC_MACRO_ENABLE = yes
EXTRAKEY_ENABLE      = yes

OLED_DRIVER_ENABLE  = no
RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = no
VIA_ENABLE          = no
LTO_ENABLE          = yes


SPLIT_KEYBOARD = yes
SPLIT_TRANSPORT = mirror

USER_NAME := greyhatmiddleman

PIMORONI_TRACKBALL_ENABLE = no

