// Copyright 2024 LLLKST (@LLLKST)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once


#define WS2812_DI_PIN B6
#define RGBLIGHT_LED_COUNT 28

//#define RGBLIGHT_LAYERS - for future
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_MODE_KNIGHT
#define RGBLIGHT_MODE_CHRISTMAS
#define RGBLIGHT_MODE_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_MODE_ALTERNATING
#define RGBLIGHT_MODE_TWINKLE
