BOOTMAGIC_ENABLE = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE = no
STENO_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = yes
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = yes
RGBLIGHT_ENABLE = yes
TAP_DANCE_ENABLE = no
UNICODE_ENABLE = yes
LEADER_ENABLE = yes

# from default
SRC += muse.c
