#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 150

#define COMBO_TERM 20
#define COMBO_COUNT 1

#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 100

#define USB_POLLING_INTERVAL_MS 1
