#define RGB_MATRIX_LED_COUNT 104

/* Enable CapsLcok LED*/
#define CAPS_LOCK_LED_INDEX 73
#define NUM_LOCK_LED_INDEX 19

#define DIP_SWITCH_PINS {B3}

#define SHR_SERIES_NUM 2
#define SHR_CLOCK_PIN A0
#define SHR_DATA_PIN A1
#define SHR_LATCH_PIN C15