
#define PMW33XX_CS_PIN GP10
#define PMW33XX_LIFTOFF_DISTANCE 0x03
#define POINTING_DEVICE_INVERT_Y
#undef DIODE_DIRECTION
#define DIODE_DIRECTION ROW2COL

#ifdef RGB_DI_PIN
#    undef RGB_DI_PIN
#endif

#define RGB_DI_PIN GP26

#define RGBLED_NUM 30
#define RGBLIGHT_ANIMATIONS
