# Build Options
#   change yes to no to disable
#

DEFAULT_FOLDER = crkbd/rev1

RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = yes