DEFAULT_FOLDER = crkbd/rev1
COMBO_ENABLE = yes
CONSOLE_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
SPLIT_KEYBOARD = yes
OLED_ENABLE = yes
LTO_ENABLE = yes
WPM_ENABLE = yes

SRC += global_vars.c
