#pragma once

#define MASTER_RIGHT
#define SPLIT_USB_DETECT

#define SPLIT_LAYER_STATE_ENABLE

#undef TAPPING_TERM
#define TAPPING_TERM 350
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define QUICK_TAP_TERM 0
