BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
COMMAND_ENABLE   = yes
CONSOLE_ENABLE   = yes
EXTRAKEY_ENABLE  = yes
MOUSEKEY_ENABLE  = yes
RGBLIGHT_ENABLE  = no
TAP_DANCE_ENABLE = yes
