#pragma once

#define PERMISSIVE_HOLD

#undef TAPPING_TERM
#define TAPPING_TERM 140

// #define RETRO_TAPPING

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 3

#define CAPS_LOCATION (MATRIX_COLS * 0 + 0)