# STM32 MCU settings for converting AVR projects
MCU := STM32F411
BOARD := STEMCELL
BOOTLOADER := tinyuf2
FIRMWARE_FORMAT := uf2

SERIAL_DRIVER ?= usart
WS2812_DRIVER ?= bitbang

OPT_DEFS += -DFEE_PAGE_BASE_ADDRESS=0x08008000

ifeq ($(strip $(STMC_US)), yes)
  CONVERT_TO_STEMCELL_UART_SWAP=yes
  OPT_DEFS += -DCONVERT_TO_STEMCELL_UART_SWAP
  OPT_DEFS += -DSERIAL_USART_DRIVER=SD2
endif

ifeq ($(strip $(STMC_IS)), yes)
  CONVERT_TO_STEMCELL_I2C_SWAP=yes
  OPT_DEFS += -DCONVERT_TO_STEMCELL_I2C_SWAP
endif
