#define TAPPING_TERM 200
#define LEADER_TIMEOUT 1000
#define TAPPING_TOGGLE 2
// Tapping this number of times holds the key until tapped once again.
#define ONESHOT_TAP_TOGGLE 3
// Time (in ms) before the one shot key is released
#define ONESHOT_TIMEOUT 200

#define MK_KINETIC_SPEED
#define MOUSEKEY_DELAY 5
#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_MOVE_DELTA 5
#define MOUSEKEY_INITIAL_SPEED 10
#define MOUSEKEY_BASE_SPEED 100
#define MOUSEKEY_DECELERATED_SPEED 400
#define MOUSEKEY_ACELERATED_SPEED 200
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 16
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMETS 48
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMETS 8

