TAP_DANCE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
SWAP_HANDS_ENABLE = yes
EXTRAFLAGS+=-flto
UNICODEMAP_ENABLE = yes



