# Build Options

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no

AUDIO_ENABLE = no
ENCODER_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
TAP_DANCE_ENABLE = no

EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no        # Console for debug
RGBLIGHT_ENABLE = yes 
RGB_MATRIX_ENABLE = no 
#RGB_MATRIX_ENABLE = yes
#RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes
VIA_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
