#include QMK_KEYBOARD_H

enum layers {
    DEFAULT,
    SUPER,
    META,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [DEFAULT] = LAYOUT(
      KC_ESC, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_F, KC_G, KC_C, KC_R, KC_L, KC_BSPC, KC_7, KC_8, KC_9,
  		KC_TAB, KC_A, KC_O, KC_E, KC_U, KC_I, KC_D, KC_H, KC_T, KC_N, KC_S, KC_4, KC_5, KC_6,
  		KC_LSFT, KC_SCLN, KC_Q, KC_J, KC_K, KC_X, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_1, KC_2, KC_3,
		KC_LCTL, KC_LALT, MO(SUPER), KC_SPC, KC_BSPC, MO(META), KC_LCTL, KC_NO, KC_NO, KC_NO, KC_0, KC_NLCK),

    [SUPER] = LAYOUT(
		KC_ESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_DELETE, KC_7, KC_8, KC_9,
		KC_TAB, KC_GRAVE, KC_MINUS, KC_EQUAL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_QUOT, KC_SCLN, KC_4, KC_5, KC_6,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SLASH, KC_BSLASH, KC_NO, KC_1, KC_2, KC_3,
		KC_LCTL, KC_LALT, KC_TRNS, KC_SPC, KC_LSFT, KC_TRNS, KC_LCTL, KC_NO, KC_NO, KC_NO, KC_0, KC_NLCK),

	  [META] = LAYOUT(
		KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, RGB_MOD, RGB_RMOD, RGB_SAI,
		KC_TAB, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT, RGB_HUI, RGB_HUD, RGB_SAD,
		KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_UP, RGB_VAI, RGB_VAD, KC_NO,
		KC_LCTL, KC_LALT, KC_TRNS, KC_SPC, KC_LSFT, KC_TRNS, KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG),

};
