// Copyright 2023 @miketronic -- Mike B <mxb540@gmail.com>
// SPDX-License-Identifier: GPL-2.0+

#pragma once

#    define TAPPING_TERM 170
#    define TAPPING_TERM_PER_KEY
#    define QUICK_TAP_TERM TAPPING_TERM / 2
#    define QUICK_TAP_TERM_PER_KEY
#    define PERMISSIVE_HOLD_PER_KEY
#    define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#    define IGNORE_MOD_TAP_INTERRUPT
#    define TAPPING_FORCE_HOLD
#    define ONESHOT_TAP_TOGGLE 10
#    define ONESHOT_TIMEOUT 500
#    define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#    define CIRQUE_PINNACLE_TAP_ENABLE
#    define CIRQUE_PINNACLE_POSITION_MODE  CIRQUE_PINNACLE_ABSOLUTE_MODE 
#    define CIRQUE_DEVICE_GESTURES_SCROLL_ENABLE 