COMBO_ENABLE        = yes
CONSOLE_ENABLE      = no
EXTRAKEY_ENABLE     = yes
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE       = yes
LTO_ENABLE          = yes
MIDI_ENABLE         = no
MOUSEKEY_ENABLE     = yes      # Mouse keys
NKRO_ENABLE         = yes      # Enable N-Key Rollover
OLED_DRIVER         = SSD1306
OLED_ENABLE         = yes
RAW_ENABLE          = no
RGBLIGHT_ENABLE     = yes      # Enable WS2812 RGB underlight.
TAP_DANCE_ENABLE    = yes
VIA_ENABLE          = yes      # Enable VIA
VIRTSER_ENABLE      = no
